// Code generated by "enumer -type=HeaderType,TrailerType --linecomment -output=header_enums.go"; DO NOT EDIT.

//
package hl7v2

import (
	"fmt"
)

const _HeaderTypeName = "MSHFHSBHS"

var _HeaderTypeIndex = [...]uint8{0, 3, 6, 9}

func (i HeaderType) String() string {
	if i < 0 || i >= HeaderType(len(_HeaderTypeIndex)-1) {
		return fmt.Sprintf("HeaderType(%d)", i)
	}
	return _HeaderTypeName[_HeaderTypeIndex[i]:_HeaderTypeIndex[i+1]]
}

var _HeaderTypeValues = []HeaderType{0, 1, 2}

var _HeaderTypeNameToValueMap = map[string]HeaderType{
	_HeaderTypeName[0:3]: 0,
	_HeaderTypeName[3:6]: 1,
	_HeaderTypeName[6:9]: 2,
}

// HeaderTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HeaderTypeString(s string) (HeaderType, error) {
	if val, ok := _HeaderTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HeaderType values", s)
}

// HeaderTypeValues returns all values of the enum
func HeaderTypeValues() []HeaderType {
	return _HeaderTypeValues
}

// IsAHeaderType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HeaderType) IsAHeaderType() bool {
	for _, v := range _HeaderTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _TrailerTypeName = "_FTSBTS"

var _TrailerTypeIndex = [...]uint8{0, 1, 4, 7}

func (i TrailerType) String() string {
	if i < 0 || i >= TrailerType(len(_TrailerTypeIndex)-1) {
		return fmt.Sprintf("TrailerType(%d)", i)
	}
	return _TrailerTypeName[_TrailerTypeIndex[i]:_TrailerTypeIndex[i+1]]
}

var _TrailerTypeValues = []TrailerType{0, 1, 2}

var _TrailerTypeNameToValueMap = map[string]TrailerType{
	_TrailerTypeName[0:1]: 0,
	_TrailerTypeName[1:4]: 1,
	_TrailerTypeName[4:7]: 2,
}

// TrailerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TrailerTypeString(s string) (TrailerType, error) {
	if val, ok := _TrailerTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TrailerType values", s)
}

// TrailerTypeValues returns all values of the enum
func TrailerTypeValues() []TrailerType {
	return _TrailerTypeValues
}

// IsATrailerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TrailerType) IsATrailerType() bool {
	for _, v := range _TrailerTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
