// Code generated by "enumer -type=Version --linecomment -output=version_enums.go"; DO NOT EDIT.

//
package hl7v2

import (
	"fmt"
)

const _VersionName = "unknown2.12.22.32.3.12.42.52.5.12.62.72.7.12.82.8.12.8.22.9"

var _VersionIndex = [...]uint8{0, 7, 10, 13, 16, 21, 24, 27, 32, 35, 38, 43, 46, 51, 56, 59}

func (i Version) String() string {
	if i < 0 || i >= Version(len(_VersionIndex)-1) {
		return fmt.Sprintf("Version(%d)", i)
	}
	return _VersionName[_VersionIndex[i]:_VersionIndex[i+1]]
}

var _VersionValues = []Version{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

var _VersionNameToValueMap = map[string]Version{
	_VersionName[0:7]:   0,
	_VersionName[7:10]:  1,
	_VersionName[10:13]: 2,
	_VersionName[13:16]: 3,
	_VersionName[16:21]: 4,
	_VersionName[21:24]: 5,
	_VersionName[24:27]: 6,
	_VersionName[27:32]: 7,
	_VersionName[32:35]: 8,
	_VersionName[35:38]: 9,
	_VersionName[38:43]: 10,
	_VersionName[43:46]: 11,
	_VersionName[46:51]: 12,
	_VersionName[51:56]: 13,
	_VersionName[56:59]: 14,
}

// VersionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VersionString(s string) (Version, error) {
	if val, ok := _VersionNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Version values", s)
}

// VersionValues returns all values of the enum
func VersionValues() []Version {
	return _VersionValues
}

// IsAVersion returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Version) IsAVersion() bool {
	for _, v := range _VersionValues {
		if i == v {
			return true
		}
	}
	return false
}
