// Code generated by gen_hl7v2. DO NOT EDIT.

package v25

import (
	"github.com/blushift-io/hl7v2"
	"github.com/blushift-io/hl7v2/schema"
	_ "github.com/blushift-io/hl7v2/schema/spec/v25"
)

func Version() hl7v2.Version {
	return hl7v2.Version25
}

func Schema() *schema.Schema {
	return schema.Open(Version().String())
}
