// Code generated by gen_hl7v2. DO NOT EDIT.

package v21

// AD - Address
type AD string

func NewAD(s string) *AD {
	v := AD(s)
	return &v
}

func (d AD) Validate() error {
	return nil
}

// CE - Coded Element
type CE struct {
	Identifier                  ID `hl7:"1"`
	Text                        ST `hl7:"2"`
	NameOfCodingSystem          ST `hl7:"3"`
	AlternateIdentifier         ST `hl7:"4"`
	AlternateText               ST `hl7:"5"`
	NameOfAlternateCodingSystem ST `hl7:"6"`
}

func NewCE() *CE {
	return &CE{}
}

func (d *CE) Validate() error {

	return nil
}

func (d *CE) SetIdentifier(v string) *CE {
	d.Identifier = ID(v)
	return d
}

func (d *CE) SetText(v string) *CE {
	d.Text = ST(v)
	return d
}

func (d *CE) SetNameOfCodingSystem(v string) *CE {
	d.NameOfCodingSystem = ST(v)
	return d
}

func (d *CE) SetAlternateIdentifier(v string) *CE {
	d.AlternateIdentifier = ST(v)
	return d
}

func (d *CE) SetAlternateText(v string) *CE {
	d.AlternateText = ST(v)
	return d
}

func (d *CE) SetNameOfAlternateCodingSystem(v string) *CE {
	d.NameOfAlternateCodingSystem = ST(v)
	return d
}

// CE_0057 -
type CE_0057 string

func NewCE_0057(s string) *CE_0057 {
	v := CE_0057(s)
	return &v
}

func (d CE_0057) Validate() error {
	return nil
}

// CK - Composite Id With Check Digit
type CK string

func NewCK(s string) *CK {
	v := CK(s)
	return &v
}

func (d CK) Validate() error {
	return nil
}

// CM -
type CM string

func NewCM(s string) *CM {
	v := CM(s)
	return &v
}

func (d CM) Validate() error {
	return nil
}

// CM_UNDEFINED - Undefined Cm Data Type
type CM_UNDEFINED string

func NewCM_UNDEFINED(s string) *CM_UNDEFINED {
	v := CM_UNDEFINED(s)
	return &v
}

func (d CM_UNDEFINED) Validate() error {
	return nil
}

// CN - Composite Id Number And Name
type CN string

func NewCN(s string) *CN {
	v := CN(s)
	return &v
}

func (d CN) Validate() error {
	return nil
}

// COMP_ID_DIGIT - Composite Id W/chk Digit
type COMP_ID_DIGIT string

func NewCOMP_ID_DIGIT(s string) *COMP_ID_DIGIT {
	v := COMP_ID_DIGIT(s)
	return &v
}

func (d COMP_ID_DIGIT) Validate() error {
	return nil
}

// COMP_ID_NAME - Composite Id And Name
type COMP_ID_NAME string

func NewCOMP_ID_NAME(s string) *COMP_ID_NAME {
	v := COMP_ID_NAME(s)
	return &v
}

func (d COMP_ID_NAME) Validate() error {
	return nil
}

// COMP_QUANT - Composite Quantity/units
type COMP_QUANT string

func NewCOMP_QUANT(s string) *COMP_QUANT {
	v := COMP_QUANT(s)
	return &v
}

func (d COMP_QUANT) Validate() error {
	return nil
}

// CQ - Composite Quantity With Units
type CQ string

func NewCQ(s string) *CQ {
	v := CQ(s)
	return &v
}

func (d CQ) Validate() error {
	return nil
}

// DT - Date
type DT string

func NewDT(s string) *DT {
	v := DT(s)
	return &v
}

func (d DT) Validate() error {
	return nil
}

// FT - Formatted Text Data
type FT string

func NewFT(s string) *FT {
	v := FT(s)
	return &v
}

func (d FT) Validate() error {
	return nil
}

// ID - Coded Value
type ID string

func NewID(s string) *ID {
	v := ID(s)
	return &v
}

func (d ID) Validate() error {
	return nil
}

// NM - Numeric
type NM string

func NewNM(s string) *NM {
	v := NM(s)
	return &v
}

func (d NM) Validate() error {
	return nil
}

// PN - Person Name
type PN string

func NewPN(s string) *PN {
	v := PN(s)
	return &v
}

func (d PN) Validate() error {
	return nil
}

// SET_ID - Set Id
type SET_ID string

func NewSET_ID(s string) *SET_ID {
	v := SET_ID(s)
	return &v
}

func (d SET_ID) Validate() error {
	return nil
}

// SI - Set Id
type SI string

func NewSI(s string) *SI {
	v := SI(s)
	return &v
}

func (d SI) Validate() error {
	return nil
}

// ST - String Data
type ST string

func NewST(s string) *ST {
	v := ST(s)
	return &v
}

func (d ST) Validate() error {
	return nil
}

// TM - Time
type TM string

func NewTM(s string) *TM {
	v := TM(s)
	return &v
}

func (d TM) Validate() error {
	return nil
}

// TN - Telephone Number
type TN string

func NewTN(s string) *TN {
	v := TN(s)
	return &v
}

func (d TN) Validate() error {
	return nil
}

// TS - Time Stamp
type TS string

func NewTS(s string) *TS {
	v := TS(s)
	return &v
}

func (d TS) Validate() error {
	return nil
}

// TX - Text Data
type TX string

func NewTX(s string) *TX {
	v := TX(s)
	return &v
}

func (d TX) Validate() error {
	return nil
}
