// Code generated by gen_hl7v2. DO NOT EDIT.

package v21

// AD - Address
type AD string

// CE - Coded Element
type CE struct {
	Identifier                  ID `hl7:"1"`
	Text                        ST `hl7:"2"`
	NameOfCodingSystem          ST `hl7:"3"`
	AlternateIdentifier         ST `hl7:"4"`
	AlternateText               ST `hl7:"5"`
	NameOfAlternateCodingSystem ST `hl7:"6"`
}

// CE_0057 -
type CE_0057 string

// CK - Composite Id With Check Digit
type CK string

// CM -
type CM string

// CM_UNDEFINED - Undefined Cm Data Type
type CM_UNDEFINED string

// CN - Composite Id Number And Name
type CN string

// COMP_ID_DIGIT - Composite Id W/chk Digit
type COMP_ID_DIGIT string

// COMP_ID_NAME - Composite Id And Name
type COMP_ID_NAME string

// COMP_QUANT - Composite Quantity/units
type COMP_QUANT string

// CQ - Composite Quantity With Units
type CQ string

// DT - Date
type DT string

// FT - Formatted Text Data
type FT string

// ID - Coded Value
type ID string

// NM - Numeric
type NM string

// PN - Person Name
type PN string

// SET_ID - Set Id
type SET_ID string

// SI - Set Id
type SI string

// ST - String Data
type ST string

// TM - Time
type TM string

// TN - Telephone Number
type TN string

// TS - Time Stamp
type TS string

// TX - Text Data
type TX string
