// Code generated by gen_hl7v2. DO NOT EDIT.

package v21

// ADT_A01 - Admit a Patient
type ADT_A01 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	NK1 NK1 `hl7:"NK1,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A02 - Transfer a Patient
type ADT_A02 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A03 - Discharge a Patient
type ADT_A03 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A04 - Register a Patient
type ADT_A04 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	NK1 NK1 `hl7:"NK1,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A05 - admit a Patient
type ADT_A05 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	NK1 NK1 `hl7:"NK1,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A06 - Transfer an Outpatient to Inpatient
type ADT_A06 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A07 - Transfer an Inpatient to Outpatient
type ADT_A07 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A08 - Update Patient Information
type ADT_A08 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	NK1 NK1 `hl7:"NK1,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A09 - Patient Departing
type ADT_A09 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A10 - Patient Arriving
type ADT_A10 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A11 - Cancel Admit
type ADT_A11 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A12 - Cancel Transfer
type ADT_A12 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A13 - Cancel Discharge
type ADT_A13 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A14 - Pending Admit
type ADT_A14 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PD1 PD1 `hl7:"PD1,required"`
	NK1 NK1 `hl7:"NK1,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A15 - Pending Transfer
type ADT_A15 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

// ADT_A16 - Pending Discharge
type ADT_A16 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
	DG1 DG1 `hl7:"DG1"`
}

type ADT_A17_PATIENT struct {
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A17 - Swap Patients
type ADT_A17 struct {
	MSH     MSH               `hl7:"MSH,required"`
	EVN     EVN               `hl7:"EVN,required"`
	PATIENT []ADT_A17_PATIENT `hl7:"PATIENT,required"`
}

// ADT_A18 - Merge Patient Information
type ADT_A18 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	MRG MRG `hl7:"MRG,required"`
	PV1 PV1 `hl7:"PV1"`
}

// ADT_A20 - Nursing/Census Application Updates
type ADT_A20 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	NPU NPU `hl7:"NPU,required"`
}

// ADT_A21 - A Patient Goes On A "Leave Of Absence"
type ADT_A21 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A22 - A Patient Returns From A "Leave Of Absence"
type ADT_A22 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A23 - Delete a Patient Record
type ADT_A23 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A24 - Create a Patient Link Transaction
type ADT_A24 struct {
	MSH  MSH `hl7:"MSH,required"`
	EVN  EVN `hl7:"EVN,required"`
	PID  PID `hl7:"PID,required"`
	PV1  PV1 `hl7:"PV1,required"`
	PID2 PID `hl7:"PID,required"`
}

type BAR_P01_VISIT struct {
	PV1 PV1   `hl7:"PV1"`
	DG1 []DG1 `hl7:"DG1"`
	PR1 []PR1 `hl7:"PR1"`
	GT1 []GT1 `hl7:"GT1"`
	NK1 []NK1 `hl7:"NK1"`
	IN1 []IN1 `hl7:"IN1"`
	ACC ACC   `hl7:"ACC"`
	UB1 UB1   `hl7:"UB1"`
}

// BAR_P01 - Add and Update Patient Accounts
type BAR_P01 struct {
	MSH   MSH             `hl7:"MSH,required"`
	EVN   EVN             `hl7:"EVN,required"`
	PID   PID             `hl7:"PID,required"`
	VISIT []BAR_P01_VISIT `hl7:"VISIT,required"`
}

type BAR_P02_PATIENT struct {
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1"`
}

// BAR_P02 - Purge Patient Accounts
type BAR_P02 struct {
	MSH     MSH               `hl7:"MSH,required"`
	EVN     EVN               `hl7:"EVN,required"`
	PATIENT []BAR_P02_PATIENT `hl7:"PATIENT,required"`
}

// DFT_P03 - Post Detail Financial Transactions
type DFT_P03 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1"`
	FT1 []FT1 `hl7:"FT1"`
}

// DSR_Q03 - Deferred Response to A Query
type DSR_Q03 struct {
	MSH MSH   `hl7:"MSH,required"`
	QRD QRD   `hl7:"QRD,required"`
	QRF QRF   `hl7:"QRF"`
	DSP []DSP `hl7:"DSP,required"`
	DSC DSC   `hl7:"DSC,required"`
}

type ORM_O01_ORDERDETAIL struct {
	OBR  OBR   `hl7:"OBR,required"`
	NTE  []NTE `hl7:"NTE"`
	OBX  []OBX `hl7:"OBX"`
	NTE2 []NTE `hl7:"NTE"`
	BLG  BLG   `hl7:"BLG"`
}

type ORM_O01_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL ORM_O01_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

type ORM_O01_PATIENT struct {
	PID   PID             `hl7:"PID,required"`
	NTE   []NTE           `hl7:"NTE"`
	PV1   PV1             `hl7:"PV1"`
	ORDER []ORM_O01_ORDER `hl7:"ORDER,required"`
}

// ORM_O01 - Order Message
type ORM_O01 struct {
	MSH     MSH             `hl7:"MSH,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT ORM_O01_PATIENT `hl7:"PATIENT"`
}

type ORR_O02_ORDERDETAIL struct {
	OBR OBR   `hl7:"OBR,required"`
	NTE []NTE `hl7:"NTE"`
}

type ORR_O02_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL ORR_O02_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

type ORR_O02_PATIENT struct {
	PID   PID             `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []ORR_O02_ORDER `hl7:"ORDER,required"`
}

// ORR_O02 - Respone Message
type ORR_O02 struct {
	MSH     MSH             `hl7:"MSH,required"`
	MSA     MSA             `hl7:"MSA,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT ORR_O02_PATIENT `hl7:"PATIENT"`
}

type ORU_R01_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
	DSC DSC   `hl7:"DSC"`
}

type ORU_R01_ORDEROBSERVATION struct {
	ORC         ORC                   `hl7:"ORC"`
	OBR         OBR                   `hl7:"OBR,required"`
	NTE         []NTE                 `hl7:"NTE"`
	OBSERVATION []ORU_R01_OBSERVATION `hl7:"OBSERVATION,required"`
}

type ORU_R01_PATIENT struct {
	PID              PID                        `hl7:"PID,required"`
	NTE              []NTE                      `hl7:"NTE"`
	PV1              PV1                        `hl7:"PV1"`
	ORDEROBSERVATION []ORU_R01_ORDEROBSERVATION `hl7:"ORDER_OBSERVATION,required"`
}

type ORU_R01_PATIENTRESULT struct {
	PATIENT ORU_R01_PATIENT `hl7:"PATIENT"`
}

// ORU_R01 - Unsolicited transmission of requested Obersvation
type ORU_R01 struct {
	MSH           MSH                     `hl7:"MSH,required"`
	PATIENTRESULT []ORU_R01_PATIENTRESULT `hl7:"PATIENT_RESULT,required"`
}

type ORU_R03_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
	DSC DSC   `hl7:"DSC"`
}

type ORU_R03_ORDEROBSERVATION struct {
	ORC         ORC                   `hl7:"ORC"`
	OBR         OBR                   `hl7:"OBR,required"`
	NTE         []NTE                 `hl7:"NTE"`
	OBSERVATION []ORU_R03_OBSERVATION `hl7:"OBSERVATION,required"`
}

type ORU_R03_PATIENT struct {
	PID              PID                        `hl7:"PID,required"`
	NTE              []NTE                      `hl7:"NTE"`
	PV1              PV1                        `hl7:"PV1"`
	ORDEROBSERVATION []ORU_R03_ORDEROBSERVATION `hl7:"ORDER_OBSERVATION,required"`
}

type ORU_R03_PATIENTRESULT struct {
	PATIENT ORU_R03_PATIENT `hl7:"PATIENT"`
}

// ORU_R03 - Display oriented results, queyr/unsol. update
type ORU_R03 struct {
	MSH           MSH                     `hl7:"MSH,required"`
	PATIENTRESULT []ORU_R03_PATIENTRESULT `hl7:"PATIENT_RESULT,required"`
}

// QRY_A19 - Patient Query
type QRY_A19 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
}

// QRY_Q01 - A Query is Made for Immediate Response
type QRY_Q01 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC,required"`
}

// QRY_Q02 - A Query is Sent for Deferred Response
type QRY_Q02 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC,required"`
}

// UDM_Q05 - Unsolicited Updates, ODM Message, Trigger Event Q05
type UDM_Q05 struct {
	MSH MSH   `hl7:"MSH,required"`
	URD URD   `hl7:"URD,required"`
	URS URS   `hl7:"URS"`
	DSP []DSP `hl7:"DSP,required"`
	DSC DSC   `hl7:"DSC,required"`
}
