// Code generated by gen_hl7v2. DO NOT EDIT.

package v21

import (
	"fmt"
)

// ADT_A01 - Admit a Patient
type ADT_A01 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	NK1 *NK1 `hl7:"NK1,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A01() *ADT_A01 {
	return &ADT_A01{
		MSH: NewMSH(NewID("ADT_A01")),
	}
}

func (m *ADT_A01) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A01.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A01.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A01.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A01.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A01.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A01.PID: %w", err)
		}
	}

	if m.NK1 == nil {
		return fmt.Errorf("ADT_A01.NK1 is required")
	}
	if m.NK1 != nil {
		if err := m.NK1.Validate(); err != nil {
			return fmt.Errorf("ADT_A01.NK1: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A01.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A01.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A01.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A01) SetMSH(v *MSH) *ADT_A01 {
	m.MSH = v
	return m
}

func (m *ADT_A01) SetEVN(v *EVN) *ADT_A01 {
	m.EVN = v
	return m
}

func (m *ADT_A01) SetPID(v *PID) *ADT_A01 {
	m.PID = v
	return m
}

func (m *ADT_A01) SetNK1(v *NK1) *ADT_A01 {
	m.NK1 = v
	return m
}

func (m *ADT_A01) SetPV1(v *PV1) *ADT_A01 {
	m.PV1 = v
	return m
}

func (m *ADT_A01) SetDG1(v *DG1) *ADT_A01 {
	m.DG1 = v
	return m
}

// ADT_A02 - Transfer a Patient
type ADT_A02 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A02() *ADT_A02 {
	return &ADT_A02{
		MSH: NewMSH(NewID("ADT_A02")),
	}
}

func (m *ADT_A02) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A02.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A02.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A02.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A02.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A02.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A02.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A02.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A02.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A02) SetMSH(v *MSH) *ADT_A02 {
	m.MSH = v
	return m
}

func (m *ADT_A02) SetEVN(v *EVN) *ADT_A02 {
	m.EVN = v
	return m
}

func (m *ADT_A02) SetPID(v *PID) *ADT_A02 {
	m.PID = v
	return m
}

func (m *ADT_A02) SetPV1(v *PV1) *ADT_A02 {
	m.PV1 = v
	return m
}

// ADT_A03 - Discharge a Patient
type ADT_A03 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A03() *ADT_A03 {
	return &ADT_A03{
		MSH: NewMSH(NewID("ADT_A03")),
	}
}

func (m *ADT_A03) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A03.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A03.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A03.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A03.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A03.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A03.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A03.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A03.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A03) SetMSH(v *MSH) *ADT_A03 {
	m.MSH = v
	return m
}

func (m *ADT_A03) SetEVN(v *EVN) *ADT_A03 {
	m.EVN = v
	return m
}

func (m *ADT_A03) SetPID(v *PID) *ADT_A03 {
	m.PID = v
	return m
}

func (m *ADT_A03) SetPV1(v *PV1) *ADT_A03 {
	m.PV1 = v
	return m
}

// ADT_A04 - Register a Patient
type ADT_A04 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	NK1 *NK1 `hl7:"NK1,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A04() *ADT_A04 {
	return &ADT_A04{
		MSH: NewMSH(NewID("ADT_A04")),
	}
}

func (m *ADT_A04) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A04.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A04.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A04.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A04.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A04.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A04.PID: %w", err)
		}
	}

	if m.NK1 == nil {
		return fmt.Errorf("ADT_A04.NK1 is required")
	}
	if m.NK1 != nil {
		if err := m.NK1.Validate(); err != nil {
			return fmt.Errorf("ADT_A04.NK1: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A04.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A04.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A04.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A04) SetMSH(v *MSH) *ADT_A04 {
	m.MSH = v
	return m
}

func (m *ADT_A04) SetEVN(v *EVN) *ADT_A04 {
	m.EVN = v
	return m
}

func (m *ADT_A04) SetPID(v *PID) *ADT_A04 {
	m.PID = v
	return m
}

func (m *ADT_A04) SetNK1(v *NK1) *ADT_A04 {
	m.NK1 = v
	return m
}

func (m *ADT_A04) SetPV1(v *PV1) *ADT_A04 {
	m.PV1 = v
	return m
}

func (m *ADT_A04) SetDG1(v *DG1) *ADT_A04 {
	m.DG1 = v
	return m
}

// ADT_A05 - admit a Patient
type ADT_A05 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	NK1 *NK1 `hl7:"NK1,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A05() *ADT_A05 {
	return &ADT_A05{
		MSH: NewMSH(NewID("ADT_A05")),
	}
}

func (m *ADT_A05) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A05.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A05.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A05.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A05.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A05.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A05.PID: %w", err)
		}
	}

	if m.NK1 == nil {
		return fmt.Errorf("ADT_A05.NK1 is required")
	}
	if m.NK1 != nil {
		if err := m.NK1.Validate(); err != nil {
			return fmt.Errorf("ADT_A05.NK1: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A05.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A05.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A05.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A05) SetMSH(v *MSH) *ADT_A05 {
	m.MSH = v
	return m
}

func (m *ADT_A05) SetEVN(v *EVN) *ADT_A05 {
	m.EVN = v
	return m
}

func (m *ADT_A05) SetPID(v *PID) *ADT_A05 {
	m.PID = v
	return m
}

func (m *ADT_A05) SetNK1(v *NK1) *ADT_A05 {
	m.NK1 = v
	return m
}

func (m *ADT_A05) SetPV1(v *PV1) *ADT_A05 {
	m.PV1 = v
	return m
}

func (m *ADT_A05) SetDG1(v *DG1) *ADT_A05 {
	m.DG1 = v
	return m
}

// ADT_A06 - Transfer an Outpatient to Inpatient
type ADT_A06 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A06() *ADT_A06 {
	return &ADT_A06{
		MSH: NewMSH(NewID("ADT_A06")),
	}
}

func (m *ADT_A06) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A06.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A06.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A06.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A06.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A06.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A06.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A06.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A06.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A06) SetMSH(v *MSH) *ADT_A06 {
	m.MSH = v
	return m
}

func (m *ADT_A06) SetEVN(v *EVN) *ADT_A06 {
	m.EVN = v
	return m
}

func (m *ADT_A06) SetPID(v *PID) *ADT_A06 {
	m.PID = v
	return m
}

func (m *ADT_A06) SetPV1(v *PV1) *ADT_A06 {
	m.PV1 = v
	return m
}

// ADT_A07 - Transfer an Inpatient to Outpatient
type ADT_A07 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A07() *ADT_A07 {
	return &ADT_A07{
		MSH: NewMSH(NewID("ADT_A07")),
	}
}

func (m *ADT_A07) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A07.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A07.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A07.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A07.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A07.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A07.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A07.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A07.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A07) SetMSH(v *MSH) *ADT_A07 {
	m.MSH = v
	return m
}

func (m *ADT_A07) SetEVN(v *EVN) *ADT_A07 {
	m.EVN = v
	return m
}

func (m *ADT_A07) SetPID(v *PID) *ADT_A07 {
	m.PID = v
	return m
}

func (m *ADT_A07) SetPV1(v *PV1) *ADT_A07 {
	m.PV1 = v
	return m
}

// ADT_A08 - Update Patient Information
type ADT_A08 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	NK1 *NK1 `hl7:"NK1,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A08() *ADT_A08 {
	return &ADT_A08{
		MSH: NewMSH(NewID("ADT_A08")),
	}
}

func (m *ADT_A08) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A08.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A08.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A08.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A08.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A08.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A08.PID: %w", err)
		}
	}

	if m.NK1 == nil {
		return fmt.Errorf("ADT_A08.NK1 is required")
	}
	if m.NK1 != nil {
		if err := m.NK1.Validate(); err != nil {
			return fmt.Errorf("ADT_A08.NK1: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A08.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A08.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A08.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A08) SetMSH(v *MSH) *ADT_A08 {
	m.MSH = v
	return m
}

func (m *ADT_A08) SetEVN(v *EVN) *ADT_A08 {
	m.EVN = v
	return m
}

func (m *ADT_A08) SetPID(v *PID) *ADT_A08 {
	m.PID = v
	return m
}

func (m *ADT_A08) SetNK1(v *NK1) *ADT_A08 {
	m.NK1 = v
	return m
}

func (m *ADT_A08) SetPV1(v *PV1) *ADT_A08 {
	m.PV1 = v
	return m
}

func (m *ADT_A08) SetDG1(v *DG1) *ADT_A08 {
	m.DG1 = v
	return m
}

// ADT_A09 - Patient Departing
type ADT_A09 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A09() *ADT_A09 {
	return &ADT_A09{
		MSH: NewMSH(NewID("ADT_A09")),
	}
}

func (m *ADT_A09) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A09.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A09.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A09.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A09.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A09.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A09.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A09.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A09.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A09.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A09) SetMSH(v *MSH) *ADT_A09 {
	m.MSH = v
	return m
}

func (m *ADT_A09) SetEVN(v *EVN) *ADT_A09 {
	m.EVN = v
	return m
}

func (m *ADT_A09) SetPID(v *PID) *ADT_A09 {
	m.PID = v
	return m
}

func (m *ADT_A09) SetPV1(v *PV1) *ADT_A09 {
	m.PV1 = v
	return m
}

func (m *ADT_A09) SetDG1(v *DG1) *ADT_A09 {
	m.DG1 = v
	return m
}

// ADT_A10 - Patient Arriving
type ADT_A10 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A10() *ADT_A10 {
	return &ADT_A10{
		MSH: NewMSH(NewID("ADT_A10")),
	}
}

func (m *ADT_A10) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A10.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A10.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A10.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A10.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A10.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A10.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A10.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A10.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A10.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A10) SetMSH(v *MSH) *ADT_A10 {
	m.MSH = v
	return m
}

func (m *ADT_A10) SetEVN(v *EVN) *ADT_A10 {
	m.EVN = v
	return m
}

func (m *ADT_A10) SetPID(v *PID) *ADT_A10 {
	m.PID = v
	return m
}

func (m *ADT_A10) SetPV1(v *PV1) *ADT_A10 {
	m.PV1 = v
	return m
}

func (m *ADT_A10) SetDG1(v *DG1) *ADT_A10 {
	m.DG1 = v
	return m
}

// ADT_A11 - Cancel Admit
type ADT_A11 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A11() *ADT_A11 {
	return &ADT_A11{
		MSH: NewMSH(NewID("ADT_A11")),
	}
}

func (m *ADT_A11) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A11.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A11.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A11.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A11.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A11.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A11.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A11.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A11.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A11.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A11) SetMSH(v *MSH) *ADT_A11 {
	m.MSH = v
	return m
}

func (m *ADT_A11) SetEVN(v *EVN) *ADT_A11 {
	m.EVN = v
	return m
}

func (m *ADT_A11) SetPID(v *PID) *ADT_A11 {
	m.PID = v
	return m
}

func (m *ADT_A11) SetPV1(v *PV1) *ADT_A11 {
	m.PV1 = v
	return m
}

func (m *ADT_A11) SetDG1(v *DG1) *ADT_A11 {
	m.DG1 = v
	return m
}

// ADT_A12 - Cancel Transfer
type ADT_A12 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A12() *ADT_A12 {
	return &ADT_A12{
		MSH: NewMSH(NewID("ADT_A12")),
	}
}

func (m *ADT_A12) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A12.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A12.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A12.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A12.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A12.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A12.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A12.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A12.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A12.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A12) SetMSH(v *MSH) *ADT_A12 {
	m.MSH = v
	return m
}

func (m *ADT_A12) SetEVN(v *EVN) *ADT_A12 {
	m.EVN = v
	return m
}

func (m *ADT_A12) SetPID(v *PID) *ADT_A12 {
	m.PID = v
	return m
}

func (m *ADT_A12) SetPV1(v *PV1) *ADT_A12 {
	m.PV1 = v
	return m
}

func (m *ADT_A12) SetDG1(v *DG1) *ADT_A12 {
	m.DG1 = v
	return m
}

// ADT_A13 - Cancel Discharge
type ADT_A13 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A13() *ADT_A13 {
	return &ADT_A13{
		MSH: NewMSH(NewID("ADT_A13")),
	}
}

func (m *ADT_A13) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A13.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A13.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A13.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A13.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A13.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A13.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A13.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A13.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A13.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A13) SetMSH(v *MSH) *ADT_A13 {
	m.MSH = v
	return m
}

func (m *ADT_A13) SetEVN(v *EVN) *ADT_A13 {
	m.EVN = v
	return m
}

func (m *ADT_A13) SetPID(v *PID) *ADT_A13 {
	m.PID = v
	return m
}

func (m *ADT_A13) SetPV1(v *PV1) *ADT_A13 {
	m.PV1 = v
	return m
}

func (m *ADT_A13) SetDG1(v *DG1) *ADT_A13 {
	m.DG1 = v
	return m
}

// ADT_A14 - Pending Admit
type ADT_A14 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PD1 *PD1 `hl7:"PD1,required"`
	NK1 *NK1 `hl7:"NK1,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A14() *ADT_A14 {
	return &ADT_A14{
		MSH: NewMSH(NewID("ADT_A14")),
	}
}

func (m *ADT_A14) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A14.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A14.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A14.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.PID: %w", err)
		}
	}

	if m.PD1 == nil {
		return fmt.Errorf("ADT_A14.PD1 is required")
	}
	if m.PD1 != nil {
		if err := m.PD1.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.PD1: %w", err)
		}
	}

	if m.NK1 == nil {
		return fmt.Errorf("ADT_A14.NK1 is required")
	}
	if m.NK1 != nil {
		if err := m.NK1.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.NK1: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A14.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A14.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A14) SetMSH(v *MSH) *ADT_A14 {
	m.MSH = v
	return m
}

func (m *ADT_A14) SetEVN(v *EVN) *ADT_A14 {
	m.EVN = v
	return m
}

func (m *ADT_A14) SetPID(v *PID) *ADT_A14 {
	m.PID = v
	return m
}

func (m *ADT_A14) SetPD1(v *PD1) *ADT_A14 {
	m.PD1 = v
	return m
}

func (m *ADT_A14) SetNK1(v *NK1) *ADT_A14 {
	m.NK1 = v
	return m
}

func (m *ADT_A14) SetPV1(v *PV1) *ADT_A14 {
	m.PV1 = v
	return m
}

func (m *ADT_A14) SetDG1(v *DG1) *ADT_A14 {
	m.DG1 = v
	return m
}

// ADT_A15 - Pending Transfer
type ADT_A15 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A15() *ADT_A15 {
	return &ADT_A15{
		MSH: NewMSH(NewID("ADT_A15")),
	}
}

func (m *ADT_A15) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A15.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A15.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A15.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A15.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A15.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A15.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A15.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A15.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A15.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A15) SetMSH(v *MSH) *ADT_A15 {
	m.MSH = v
	return m
}

func (m *ADT_A15) SetEVN(v *EVN) *ADT_A15 {
	m.EVN = v
	return m
}

func (m *ADT_A15) SetPID(v *PID) *ADT_A15 {
	m.PID = v
	return m
}

func (m *ADT_A15) SetPV1(v *PV1) *ADT_A15 {
	m.PV1 = v
	return m
}

func (m *ADT_A15) SetDG1(v *DG1) *ADT_A15 {
	m.DG1 = v
	return m
}

// ADT_A16 - Pending Discharge
type ADT_A16 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
	DG1 *DG1 `hl7:"DG1"`
}

func NewADT_A16() *ADT_A16 {
	return &ADT_A16{
		MSH: NewMSH(NewID("ADT_A16")),
	}
}

func (m *ADT_A16) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A16.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A16.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A16.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A16.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A16.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A16.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A16.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A16.PV1: %w", err)
		}
	}

	if m.DG1 != nil {
		if err := m.DG1.Validate(); err != nil {
			return fmt.Errorf("ADT_A16.DG1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A16) SetMSH(v *MSH) *ADT_A16 {
	m.MSH = v
	return m
}

func (m *ADT_A16) SetEVN(v *EVN) *ADT_A16 {
	m.EVN = v
	return m
}

func (m *ADT_A16) SetPID(v *PID) *ADT_A16 {
	m.PID = v
	return m
}

func (m *ADT_A16) SetPV1(v *PV1) *ADT_A16 {
	m.PV1 = v
	return m
}

func (m *ADT_A16) SetDG1(v *DG1) *ADT_A16 {
	m.DG1 = v
	return m
}

type ADT_A17_PATIENT struct {
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A17_PATIENT() *ADT_A17_PATIENT {
	return &ADT_A17_PATIENT{}
}

func (m *ADT_A17_PATIENT) Validate() error {

	if m.PID == nil {
		return fmt.Errorf("ADT_A17_PATIENT.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A17_PATIENT.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A17_PATIENT.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A17_PATIENT.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A17_PATIENT) SetPID(v *PID) *ADT_A17_PATIENT {
	m.PID = v
	return m
}

func (m *ADT_A17_PATIENT) SetPV1(v *PV1) *ADT_A17_PATIENT {
	m.PV1 = v
	return m
}

// ADT_A17 - Swap Patients
type ADT_A17 struct {
	MSH     *MSH              `hl7:"MSH,required"`
	EVN     *EVN              `hl7:"EVN,required"`
	PATIENT []ADT_A17_PATIENT `hl7:"PATIENT,required"`
}

func NewADT_A17() *ADT_A17 {
	return &ADT_A17{
		MSH: NewMSH(NewID("ADT_A17")),
	}
}

func (m *ADT_A17) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A17.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A17.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A17.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A17.EVN: %w", err)
		}
	}

	if len(m.PATIENT) == 0 {
		return fmt.Errorf("ADT_A17.PATIENT is required")
	}
	for _, item := range m.PATIENT {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ADT_A17.PATIENT: %w", err)
		}
	}
	return nil
}

func (m *ADT_A17) SetMSH(v *MSH) *ADT_A17 {
	m.MSH = v
	return m
}

func (m *ADT_A17) SetEVN(v *EVN) *ADT_A17 {
	m.EVN = v
	return m
}

func (m *ADT_A17) AddPATIENT(v ADT_A17_PATIENT) *ADT_A17 {
	m.PATIENT = append(m.PATIENT, v)
	return m
}

// ADT_A18 - Merge Patient Information
type ADT_A18 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	MRG *MRG `hl7:"MRG,required"`
	PV1 *PV1 `hl7:"PV1"`
}

func NewADT_A18() *ADT_A18 {
	return &ADT_A18{
		MSH: NewMSH(NewID("ADT_A18")),
	}
}

func (m *ADT_A18) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A18.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A18.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A18.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A18.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A18.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A18.PID: %w", err)
		}
	}

	if m.MRG == nil {
		return fmt.Errorf("ADT_A18.MRG is required")
	}
	if m.MRG != nil {
		if err := m.MRG.Validate(); err != nil {
			return fmt.Errorf("ADT_A18.MRG: %w", err)
		}
	}

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A18.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A18) SetMSH(v *MSH) *ADT_A18 {
	m.MSH = v
	return m
}

func (m *ADT_A18) SetEVN(v *EVN) *ADT_A18 {
	m.EVN = v
	return m
}

func (m *ADT_A18) SetPID(v *PID) *ADT_A18 {
	m.PID = v
	return m
}

func (m *ADT_A18) SetMRG(v *MRG) *ADT_A18 {
	m.MRG = v
	return m
}

func (m *ADT_A18) SetPV1(v *PV1) *ADT_A18 {
	m.PV1 = v
	return m
}

// ADT_A20 - Nursing/Census Application Updates
type ADT_A20 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	NPU *NPU `hl7:"NPU,required"`
}

func NewADT_A20() *ADT_A20 {
	return &ADT_A20{
		MSH: NewMSH(NewID("ADT_A20")),
	}
}

func (m *ADT_A20) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A20.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A20.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A20.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A20.EVN: %w", err)
		}
	}

	if m.NPU == nil {
		return fmt.Errorf("ADT_A20.NPU is required")
	}
	if m.NPU != nil {
		if err := m.NPU.Validate(); err != nil {
			return fmt.Errorf("ADT_A20.NPU: %w", err)
		}
	}
	return nil
}

func (m *ADT_A20) SetMSH(v *MSH) *ADT_A20 {
	m.MSH = v
	return m
}

func (m *ADT_A20) SetEVN(v *EVN) *ADT_A20 {
	m.EVN = v
	return m
}

func (m *ADT_A20) SetNPU(v *NPU) *ADT_A20 {
	m.NPU = v
	return m
}

// ADT_A21 - A Patient Goes On A "Leave Of Absence"
type ADT_A21 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A21() *ADT_A21 {
	return &ADT_A21{
		MSH: NewMSH(NewID("ADT_A21")),
	}
}

func (m *ADT_A21) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A21.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A21.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A21.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A21.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A21.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A21.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A21.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A21.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A21) SetMSH(v *MSH) *ADT_A21 {
	m.MSH = v
	return m
}

func (m *ADT_A21) SetEVN(v *EVN) *ADT_A21 {
	m.EVN = v
	return m
}

func (m *ADT_A21) SetPID(v *PID) *ADT_A21 {
	m.PID = v
	return m
}

func (m *ADT_A21) SetPV1(v *PV1) *ADT_A21 {
	m.PV1 = v
	return m
}

// ADT_A22 - A Patient Returns From A "Leave Of Absence"
type ADT_A22 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A22() *ADT_A22 {
	return &ADT_A22{
		MSH: NewMSH(NewID("ADT_A22")),
	}
}

func (m *ADT_A22) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A22.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A22.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A22.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A22.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A22.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A22.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A22.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A22.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A22) SetMSH(v *MSH) *ADT_A22 {
	m.MSH = v
	return m
}

func (m *ADT_A22) SetEVN(v *EVN) *ADT_A22 {
	m.EVN = v
	return m
}

func (m *ADT_A22) SetPID(v *PID) *ADT_A22 {
	m.PID = v
	return m
}

func (m *ADT_A22) SetPV1(v *PV1) *ADT_A22 {
	m.PV1 = v
	return m
}

// ADT_A23 - Delete a Patient Record
type ADT_A23 struct {
	MSH *MSH `hl7:"MSH,required"`
	EVN *EVN `hl7:"EVN,required"`
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1,required"`
}

func NewADT_A23() *ADT_A23 {
	return &ADT_A23{
		MSH: NewMSH(NewID("ADT_A23")),
	}
}

func (m *ADT_A23) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A23.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A23.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A23.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A23.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A23.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A23.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A23.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A23.PV1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A23) SetMSH(v *MSH) *ADT_A23 {
	m.MSH = v
	return m
}

func (m *ADT_A23) SetEVN(v *EVN) *ADT_A23 {
	m.EVN = v
	return m
}

func (m *ADT_A23) SetPID(v *PID) *ADT_A23 {
	m.PID = v
	return m
}

func (m *ADT_A23) SetPV1(v *PV1) *ADT_A23 {
	m.PV1 = v
	return m
}

// ADT_A24 - Create a Patient Link Transaction
type ADT_A24 struct {
	MSH   *MSH `hl7:"MSH,required"`
	EVN   *EVN `hl7:"EVN,required"`
	PID   *PID `hl7:"PID,required"`
	PV1   *PV1 `hl7:"PV1,required"`
	PID_1 *PID `hl7:"PID,required"`
}

func NewADT_A24() *ADT_A24 {
	return &ADT_A24{
		MSH: NewMSH(NewID("ADT_A24")),
	}
}

func (m *ADT_A24) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ADT_A24.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ADT_A24.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("ADT_A24.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("ADT_A24.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("ADT_A24.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ADT_A24.PID: %w", err)
		}
	}

	if m.PV1 == nil {
		return fmt.Errorf("ADT_A24.PV1 is required")
	}
	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ADT_A24.PV1: %w", err)
		}
	}

	if m.PID_1 == nil {
		return fmt.Errorf("ADT_A24.PID_1 is required")
	}
	if m.PID_1 != nil {
		if err := m.PID_1.Validate(); err != nil {
			return fmt.Errorf("ADT_A24.PID_1: %w", err)
		}
	}
	return nil
}

func (m *ADT_A24) SetMSH(v *MSH) *ADT_A24 {
	m.MSH = v
	return m
}

func (m *ADT_A24) SetEVN(v *EVN) *ADT_A24 {
	m.EVN = v
	return m
}

func (m *ADT_A24) SetPID(v *PID) *ADT_A24 {
	m.PID = v
	return m
}

func (m *ADT_A24) SetPV1(v *PV1) *ADT_A24 {
	m.PV1 = v
	return m
}

func (m *ADT_A24) SetPID_1(v *PID) *ADT_A24 {
	m.PID_1 = v
	return m
}

type BAR_P01_VISIT struct {
	PV1 *PV1  `hl7:"PV1"`
	DG1 []DG1 `hl7:"DG1"`
	PR1 []PR1 `hl7:"PR1"`
	GT1 []GT1 `hl7:"GT1"`
	NK1 []NK1 `hl7:"NK1"`
	IN1 []IN1 `hl7:"IN1"`
	ACC *ACC  `hl7:"ACC"`
	UB1 *UB1  `hl7:"UB1"`
}

func NewBAR_P01_VISIT() *BAR_P01_VISIT {
	return &BAR_P01_VISIT{}
}

func (m *BAR_P01_VISIT) Validate() error {

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.PV1: %w", err)
		}
	}

	for _, item := range m.DG1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.DG1: %w", err)
		}
	}

	for _, item := range m.PR1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.PR1: %w", err)
		}
	}

	for _, item := range m.GT1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.GT1: %w", err)
		}
	}

	for _, item := range m.NK1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.NK1: %w", err)
		}
	}

	for _, item := range m.IN1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.IN1: %w", err)
		}
	}

	if m.ACC != nil {
		if err := m.ACC.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.ACC: %w", err)
		}
	}

	if m.UB1 != nil {
		if err := m.UB1.Validate(); err != nil {
			return fmt.Errorf("BAR_P01_VISIT.UB1: %w", err)
		}
	}
	return nil
}

func (m *BAR_P01_VISIT) SetPV1(v *PV1) *BAR_P01_VISIT {
	m.PV1 = v
	return m
}

func (m *BAR_P01_VISIT) AddDG1(v DG1) *BAR_P01_VISIT {
	m.DG1 = append(m.DG1, v)
	return m
}

func (m *BAR_P01_VISIT) AddPR1(v PR1) *BAR_P01_VISIT {
	m.PR1 = append(m.PR1, v)
	return m
}

func (m *BAR_P01_VISIT) AddGT1(v GT1) *BAR_P01_VISIT {
	m.GT1 = append(m.GT1, v)
	return m
}

func (m *BAR_P01_VISIT) AddNK1(v NK1) *BAR_P01_VISIT {
	m.NK1 = append(m.NK1, v)
	return m
}

func (m *BAR_P01_VISIT) AddIN1(v IN1) *BAR_P01_VISIT {
	m.IN1 = append(m.IN1, v)
	return m
}

func (m *BAR_P01_VISIT) SetACC(v *ACC) *BAR_P01_VISIT {
	m.ACC = v
	return m
}

func (m *BAR_P01_VISIT) SetUB1(v *UB1) *BAR_P01_VISIT {
	m.UB1 = v
	return m
}

// BAR_P01 - Add and Update Patient Accounts
type BAR_P01 struct {
	MSH   *MSH            `hl7:"MSH,required"`
	EVN   *EVN            `hl7:"EVN,required"`
	PID   *PID            `hl7:"PID,required"`
	VISIT []BAR_P01_VISIT `hl7:"VISIT,required"`
}

func NewBAR_P01() *BAR_P01 {
	return &BAR_P01{
		MSH: NewMSH(NewID("BAR_P01")),
	}
}

func (m *BAR_P01) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("BAR_P01.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("BAR_P01.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("BAR_P01.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("BAR_P01.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("BAR_P01.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("BAR_P01.PID: %w", err)
		}
	}

	if len(m.VISIT) == 0 {
		return fmt.Errorf("BAR_P01.VISIT is required")
	}
	for _, item := range m.VISIT {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P01.VISIT: %w", err)
		}
	}
	return nil
}

func (m *BAR_P01) SetMSH(v *MSH) *BAR_P01 {
	m.MSH = v
	return m
}

func (m *BAR_P01) SetEVN(v *EVN) *BAR_P01 {
	m.EVN = v
	return m
}

func (m *BAR_P01) SetPID(v *PID) *BAR_P01 {
	m.PID = v
	return m
}

func (m *BAR_P01) AddVISIT(v BAR_P01_VISIT) *BAR_P01 {
	m.VISIT = append(m.VISIT, v)
	return m
}

type BAR_P02_PATIENT struct {
	PID *PID `hl7:"PID,required"`
	PV1 *PV1 `hl7:"PV1"`
}

func NewBAR_P02_PATIENT() *BAR_P02_PATIENT {
	return &BAR_P02_PATIENT{}
}

func (m *BAR_P02_PATIENT) Validate() error {

	if m.PID == nil {
		return fmt.Errorf("BAR_P02_PATIENT.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("BAR_P02_PATIENT.PID: %w", err)
		}
	}

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("BAR_P02_PATIENT.PV1: %w", err)
		}
	}
	return nil
}

func (m *BAR_P02_PATIENT) SetPID(v *PID) *BAR_P02_PATIENT {
	m.PID = v
	return m
}

func (m *BAR_P02_PATIENT) SetPV1(v *PV1) *BAR_P02_PATIENT {
	m.PV1 = v
	return m
}

// BAR_P02 - Purge Patient Accounts
type BAR_P02 struct {
	MSH     *MSH              `hl7:"MSH,required"`
	EVN     *EVN              `hl7:"EVN,required"`
	PATIENT []BAR_P02_PATIENT `hl7:"PATIENT,required"`
}

func NewBAR_P02() *BAR_P02 {
	return &BAR_P02{
		MSH: NewMSH(NewID("BAR_P02")),
	}
}

func (m *BAR_P02) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("BAR_P02.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("BAR_P02.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("BAR_P02.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("BAR_P02.EVN: %w", err)
		}
	}

	if len(m.PATIENT) == 0 {
		return fmt.Errorf("BAR_P02.PATIENT is required")
	}
	for _, item := range m.PATIENT {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("BAR_P02.PATIENT: %w", err)
		}
	}
	return nil
}

func (m *BAR_P02) SetMSH(v *MSH) *BAR_P02 {
	m.MSH = v
	return m
}

func (m *BAR_P02) SetEVN(v *EVN) *BAR_P02 {
	m.EVN = v
	return m
}

func (m *BAR_P02) AddPATIENT(v BAR_P02_PATIENT) *BAR_P02 {
	m.PATIENT = append(m.PATIENT, v)
	return m
}

// DFT_P03 - Post Detail Financial Transactions
type DFT_P03 struct {
	MSH *MSH  `hl7:"MSH,required"`
	EVN *EVN  `hl7:"EVN,required"`
	PID *PID  `hl7:"PID,required"`
	PV1 *PV1  `hl7:"PV1"`
	FT1 []FT1 `hl7:"FT1"`
}

func NewDFT_P03() *DFT_P03 {
	return &DFT_P03{
		MSH: NewMSH(NewID("DFT_P03")),
	}
}

func (m *DFT_P03) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("DFT_P03.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("DFT_P03.MSH: %w", err)
		}
	}

	if m.EVN == nil {
		return fmt.Errorf("DFT_P03.EVN is required")
	}
	if m.EVN != nil {
		if err := m.EVN.Validate(); err != nil {
			return fmt.Errorf("DFT_P03.EVN: %w", err)
		}
	}

	if m.PID == nil {
		return fmt.Errorf("DFT_P03.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("DFT_P03.PID: %w", err)
		}
	}

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("DFT_P03.PV1: %w", err)
		}
	}

	for _, item := range m.FT1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("DFT_P03.FT1: %w", err)
		}
	}
	return nil
}

func (m *DFT_P03) SetMSH(v *MSH) *DFT_P03 {
	m.MSH = v
	return m
}

func (m *DFT_P03) SetEVN(v *EVN) *DFT_P03 {
	m.EVN = v
	return m
}

func (m *DFT_P03) SetPID(v *PID) *DFT_P03 {
	m.PID = v
	return m
}

func (m *DFT_P03) SetPV1(v *PV1) *DFT_P03 {
	m.PV1 = v
	return m
}

func (m *DFT_P03) AddFT1(v FT1) *DFT_P03 {
	m.FT1 = append(m.FT1, v)
	return m
}

// DSR_Q03 - Deferred Response to A Query
type DSR_Q03 struct {
	MSH *MSH  `hl7:"MSH,required"`
	QRD *QRD  `hl7:"QRD,required"`
	QRF *QRF  `hl7:"QRF"`
	DSP []DSP `hl7:"DSP,required"`
	DSC *DSC  `hl7:"DSC,required"`
}

func NewDSR_Q03() *DSR_Q03 {
	return &DSR_Q03{
		MSH: NewMSH(NewID("DSR_Q03")),
	}
}

func (m *DSR_Q03) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("DSR_Q03.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("DSR_Q03.MSH: %w", err)
		}
	}

	if m.QRD == nil {
		return fmt.Errorf("DSR_Q03.QRD is required")
	}
	if m.QRD != nil {
		if err := m.QRD.Validate(); err != nil {
			return fmt.Errorf("DSR_Q03.QRD: %w", err)
		}
	}

	if m.QRF != nil {
		if err := m.QRF.Validate(); err != nil {
			return fmt.Errorf("DSR_Q03.QRF: %w", err)
		}
	}

	if len(m.DSP) == 0 {
		return fmt.Errorf("DSR_Q03.DSP is required")
	}
	for _, item := range m.DSP {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("DSR_Q03.DSP: %w", err)
		}
	}

	if m.DSC == nil {
		return fmt.Errorf("DSR_Q03.DSC is required")
	}
	if m.DSC != nil {
		if err := m.DSC.Validate(); err != nil {
			return fmt.Errorf("DSR_Q03.DSC: %w", err)
		}
	}
	return nil
}

func (m *DSR_Q03) SetMSH(v *MSH) *DSR_Q03 {
	m.MSH = v
	return m
}

func (m *DSR_Q03) SetQRD(v *QRD) *DSR_Q03 {
	m.QRD = v
	return m
}

func (m *DSR_Q03) SetQRF(v *QRF) *DSR_Q03 {
	m.QRF = v
	return m
}

func (m *DSR_Q03) AddDSP(v DSP) *DSR_Q03 {
	m.DSP = append(m.DSP, v)
	return m
}

func (m *DSR_Q03) SetDSC(v *DSC) *DSR_Q03 {
	m.DSC = v
	return m
}

type ORM_O01_ORDERDETAIL struct {
	OBR   *OBR  `hl7:"OBR,required"`
	NTE   []NTE `hl7:"NTE"`
	OBX   []OBX `hl7:"OBX"`
	NTE_1 []NTE `hl7:"NTE"`
	BLG   *BLG  `hl7:"BLG"`
}

func NewORM_O01_ORDERDETAIL() *ORM_O01_ORDERDETAIL {
	return &ORM_O01_ORDERDETAIL{}
}

func (m *ORM_O01_ORDERDETAIL) Validate() error {

	if m.OBR == nil {
		return fmt.Errorf("ORM_O01_ORDERDETAIL.OBR is required")
	}
	if m.OBR != nil {
		if err := m.OBR.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDERDETAIL.OBR: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDERDETAIL.NTE: %w", err)
		}
	}

	for _, item := range m.OBX {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDERDETAIL.OBX: %w", err)
		}
	}

	for _, item := range m.NTE_1 {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDERDETAIL.NTE_1: %w", err)
		}
	}

	if m.BLG != nil {
		if err := m.BLG.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDERDETAIL.BLG: %w", err)
		}
	}
	return nil
}

func (m *ORM_O01_ORDERDETAIL) SetOBR(v *OBR) *ORM_O01_ORDERDETAIL {
	m.OBR = v
	return m
}

func (m *ORM_O01_ORDERDETAIL) AddNTE(v NTE) *ORM_O01_ORDERDETAIL {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORM_O01_ORDERDETAIL) AddOBX(v OBX) *ORM_O01_ORDERDETAIL {
	m.OBX = append(m.OBX, v)
	return m
}

func (m *ORM_O01_ORDERDETAIL) AddNTE_1(v NTE) *ORM_O01_ORDERDETAIL {
	m.NTE_1 = append(m.NTE_1, v)
	return m
}

func (m *ORM_O01_ORDERDETAIL) SetBLG(v *BLG) *ORM_O01_ORDERDETAIL {
	m.BLG = v
	return m
}

type ORM_O01_ORDER struct {
	ORC         *ORC                 `hl7:"ORC,required"`
	ORDERDETAIL *ORM_O01_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

func NewORM_O01_ORDER() *ORM_O01_ORDER {
	return &ORM_O01_ORDER{}
}

func (m *ORM_O01_ORDER) Validate() error {

	if m.ORC == nil {
		return fmt.Errorf("ORM_O01_ORDER.ORC is required")
	}
	if m.ORC != nil {
		if err := m.ORC.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDER.ORC: %w", err)
		}
	}

	if m.ORDERDETAIL != nil {
		if err := m.ORDERDETAIL.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_ORDER.ORDERDETAIL: %w", err)
		}
	}
	return nil
}

func (m *ORM_O01_ORDER) SetORC(v *ORC) *ORM_O01_ORDER {
	m.ORC = v
	return m
}

func (m *ORM_O01_ORDER) SetORDERDETAIL(v *ORM_O01_ORDERDETAIL) *ORM_O01_ORDER {
	m.ORDERDETAIL = v
	return m
}

type ORM_O01_PATIENT struct {
	PID   *PID            `hl7:"PID,required"`
	NTE   []NTE           `hl7:"NTE"`
	PV1   *PV1            `hl7:"PV1"`
	ORDER []ORM_O01_ORDER `hl7:"ORDER,required"`
}

func NewORM_O01_PATIENT() *ORM_O01_PATIENT {
	return &ORM_O01_PATIENT{}
}

func (m *ORM_O01_PATIENT) Validate() error {

	if m.PID == nil {
		return fmt.Errorf("ORM_O01_PATIENT.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_PATIENT.PID: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_PATIENT.NTE: %w", err)
		}
	}

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_PATIENT.PV1: %w", err)
		}
	}

	if len(m.ORDER) == 0 {
		return fmt.Errorf("ORM_O01_PATIENT.ORDER is required")
	}
	for _, item := range m.ORDER {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORM_O01_PATIENT.ORDER: %w", err)
		}
	}
	return nil
}

func (m *ORM_O01_PATIENT) SetPID(v *PID) *ORM_O01_PATIENT {
	m.PID = v
	return m
}

func (m *ORM_O01_PATIENT) AddNTE(v NTE) *ORM_O01_PATIENT {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORM_O01_PATIENT) SetPV1(v *PV1) *ORM_O01_PATIENT {
	m.PV1 = v
	return m
}

func (m *ORM_O01_PATIENT) AddORDER(v ORM_O01_ORDER) *ORM_O01_PATIENT {
	m.ORDER = append(m.ORDER, v)
	return m
}

// ORM_O01 - Order Message
type ORM_O01 struct {
	MSH     *MSH             `hl7:"MSH,required"`
	NTE     []NTE            `hl7:"NTE"`
	PATIENT *ORM_O01_PATIENT `hl7:"PATIENT"`
}

func NewORM_O01() *ORM_O01 {
	return &ORM_O01{
		MSH: NewMSH(NewID("ORM_O01")),
	}
}

func (m *ORM_O01) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ORM_O01.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ORM_O01.MSH: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORM_O01.NTE: %w", err)
		}
	}

	if m.PATIENT != nil {
		if err := m.PATIENT.Validate(); err != nil {
			return fmt.Errorf("ORM_O01.PATIENT: %w", err)
		}
	}
	return nil
}

func (m *ORM_O01) SetMSH(v *MSH) *ORM_O01 {
	m.MSH = v
	return m
}

func (m *ORM_O01) AddNTE(v NTE) *ORM_O01 {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORM_O01) SetPATIENT(v *ORM_O01_PATIENT) *ORM_O01 {
	m.PATIENT = v
	return m
}

type ORR_O02_ORDERDETAIL struct {
	OBR *OBR  `hl7:"OBR,required"`
	NTE []NTE `hl7:"NTE"`
}

func NewORR_O02_ORDERDETAIL() *ORR_O02_ORDERDETAIL {
	return &ORR_O02_ORDERDETAIL{}
}

func (m *ORR_O02_ORDERDETAIL) Validate() error {

	if m.OBR == nil {
		return fmt.Errorf("ORR_O02_ORDERDETAIL.OBR is required")
	}
	if m.OBR != nil {
		if err := m.OBR.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_ORDERDETAIL.OBR: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_ORDERDETAIL.NTE: %w", err)
		}
	}
	return nil
}

func (m *ORR_O02_ORDERDETAIL) SetOBR(v *OBR) *ORR_O02_ORDERDETAIL {
	m.OBR = v
	return m
}

func (m *ORR_O02_ORDERDETAIL) AddNTE(v NTE) *ORR_O02_ORDERDETAIL {
	m.NTE = append(m.NTE, v)
	return m
}

type ORR_O02_ORDER struct {
	ORC         *ORC                 `hl7:"ORC,required"`
	ORDERDETAIL *ORR_O02_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

func NewORR_O02_ORDER() *ORR_O02_ORDER {
	return &ORR_O02_ORDER{}
}

func (m *ORR_O02_ORDER) Validate() error {

	if m.ORC == nil {
		return fmt.Errorf("ORR_O02_ORDER.ORC is required")
	}
	if m.ORC != nil {
		if err := m.ORC.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_ORDER.ORC: %w", err)
		}
	}

	if m.ORDERDETAIL != nil {
		if err := m.ORDERDETAIL.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_ORDER.ORDERDETAIL: %w", err)
		}
	}
	return nil
}

func (m *ORR_O02_ORDER) SetORC(v *ORC) *ORR_O02_ORDER {
	m.ORC = v
	return m
}

func (m *ORR_O02_ORDER) SetORDERDETAIL(v *ORR_O02_ORDERDETAIL) *ORR_O02_ORDER {
	m.ORDERDETAIL = v
	return m
}

type ORR_O02_PATIENT struct {
	PID   *PID            `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []ORR_O02_ORDER `hl7:"ORDER,required"`
}

func NewORR_O02_PATIENT() *ORR_O02_PATIENT {
	return &ORR_O02_PATIENT{}
}

func (m *ORR_O02_PATIENT) Validate() error {

	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_PATIENT.PID: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_PATIENT.NTE: %w", err)
		}
	}

	if len(m.ORDER) == 0 {
		return fmt.Errorf("ORR_O02_PATIENT.ORDER is required")
	}
	for _, item := range m.ORDER {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORR_O02_PATIENT.ORDER: %w", err)
		}
	}
	return nil
}

func (m *ORR_O02_PATIENT) SetPID(v *PID) *ORR_O02_PATIENT {
	m.PID = v
	return m
}

func (m *ORR_O02_PATIENT) AddNTE(v NTE) *ORR_O02_PATIENT {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORR_O02_PATIENT) AddORDER(v ORR_O02_ORDER) *ORR_O02_PATIENT {
	m.ORDER = append(m.ORDER, v)
	return m
}

// ORR_O02 - Respone Message
type ORR_O02 struct {
	MSH     *MSH             `hl7:"MSH,required"`
	MSA     *MSA             `hl7:"MSA,required"`
	NTE     []NTE            `hl7:"NTE"`
	PATIENT *ORR_O02_PATIENT `hl7:"PATIENT"`
}

func NewORR_O02() *ORR_O02 {
	return &ORR_O02{
		MSH: NewMSH(NewID("ORR_O02")),
	}
}

func (m *ORR_O02) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ORR_O02.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ORR_O02.MSH: %w", err)
		}
	}

	if m.MSA == nil {
		return fmt.Errorf("ORR_O02.MSA is required")
	}
	if m.MSA != nil {
		if err := m.MSA.Validate(); err != nil {
			return fmt.Errorf("ORR_O02.MSA: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORR_O02.NTE: %w", err)
		}
	}

	if m.PATIENT != nil {
		if err := m.PATIENT.Validate(); err != nil {
			return fmt.Errorf("ORR_O02.PATIENT: %w", err)
		}
	}
	return nil
}

func (m *ORR_O02) SetMSH(v *MSH) *ORR_O02 {
	m.MSH = v
	return m
}

func (m *ORR_O02) SetMSA(v *MSA) *ORR_O02 {
	m.MSA = v
	return m
}

func (m *ORR_O02) AddNTE(v NTE) *ORR_O02 {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORR_O02) SetPATIENT(v *ORR_O02_PATIENT) *ORR_O02 {
	m.PATIENT = v
	return m
}

type ORU_R01_OBSERVATION struct {
	OBX *OBX  `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
	DSC *DSC  `hl7:"DSC"`
}

func NewORU_R01_OBSERVATION() *ORU_R01_OBSERVATION {
	return &ORU_R01_OBSERVATION{}
}

func (m *ORU_R01_OBSERVATION) Validate() error {

	if m.OBX != nil {
		if err := m.OBX.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_OBSERVATION.OBX: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_OBSERVATION.NTE: %w", err)
		}
	}

	if m.DSC != nil {
		if err := m.DSC.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_OBSERVATION.DSC: %w", err)
		}
	}
	return nil
}

func (m *ORU_R01_OBSERVATION) SetOBX(v *OBX) *ORU_R01_OBSERVATION {
	m.OBX = v
	return m
}

func (m *ORU_R01_OBSERVATION) AddNTE(v NTE) *ORU_R01_OBSERVATION {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORU_R01_OBSERVATION) SetDSC(v *DSC) *ORU_R01_OBSERVATION {
	m.DSC = v
	return m
}

type ORU_R01_ORDEROBSERVATION struct {
	ORC         *ORC                  `hl7:"ORC"`
	OBR         *OBR                  `hl7:"OBR,required"`
	NTE         []NTE                 `hl7:"NTE"`
	OBSERVATION []ORU_R01_OBSERVATION `hl7:"OBSERVATION,required"`
}

func NewORU_R01_ORDEROBSERVATION() *ORU_R01_ORDEROBSERVATION {
	return &ORU_R01_ORDEROBSERVATION{}
}

func (m *ORU_R01_ORDEROBSERVATION) Validate() error {

	if m.ORC != nil {
		if err := m.ORC.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_ORDEROBSERVATION.ORC: %w", err)
		}
	}

	if m.OBR == nil {
		return fmt.Errorf("ORU_R01_ORDEROBSERVATION.OBR is required")
	}
	if m.OBR != nil {
		if err := m.OBR.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_ORDEROBSERVATION.OBR: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_ORDEROBSERVATION.NTE: %w", err)
		}
	}

	if len(m.OBSERVATION) == 0 {
		return fmt.Errorf("ORU_R01_ORDEROBSERVATION.OBSERVATION is required")
	}
	for _, item := range m.OBSERVATION {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_ORDEROBSERVATION.OBSERVATION: %w", err)
		}
	}
	return nil
}

func (m *ORU_R01_ORDEROBSERVATION) SetORC(v *ORC) *ORU_R01_ORDEROBSERVATION {
	m.ORC = v
	return m
}

func (m *ORU_R01_ORDEROBSERVATION) SetOBR(v *OBR) *ORU_R01_ORDEROBSERVATION {
	m.OBR = v
	return m
}

func (m *ORU_R01_ORDEROBSERVATION) AddNTE(v NTE) *ORU_R01_ORDEROBSERVATION {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORU_R01_ORDEROBSERVATION) AddOBSERVATION(v ORU_R01_OBSERVATION) *ORU_R01_ORDEROBSERVATION {
	m.OBSERVATION = append(m.OBSERVATION, v)
	return m
}

type ORU_R01_PATIENT struct {
	PID              *PID                       `hl7:"PID,required"`
	NTE              []NTE                      `hl7:"NTE"`
	PV1              *PV1                       `hl7:"PV1"`
	ORDEROBSERVATION []ORU_R01_ORDEROBSERVATION `hl7:"ORDER_OBSERVATION,required"`
}

func NewORU_R01_PATIENT() *ORU_R01_PATIENT {
	return &ORU_R01_PATIENT{}
}

func (m *ORU_R01_PATIENT) Validate() error {

	if m.PID == nil {
		return fmt.Errorf("ORU_R01_PATIENT.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_PATIENT.PID: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_PATIENT.NTE: %w", err)
		}
	}

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_PATIENT.PV1: %w", err)
		}
	}

	if len(m.ORDEROBSERVATION) == 0 {
		return fmt.Errorf("ORU_R01_PATIENT.ORDEROBSERVATION is required")
	}
	for _, item := range m.ORDEROBSERVATION {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_PATIENT.ORDEROBSERVATION: %w", err)
		}
	}
	return nil
}

func (m *ORU_R01_PATIENT) SetPID(v *PID) *ORU_R01_PATIENT {
	m.PID = v
	return m
}

func (m *ORU_R01_PATIENT) AddNTE(v NTE) *ORU_R01_PATIENT {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORU_R01_PATIENT) SetPV1(v *PV1) *ORU_R01_PATIENT {
	m.PV1 = v
	return m
}

func (m *ORU_R01_PATIENT) AddORDEROBSERVATION(v ORU_R01_ORDEROBSERVATION) *ORU_R01_PATIENT {
	m.ORDEROBSERVATION = append(m.ORDEROBSERVATION, v)
	return m
}

type ORU_R01_PATIENTRESULT struct {
	PATIENT *ORU_R01_PATIENT `hl7:"PATIENT"`
}

func NewORU_R01_PATIENTRESULT() *ORU_R01_PATIENTRESULT {
	return &ORU_R01_PATIENTRESULT{}
}

func (m *ORU_R01_PATIENTRESULT) Validate() error {

	if m.PATIENT != nil {
		if err := m.PATIENT.Validate(); err != nil {
			return fmt.Errorf("ORU_R01_PATIENTRESULT.PATIENT: %w", err)
		}
	}
	return nil
}

func (m *ORU_R01_PATIENTRESULT) SetPATIENT(v *ORU_R01_PATIENT) *ORU_R01_PATIENTRESULT {
	m.PATIENT = v
	return m
}

// ORU_R01 - Unsolicited transmission of requested Obersvation
type ORU_R01 struct {
	MSH           *MSH                    `hl7:"MSH,required"`
	PATIENTRESULT []ORU_R01_PATIENTRESULT `hl7:"PATIENT_RESULT,required"`
}

func NewORU_R01() *ORU_R01 {
	return &ORU_R01{
		MSH: NewMSH(NewID("ORU_R01")),
	}
}

func (m *ORU_R01) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ORU_R01.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ORU_R01.MSH: %w", err)
		}
	}

	if len(m.PATIENTRESULT) == 0 {
		return fmt.Errorf("ORU_R01.PATIENTRESULT is required")
	}
	for _, item := range m.PATIENTRESULT {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R01.PATIENTRESULT: %w", err)
		}
	}
	return nil
}

func (m *ORU_R01) SetMSH(v *MSH) *ORU_R01 {
	m.MSH = v
	return m
}

func (m *ORU_R01) AddPATIENTRESULT(v ORU_R01_PATIENTRESULT) *ORU_R01 {
	m.PATIENTRESULT = append(m.PATIENTRESULT, v)
	return m
}

type ORU_R03_OBSERVATION struct {
	OBX *OBX  `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
	DSC *DSC  `hl7:"DSC"`
}

func NewORU_R03_OBSERVATION() *ORU_R03_OBSERVATION {
	return &ORU_R03_OBSERVATION{}
}

func (m *ORU_R03_OBSERVATION) Validate() error {

	if m.OBX != nil {
		if err := m.OBX.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_OBSERVATION.OBX: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_OBSERVATION.NTE: %w", err)
		}
	}

	if m.DSC != nil {
		if err := m.DSC.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_OBSERVATION.DSC: %w", err)
		}
	}
	return nil
}

func (m *ORU_R03_OBSERVATION) SetOBX(v *OBX) *ORU_R03_OBSERVATION {
	m.OBX = v
	return m
}

func (m *ORU_R03_OBSERVATION) AddNTE(v NTE) *ORU_R03_OBSERVATION {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORU_R03_OBSERVATION) SetDSC(v *DSC) *ORU_R03_OBSERVATION {
	m.DSC = v
	return m
}

type ORU_R03_ORDEROBSERVATION struct {
	ORC         *ORC                  `hl7:"ORC"`
	OBR         *OBR                  `hl7:"OBR,required"`
	NTE         []NTE                 `hl7:"NTE"`
	OBSERVATION []ORU_R03_OBSERVATION `hl7:"OBSERVATION,required"`
}

func NewORU_R03_ORDEROBSERVATION() *ORU_R03_ORDEROBSERVATION {
	return &ORU_R03_ORDEROBSERVATION{}
}

func (m *ORU_R03_ORDEROBSERVATION) Validate() error {

	if m.ORC != nil {
		if err := m.ORC.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_ORDEROBSERVATION.ORC: %w", err)
		}
	}

	if m.OBR == nil {
		return fmt.Errorf("ORU_R03_ORDEROBSERVATION.OBR is required")
	}
	if m.OBR != nil {
		if err := m.OBR.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_ORDEROBSERVATION.OBR: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_ORDEROBSERVATION.NTE: %w", err)
		}
	}

	if len(m.OBSERVATION) == 0 {
		return fmt.Errorf("ORU_R03_ORDEROBSERVATION.OBSERVATION is required")
	}
	for _, item := range m.OBSERVATION {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_ORDEROBSERVATION.OBSERVATION: %w", err)
		}
	}
	return nil
}

func (m *ORU_R03_ORDEROBSERVATION) SetORC(v *ORC) *ORU_R03_ORDEROBSERVATION {
	m.ORC = v
	return m
}

func (m *ORU_R03_ORDEROBSERVATION) SetOBR(v *OBR) *ORU_R03_ORDEROBSERVATION {
	m.OBR = v
	return m
}

func (m *ORU_R03_ORDEROBSERVATION) AddNTE(v NTE) *ORU_R03_ORDEROBSERVATION {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORU_R03_ORDEROBSERVATION) AddOBSERVATION(v ORU_R03_OBSERVATION) *ORU_R03_ORDEROBSERVATION {
	m.OBSERVATION = append(m.OBSERVATION, v)
	return m
}

type ORU_R03_PATIENT struct {
	PID              *PID                       `hl7:"PID,required"`
	NTE              []NTE                      `hl7:"NTE"`
	PV1              *PV1                       `hl7:"PV1"`
	ORDEROBSERVATION []ORU_R03_ORDEROBSERVATION `hl7:"ORDER_OBSERVATION,required"`
}

func NewORU_R03_PATIENT() *ORU_R03_PATIENT {
	return &ORU_R03_PATIENT{}
}

func (m *ORU_R03_PATIENT) Validate() error {

	if m.PID == nil {
		return fmt.Errorf("ORU_R03_PATIENT.PID is required")
	}
	if m.PID != nil {
		if err := m.PID.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_PATIENT.PID: %w", err)
		}
	}

	for _, item := range m.NTE {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_PATIENT.NTE: %w", err)
		}
	}

	if m.PV1 != nil {
		if err := m.PV1.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_PATIENT.PV1: %w", err)
		}
	}

	if len(m.ORDEROBSERVATION) == 0 {
		return fmt.Errorf("ORU_R03_PATIENT.ORDEROBSERVATION is required")
	}
	for _, item := range m.ORDEROBSERVATION {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_PATIENT.ORDEROBSERVATION: %w", err)
		}
	}
	return nil
}

func (m *ORU_R03_PATIENT) SetPID(v *PID) *ORU_R03_PATIENT {
	m.PID = v
	return m
}

func (m *ORU_R03_PATIENT) AddNTE(v NTE) *ORU_R03_PATIENT {
	m.NTE = append(m.NTE, v)
	return m
}

func (m *ORU_R03_PATIENT) SetPV1(v *PV1) *ORU_R03_PATIENT {
	m.PV1 = v
	return m
}

func (m *ORU_R03_PATIENT) AddORDEROBSERVATION(v ORU_R03_ORDEROBSERVATION) *ORU_R03_PATIENT {
	m.ORDEROBSERVATION = append(m.ORDEROBSERVATION, v)
	return m
}

type ORU_R03_PATIENTRESULT struct {
	PATIENT *ORU_R03_PATIENT `hl7:"PATIENT"`
}

func NewORU_R03_PATIENTRESULT() *ORU_R03_PATIENTRESULT {
	return &ORU_R03_PATIENTRESULT{}
}

func (m *ORU_R03_PATIENTRESULT) Validate() error {

	if m.PATIENT != nil {
		if err := m.PATIENT.Validate(); err != nil {
			return fmt.Errorf("ORU_R03_PATIENTRESULT.PATIENT: %w", err)
		}
	}
	return nil
}

func (m *ORU_R03_PATIENTRESULT) SetPATIENT(v *ORU_R03_PATIENT) *ORU_R03_PATIENTRESULT {
	m.PATIENT = v
	return m
}

// ORU_R03 - Display oriented results, queyr/unsol. update
type ORU_R03 struct {
	MSH           *MSH                    `hl7:"MSH,required"`
	PATIENTRESULT []ORU_R03_PATIENTRESULT `hl7:"PATIENT_RESULT,required"`
}

func NewORU_R03() *ORU_R03 {
	return &ORU_R03{
		MSH: NewMSH(NewID("ORU_R03")),
	}
}

func (m *ORU_R03) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("ORU_R03.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("ORU_R03.MSH: %w", err)
		}
	}

	if len(m.PATIENTRESULT) == 0 {
		return fmt.Errorf("ORU_R03.PATIENTRESULT is required")
	}
	for _, item := range m.PATIENTRESULT {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("ORU_R03.PATIENTRESULT: %w", err)
		}
	}
	return nil
}

func (m *ORU_R03) SetMSH(v *MSH) *ORU_R03 {
	m.MSH = v
	return m
}

func (m *ORU_R03) AddPATIENTRESULT(v ORU_R03_PATIENTRESULT) *ORU_R03 {
	m.PATIENTRESULT = append(m.PATIENTRESULT, v)
	return m
}

// QRY_A19 - Patient Query
type QRY_A19 struct {
	MSH *MSH `hl7:"MSH,required"`
	QRD *QRD `hl7:"QRD,required"`
}

func NewQRY_A19() *QRY_A19 {
	return &QRY_A19{
		MSH: NewMSH(NewID("QRY_A19")),
	}
}

func (m *QRY_A19) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("QRY_A19.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("QRY_A19.MSH: %w", err)
		}
	}

	if m.QRD == nil {
		return fmt.Errorf("QRY_A19.QRD is required")
	}
	if m.QRD != nil {
		if err := m.QRD.Validate(); err != nil {
			return fmt.Errorf("QRY_A19.QRD: %w", err)
		}
	}
	return nil
}

func (m *QRY_A19) SetMSH(v *MSH) *QRY_A19 {
	m.MSH = v
	return m
}

func (m *QRY_A19) SetQRD(v *QRD) *QRY_A19 {
	m.QRD = v
	return m
}

// QRY_Q01 - A Query is Made for Immediate Response
type QRY_Q01 struct {
	MSH *MSH `hl7:"MSH,required"`
	QRD *QRD `hl7:"QRD,required"`
	QRF *QRF `hl7:"QRF"`
	DSC *DSC `hl7:"DSC,required"`
}

func NewQRY_Q01() *QRY_Q01 {
	return &QRY_Q01{
		MSH: NewMSH(NewID("QRY_Q01")),
	}
}

func (m *QRY_Q01) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("QRY_Q01.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("QRY_Q01.MSH: %w", err)
		}
	}

	if m.QRD == nil {
		return fmt.Errorf("QRY_Q01.QRD is required")
	}
	if m.QRD != nil {
		if err := m.QRD.Validate(); err != nil {
			return fmt.Errorf("QRY_Q01.QRD: %w", err)
		}
	}

	if m.QRF != nil {
		if err := m.QRF.Validate(); err != nil {
			return fmt.Errorf("QRY_Q01.QRF: %w", err)
		}
	}

	if m.DSC == nil {
		return fmt.Errorf("QRY_Q01.DSC is required")
	}
	if m.DSC != nil {
		if err := m.DSC.Validate(); err != nil {
			return fmt.Errorf("QRY_Q01.DSC: %w", err)
		}
	}
	return nil
}

func (m *QRY_Q01) SetMSH(v *MSH) *QRY_Q01 {
	m.MSH = v
	return m
}

func (m *QRY_Q01) SetQRD(v *QRD) *QRY_Q01 {
	m.QRD = v
	return m
}

func (m *QRY_Q01) SetQRF(v *QRF) *QRY_Q01 {
	m.QRF = v
	return m
}

func (m *QRY_Q01) SetDSC(v *DSC) *QRY_Q01 {
	m.DSC = v
	return m
}

// QRY_Q02 - A Query is Sent for Deferred Response
type QRY_Q02 struct {
	MSH *MSH `hl7:"MSH,required"`
	QRD *QRD `hl7:"QRD,required"`
	QRF *QRF `hl7:"QRF"`
	DSC *DSC `hl7:"DSC,required"`
}

func NewQRY_Q02() *QRY_Q02 {
	return &QRY_Q02{
		MSH: NewMSH(NewID("QRY_Q02")),
	}
}

func (m *QRY_Q02) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("QRY_Q02.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("QRY_Q02.MSH: %w", err)
		}
	}

	if m.QRD == nil {
		return fmt.Errorf("QRY_Q02.QRD is required")
	}
	if m.QRD != nil {
		if err := m.QRD.Validate(); err != nil {
			return fmt.Errorf("QRY_Q02.QRD: %w", err)
		}
	}

	if m.QRF != nil {
		if err := m.QRF.Validate(); err != nil {
			return fmt.Errorf("QRY_Q02.QRF: %w", err)
		}
	}

	if m.DSC == nil {
		return fmt.Errorf("QRY_Q02.DSC is required")
	}
	if m.DSC != nil {
		if err := m.DSC.Validate(); err != nil {
			return fmt.Errorf("QRY_Q02.DSC: %w", err)
		}
	}
	return nil
}

func (m *QRY_Q02) SetMSH(v *MSH) *QRY_Q02 {
	m.MSH = v
	return m
}

func (m *QRY_Q02) SetQRD(v *QRD) *QRY_Q02 {
	m.QRD = v
	return m
}

func (m *QRY_Q02) SetQRF(v *QRF) *QRY_Q02 {
	m.QRF = v
	return m
}

func (m *QRY_Q02) SetDSC(v *DSC) *QRY_Q02 {
	m.DSC = v
	return m
}

// UDM_Q05 - Unsolicited Updates, ODM Message, Trigger Event Q05
type UDM_Q05 struct {
	MSH *MSH  `hl7:"MSH,required"`
	URD *URD  `hl7:"URD,required"`
	URS *URS  `hl7:"URS"`
	DSP []DSP `hl7:"DSP,required"`
	DSC *DSC  `hl7:"DSC,required"`
}

func NewUDM_Q05() *UDM_Q05 {
	return &UDM_Q05{
		MSH: NewMSH(NewID("UDM_Q05")),
	}
}

func (m *UDM_Q05) Validate() error {

	if m.MSH == nil {
		return fmt.Errorf("UDM_Q05.MSH is required")
	}
	if m.MSH != nil {
		if err := m.MSH.Validate(); err != nil {
			return fmt.Errorf("UDM_Q05.MSH: %w", err)
		}
	}

	if m.URD == nil {
		return fmt.Errorf("UDM_Q05.URD is required")
	}
	if m.URD != nil {
		if err := m.URD.Validate(); err != nil {
			return fmt.Errorf("UDM_Q05.URD: %w", err)
		}
	}

	if m.URS != nil {
		if err := m.URS.Validate(); err != nil {
			return fmt.Errorf("UDM_Q05.URS: %w", err)
		}
	}

	if len(m.DSP) == 0 {
		return fmt.Errorf("UDM_Q05.DSP is required")
	}
	for _, item := range m.DSP {
		if err := item.Validate(); err != nil {
			return fmt.Errorf("UDM_Q05.DSP: %w", err)
		}
	}

	if m.DSC == nil {
		return fmt.Errorf("UDM_Q05.DSC is required")
	}
	if m.DSC != nil {
		if err := m.DSC.Validate(); err != nil {
			return fmt.Errorf("UDM_Q05.DSC: %w", err)
		}
	}
	return nil
}

func (m *UDM_Q05) SetMSH(v *MSH) *UDM_Q05 {
	m.MSH = v
	return m
}

func (m *UDM_Q05) SetURD(v *URD) *UDM_Q05 {
	m.URD = v
	return m
}

func (m *UDM_Q05) SetURS(v *URS) *UDM_Q05 {
	m.URS = v
	return m
}

func (m *UDM_Q05) AddDSP(v DSP) *UDM_Q05 {
	m.DSP = append(m.DSP, v)
	return m
}

func (m *UDM_Q05) SetDSC(v *DSC) *UDM_Q05 {
	m.DSC = v
	return m
}
