// Code generated by gen_hl7v2. DO NOT EDIT.

package v21

// ACC - Accident
type ACC struct {
	AccidentDateTime TS `hl7:"1"`
	AccidentCode     ID `hl7:"2"`
	AccidentLocation ST `hl7:"3"`
}

// ADD - Addendum
type ADD struct {
	AddendumContinuationPointer ST `hl7:"1"`
}

// BHS - Batch Header
type BHS struct {
	BatchFieldSeparator       ST `hl7:"1,required"`
	BatchEncodingCharacters   ST `hl7:"2,required"`
	BatchSendingApplication   ST `hl7:"3"`
	BatchSendingFacility      ST `hl7:"4"`
	BatchReceivingApplication ST `hl7:"5"`
	BatchReceivingFacility    ST `hl7:"6"`
	BatchCreationDateTime     TS `hl7:"7"`
	BatchSecurity             ST `hl7:"8"`
	BatchNameIdType           ST `hl7:"9"`
	BatchComment              ST `hl7:"10"`
	BatchControlId            ST `hl7:"11"`
	ReferenceBatchControlId   ST `hl7:"12"`
}

// BLG - Billing
type BLG struct {
	WhenToCharge CM `hl7:"1"`
	ChargeType   ID `hl7:"2"`
	AccountId    CM `hl7:"3"`
}

// BTS - Batch Trailer
type BTS struct {
	BatchMessageCount ST `hl7:"1"`
	BatchComment      ST `hl7:"2"`
	BatchTotals       CM `hl7:"3"`
}

// DG1 - Diagnosis
type DG1 struct {
	SetIdDiagnosis          SI `hl7:"1,required"`
	DiagnosisCodingMethod   ID `hl7:"2,required"`
	DiagnosisCode           ID `hl7:"3"`
	DiagnosisDescription    ST `hl7:"4"`
	DiagnosisDateTime       TS `hl7:"5"`
	DiagnosisDrgType        ID `hl7:"6,required"`
	MajorDiagnosticCategory ST `hl7:"7"`
	DiagnosticRelatedGroup  ID `hl7:"8"`
	DrgApprovalIndicator    ID `hl7:"9"`
	DrgGrouperReviewCode    ID `hl7:"10"`
	OutlierType             ID `hl7:"11"`
	OutlierDays             NM `hl7:"12"`
	OutlierCost             NM `hl7:"13"`
	GrouperVersionAndType   ST `hl7:"14"`
}

// DSC - Continuation Pointer
type DSC struct {
	ContinuationPointer ST `hl7:"1"`
}

// DSP - Display Data
type DSP struct {
	SetIdDisplayData  SI `hl7:"1"`
	DisplayLevel      SI `hl7:"2"`
	DataLine          TX `hl7:"3,required"`
	LogicalBreakPoint ST `hl7:"4"`
	ResultId          TX `hl7:"5"`
}

// ERR - Error
type ERR struct {
	ErrorCodeAndLocation []ID `hl7:"1,required"`
}

// EVN - Event Type
type EVN struct {
	EventTypeCode        ID `hl7:"1,required"`
	DateTimeOfEvent      TS `hl7:"2,required"`
	DateTimePlannedEvent TS `hl7:"3"`
	EventReasonCode      ID `hl7:"4"`
}

// FHS - File Header
type FHS struct {
	FileFieldSeparator       ST `hl7:"1,required"`
	FileEncodingCharacters   ST `hl7:"2,required"`
	FileSendingApplication   ST `hl7:"3"`
	FileSendingFacility      ST `hl7:"4"`
	FileReceivingApplication ST `hl7:"5"`
	FileReceivingFacility    ST `hl7:"6"`
	DateTimeOfFileCreation   TS `hl7:"7"`
	FileSecurity             ST `hl7:"8"`
	FileNameId               ST `hl7:"9"`
	FileHeaderComment        ST `hl7:"10"`
	FileControlId            ST `hl7:"11"`
	ReferenceFileControlId   ST `hl7:"12"`
}

// FT1 - Financial Transaction
type FT1 struct {
	SetIdFinancialTransaction SI `hl7:"1"`
	TransactionId             ST `hl7:"2"`
	TransactionBatchId        ST `hl7:"3"`
	TransactionDate           DT `hl7:"4,required"`
	TransactionPostingDate    DT `hl7:"5"`
	TransactionType           ID `hl7:"6,required"`
	TransactionCode           ID `hl7:"7,required"`
	TransactionDescription    ST `hl7:"8"`
	TransactionDescriptionAlt ST `hl7:"9"`
	TransactionAmountExtended NM `hl7:"10"`
	TransactionQuantity       NM `hl7:"11"`
	TransactionAmountUnit     NM `hl7:"12"`
	DepartmentCode            ST `hl7:"13"`
	InsurancePlanId           ID `hl7:"14"`
	InsuranceAmount           NM `hl7:"15"`
	PatientLocation           ST `hl7:"16"`
	FeeSchedule               ID `hl7:"17"`
	PatientType               ID `hl7:"18"`
	DiagnosisCode             ID `hl7:"19"`
	PerformedByCode           CN `hl7:"20"`
	OrderedByCode             CN `hl7:"21"`
	UnitCost                  NM `hl7:"22"`
}

// FTS - File Trailer
type FTS struct {
	FileBatchCount     ST `hl7:"1"`
	FileTrailerComment ST `hl7:"2"`
}

// GT1 - Guarantor
type GT1 struct {
	SetIdGuarantor            SI `hl7:"1,required"`
	GuarantorNumber           ID `hl7:"2"`
	GuarantorName             PN `hl7:"3,required"`
	GuarantorSpouseName       PN `hl7:"4"`
	GuarantorAddress          AD `hl7:"5"`
	GuarantorPhNumHome        TN `hl7:"6"`
	GuarantorPhNumBusiness    TN `hl7:"7"`
	GuarantorDateOfBirth      DT `hl7:"8"`
	GuarantorSex              ID `hl7:"9"`
	GuarantorType             ID `hl7:"10"`
	GuarantorRelationship     ID `hl7:"11"`
	GuarantorSsn              ST `hl7:"12"`
	GuarantorDateBegin        DT `hl7:"13"`
	GuarantorDateEnd          DT `hl7:"14"`
	GuarantorPriority         NM `hl7:"15"`
	GuarantorEmployerName     ST `hl7:"16"`
	GuarantorEmployerAddress  AD `hl7:"17"`
	GuarantorEmployPhone      TN `hl7:"18"`
	GuarantorEmployeeIdNum    ST `hl7:"19"`
	GuarantorEmploymentStatus ID `hl7:"20"`
}

// IN1 - Insurance
type IN1 struct {
	SetIdInsurance                SI `hl7:"1,required"`
	InsurancePlanId               ID `hl7:"2,required"`
	InsuranceCompanyId            ST `hl7:"3,required"`
	InsuranceCompanyName          ST `hl7:"4"`
	InsuranceCompanyAddress       AD `hl7:"5"`
	InsuranceCoContactPers        PN `hl7:"6"`
	InsuranceCoPhoneNumber        TN `hl7:"7"`
	GroupNumber                   ST `hl7:"8"`
	GroupName                     ST `hl7:"9"`
	InsuredSGroupEmpId            ST `hl7:"10"`
	InsuredSGroupEmpName          ST `hl7:"11"`
	PlanEffectiveDate             DT `hl7:"12"`
	PlanExpirationDate            DT `hl7:"13"`
	AuthorizationInformation      ST `hl7:"14"`
	PlanType                      ID `hl7:"15"`
	NameOfInsured                 PN `hl7:"16"`
	InsuredSRelationshipToPatient ID `hl7:"17"`
	InsuredSDateOfBirth           DT `hl7:"18"`
	InsuredSAddress               AD `hl7:"19"`
	AssignmentOfBenefits          ID `hl7:"20"`
	CoordinationOfBenefits        ID `hl7:"21"`
	CoordOfBenPriority            ST `hl7:"22"`
	NoticeOfAdmissionCode         ID `hl7:"23"`
	NoticeOfAdmissionDate         DT `hl7:"24"`
	RptOfEligibilityCode          ID `hl7:"25"`
	RptOfEligibilityDate          DT `hl7:"26"`
	ReleaseInformationCode        ID `hl7:"27"`
	PreAdmitCertPac               ST `hl7:"28"`
	VerificationDate              DT `hl7:"29"`
	VerificationBy                CM `hl7:"30"`
	TypeOfAgreementCode           ID `hl7:"31"`
	BillingStatus                 ID `hl7:"32"`
	LifetimeReserveDays           NM `hl7:"33"`
	DelayBeforeLRDay              NM `hl7:"34"`
	CompanyPlanCode               ST `hl7:"35"`
	PolicyNumber                  ST `hl7:"36"`
	PolicyDeductible              NM `hl7:"37"`
	PolicyLimitAmount             NM `hl7:"38"`
	PolicyLimitDays               NM `hl7:"39"`
	RoomRateSemiPrivate           NM `hl7:"40"`
	RoomRatePrivate               NM `hl7:"41"`
	InsuredSEmploymentStatus      ID `hl7:"42"`
	InsuredSSex                   ID `hl7:"43"`
	InsuredSEmployerAddress       AD `hl7:"44"`
}

// MRG - Merge Patient Information
type MRG struct {
	PriorPatientIdInternal    CK `hl7:"1,required"`
	PriorAlternatePatientId   CK `hl7:"2"`
	PriorPatientAccountNumber CK `hl7:"3"`
}

// MSA - Message Acknowledgment
type MSA struct {
	AcknowledgmentCode        ID `hl7:"1,required"`
	MessageControlId          ST `hl7:"2,required"`
	TextMessage               ST `hl7:"3"`
	ExpectedSequenceNumber    NM `hl7:"4"`
	DelayedAcknowledgmentType ID `hl7:"5"`
}

// MSH - Message Header
type MSH struct {
	FieldSeparator       ST `hl7:"1,required"`
	EncodingCharacters   ST `hl7:"2,required"`
	SendingApplication   ST `hl7:"3"`
	SendingFacility      ST `hl7:"4"`
	ReceivingApplication ST `hl7:"5"`
	ReceivingFacility    ST `hl7:"6"`
	DateTimeOfMessage    TS `hl7:"7"`
	Security             ST `hl7:"8"`
	MessageType          ID `hl7:"9,required"`
	MessageControlId     ST `hl7:"10,required"`
	ProcessingId         ID `hl7:"11,required"`
	VersionId            NM `hl7:"12,required"`
	SequenceNumber       NM `hl7:"13"`
	ContinuationPointer  ST `hl7:"14"`
}

// NCK - System Clock
type NCK struct {
	SystemDateTime TS `hl7:"1,required"`
}

// NK1 - Next Of Kin
type NK1 struct {
	SetIdNextOfKin        SI   `hl7:"1,required"`
	NextOfKinName         PN   `hl7:"2"`
	NextOfKinRelationship ST   `hl7:"3"`
	NextOfKinAddress      AD   `hl7:"4"`
	NextOfKinPhoneNumber  []TN `hl7:"5"`
}

// NPU - Non-patient Update
type NPU struct {
	BedLocation ID `hl7:"1,required"`
	BedStatus   ID `hl7:"2"`
}

// NSC - Status Change
type NSC struct {
	NetworkChangeType  ID `hl7:"1,required"`
	CurrentCpu         ST `hl7:"2"`
	CurrentFileserver  ST `hl7:"3"`
	CurrentApplication ST `hl7:"4"`
	CurrentFacility    ST `hl7:"5"`
	NewCpu             ST `hl7:"6"`
	NewFileserver      ST `hl7:"7"`
	NewApplication     ST `hl7:"8"`
	NewFacility        ST `hl7:"9"`
}

// NST - Statistics
type NST struct {
	StatisticsAvailable    ID `hl7:"1,required"`
	SourceIdentifier       ST `hl7:"2"`
	SourceType             ID `hl7:"3"`
	StatisticsStart        TS `hl7:"4"`
	StatisticsEnd          TS `hl7:"5"`
	ReceiveCharacterCount  NM `hl7:"6"`
	SendCharacterCount     NM `hl7:"7"`
	MessagesReceived       NM `hl7:"8"`
	MessagesSent           NM `hl7:"9"`
	ChecksumErrorsReceived NM `hl7:"10"`
	LengthErrorsReceived   NM `hl7:"11"`
	OtherErrorsReceived    NM `hl7:"12"`
	ConnectTimeouts        NM `hl7:"13"`
	ReceiveTimeouts        NM `hl7:"14"`
	NetworkErrors          NM `hl7:"15"`
}

// NTE - Notes And Comments
type NTE struct {
	SetIdNotesAndComments SI   `hl7:"1"`
	SourceOfComment       ID   `hl7:"2"`
	Comment               []TX `hl7:"3,required"`
}

// OBR - Observation Request
type OBR struct {
	SetIdObservationRequest    SI   `hl7:"1"`
	PlacerOrder                CM   `hl7:"2"`
	FillerOrder                CM   `hl7:"3"`
	UniversalServiceIdent      CE   `hl7:"4,required"`
	Priority                   ST   `hl7:"5"`
	RequestedDateTime          TS   `hl7:"6"`
	ObservationDateTime        TS   `hl7:"7,required"`
	ObservationEndDateTime     TS   `hl7:"8,required"`
	CollectionVolume           CQ   `hl7:"9,required"`
	CollectorIdentifier        []CN `hl7:"10"`
	SpecimenActionCode         ST   `hl7:"11"`
	DangerCode                 CM   `hl7:"12"`
	RelevantClinicalInfo       ST   `hl7:"13"`
	SpecimenReceivedDateTime   TS   `hl7:"14,required"`
	SpecimenSource             CM   `hl7:"15"`
	OrderingProvider           []CN `hl7:"16"`
	OrderCallBackPhoneNum      []TN `hl7:"17"`
	PlacersField1              ST   `hl7:"18"`
	PlacersField2              ST   `hl7:"19"`
	FillersField1              ST   `hl7:"20"`
	FillersField2              ST   `hl7:"21"`
	ResultsRptStatusChngDateT  TS   `hl7:"22,required"`
	ChargeToPractice           CM   `hl7:"23"`
	DiagnosticServSectId       ID   `hl7:"24"`
	ResultStatus               ID   `hl7:"25"`
	LinkedResults              CE   `hl7:"26"`
	QuantityTiming             []CM `hl7:"27"`
	ResultCopiesTo             []CN `hl7:"28"`
	ParentAccession            CM   `hl7:"29"`
	TransportationMode         ID   `hl7:"30"`
	ReasonForStudy             []CE `hl7:"31"`
	PrincipalResultInterpreter CN   `hl7:"32"`
	AssistantResultInterpreter CN   `hl7:"33"`
	Technician                 CN   `hl7:"34"`
	Transcriptionist           CN   `hl7:"35"`
	ScheduledDateTime          TS   `hl7:"36"`
}

// OBX - Result
type OBX struct {
	SetIdObservationSimple  SI   `hl7:"1"`
	ValueType               ID   `hl7:"2"`
	ObservationIdentifier   CE   `hl7:"3,required"`
	ObservationSubId        NM   `hl7:"4"`
	ObservationResults      ST   `hl7:"5,required"`
	Units                   ID   `hl7:"6"`
	ReferencesRange         ST   `hl7:"7"`
	AbnormalFlags           []ST `hl7:"8"`
	Probability             NM   `hl7:"9"`
	NatureOfAbnormalTest    ID   `hl7:"10"`
	ObservResultStatus      ID   `hl7:"11"`
	DateLastObsNormalValues TS   `hl7:"12"`
}

// ORC - Common Order
type ORC struct {
	OrderControl          ST   `hl7:"1,required"`
	PlacerOrder           CM   `hl7:"2"`
	FillerOrder           CM   `hl7:"3"`
	PlacerGroup           CM   `hl7:"4"`
	OrderStatus           ST   `hl7:"5"`
	ResponseFlag          ST   `hl7:"6"`
	TimingQuantity        CM   `hl7:"7"`
	Parent                CM   `hl7:"8"`
	DateTimeOfTransaction TS   `hl7:"9"`
	EnteredBy             CN   `hl7:"10"`
	VerifiedBy            CN   `hl7:"11"`
	OrderingProvider      CN   `hl7:"12"`
	EntererSLocation      CM   `hl7:"13"`
	CallBackPhoneNumber   []TN `hl7:"14"`
}

// ORO - Order Other
type ORO struct {
	OrderItemId       CE   `hl7:"1"`
	SubstituteAllowed ID   `hl7:"2"`
	ResultsCopiesTo   []CN `hl7:"3"`
	StockLocation     ID   `hl7:"4"`
}

// PD1 - Patient Demographics
type PD1 struct {
	PD11 ST `hl7:"1"`
}

// PID - Patient Identification
type PID struct {
	SetIdPatientId              SI   `hl7:"1"`
	PatientIdExternalExternalId CK   `hl7:"2"`
	PatientIdInternalInternalId CK   `hl7:"3,required"`
	AlternatePatientId          ST   `hl7:"4"`
	PatientName                 PN   `hl7:"5,required"`
	MotherSMaidenName           ST   `hl7:"6"`
	DateOfBirth                 DT   `hl7:"7"`
	Sex                         ID   `hl7:"8"`
	PatientAlias                []PN `hl7:"9"`
	EthnicGroup                 ID   `hl7:"10"`
	PatientAddress              AD   `hl7:"11"`
	CountyCode                  ID   `hl7:"12"`
	PhoneNumberHome             []TN `hl7:"13"`
	PhoneNumberBusiness         []TN `hl7:"14"`
	LanguagePatient             ST   `hl7:"15"`
	MaritalStatus               ID   `hl7:"16"`
	Religion                    ID   `hl7:"17"`
	PatientAccountNumber        CK   `hl7:"18"`
	SsnNumberPatient            ST   `hl7:"19"`
	DriverSLicNumPatient        CM   `hl7:"20"`
}

// PR1 - Procedures
type PR1 struct {
	SetIdProcedure        []SI `hl7:"1,required"`
	ProcedureCodingMethod ID   `hl7:"2,required"`
	ProcedureCode         ID   `hl7:"3,required"`
	ProcedureDescription  ST   `hl7:"4"`
	ProcedureDateTime     TS   `hl7:"5,required"`
	ProcedureType         ID   `hl7:"6,required"`
	ProcedureMinutes      NM   `hl7:"7"`
	Anesthesiologist      CN   `hl7:"8"`
	AnesthesiaCode        ID   `hl7:"9"`
	AnesthesiaMinutes     NM   `hl7:"10"`
	Surgeon               CN   `hl7:"11"`
	ResidentCode          CN   `hl7:"12"`
	ConsentCode           ID   `hl7:"13"`
}

// PV1 - Patient Visit
type PV1 struct {
	SetIdPatientVisit       SI   `hl7:"1"`
	PatientClass            ID   `hl7:"2,required"`
	AssignedPatientLocation ID   `hl7:"3,required"`
	AdmissionType           ID   `hl7:"4"`
	PreAdmitNumber          ST   `hl7:"5"`
	PriorPatientLocation    ID   `hl7:"6"`
	AttendingDoctor         CN   `hl7:"7"`
	ReferringDoctor         CN   `hl7:"8"`
	ConsultingDoctor        []CN `hl7:"9"`
	HospitalService         ID   `hl7:"10"`
	TemporaryLocation       ID   `hl7:"11"`
	PreAdmitTestIndicator   ID   `hl7:"12"`
	ReAdmissionIndicator    ID   `hl7:"13"`
	AdmitSource             ID   `hl7:"14"`
	AmbulatoryStatus        ID   `hl7:"15"`
	VipIndicator            ID   `hl7:"16"`
	AdmittingDoctor         CN   `hl7:"17"`
	PatientType             ID   `hl7:"18"`
	VisitNumber             NM   `hl7:"19"`
	FinancialClass          []ID `hl7:"20"`
	ChargePriceIndicator    ID   `hl7:"21"`
	CourtesyCode            ID   `hl7:"22"`
	CreditRating            ID   `hl7:"23"`
	ContractCode            []ID `hl7:"24"`
	ContractEffectiveDate   []DT `hl7:"25"`
	ContractAmount          []NM `hl7:"26"`
	ContractPeriod          []NM `hl7:"27"`
	InterestCode            ID   `hl7:"28"`
	TransferToBadDebtCode   ID   `hl7:"29"`
	TransferToBadDebtDate   DT   `hl7:"30"`
	BadDebtAgencyCode       ST   `hl7:"31"`
	BadDebtTransferAmount   NM   `hl7:"32"`
	BadDebtRecoveryAmount   NM   `hl7:"33"`
	DeleteAccountIndicator  ID   `hl7:"34"`
	DeleteAccountDate       DT   `hl7:"35"`
	DischargeDisposition    ID   `hl7:"36"`
	DischargedToLocation    ID   `hl7:"37"`
	DietType                ID   `hl7:"38"`
	ServicingFacility       ID   `hl7:"39"`
	BedStatus               ID   `hl7:"40"`
	AccountStatus           ID   `hl7:"41"`
	PendingLocation         ID   `hl7:"42"`
	PriorTemporaryLocation  ID   `hl7:"43"`
	AdmitDateTime           TS   `hl7:"44"`
	DischargeDateTime       TS   `hl7:"45"`
	CurrentPatientBalance   NM   `hl7:"46"`
	TotalCharges            NM   `hl7:"47"`
	TotalAdjustments        NM   `hl7:"48"`
	TotalPayments           NM   `hl7:"49"`
}

// QRD - Query Definition
type QRD struct {
	QueryDateTime            TS   `hl7:"1,required"`
	QueryFormatCode          ID   `hl7:"2,required"`
	QueryPriority            ID   `hl7:"3,required"`
	QueryId                  ST   `hl7:"4,required"`
	DeferredResponseType     ID   `hl7:"5"`
	DeferredResponseDateTime TS   `hl7:"6"`
	QuantityLimitedRequest   CQ   `hl7:"7,required"`
	WhoSubjectFilter         []ST `hl7:"8,required"`
	WhatSubjectFilter        []ID `hl7:"9,required"`
	WhatDepartmentDataCode   []ST `hl7:"10,required"`
	WhatDataCodeValueQual    []ST `hl7:"11"`
	QueryResultsLevel        ID   `hl7:"12"`
}

// QRF - Query Filter
type QRF struct {
	WhereSubjectFilter    []ST `hl7:"1,required"`
	WhenDataStartDateTime TS   `hl7:"2"`
	WhenDataEndDateTime   TS   `hl7:"3"`
	WhatUserQualifier     []ST `hl7:"4"`
	OtherQrySubjectFilter []ST `hl7:"5"`
}

// RX1 - Pharmacy Order
type RX1 struct {
	Unused               ST      `hl7:"1"`
	Unused2              ST      `hl7:"2"`
	Route                ST      `hl7:"3"`
	SiteAdministered     ST      `hl7:"4"`
	IvSolutionRate       CQ      `hl7:"5"`
	DrugStrength         CQ      `hl7:"6"`
	FinalConcentration   NM      `hl7:"7"`
	FinalVolumeInMl      NM      `hl7:"8"`
	DrugDose             CM      `hl7:"9"`
	DrugRole             ID      `hl7:"10"`
	PrescriptionSequence NM      `hl7:"11"`
	QuantityDispensed    CQ      `hl7:"12"`
	Unused3              ST      `hl7:"13"`
	DrugId               CE_0057 `hl7:"14"`
	ComponentDrugIds     []ID    `hl7:"15"`
	PrescriptionType     ID      `hl7:"16"`
	SubstitutionStatus   ID      `hl7:"17"`
	RxOrderStatus        ID      `hl7:"18"`
	NumberOfRefills      NM      `hl7:"19"`
	Unused4              ST      `hl7:"20"`
	RefillsRemaining     NM      `hl7:"21"`
	DeaClass             ID      `hl7:"22"`
	OrderingMdSDeaNumber NM      `hl7:"23"`
	Unused5              ST      `hl7:"24"`
	LastRefillDateTime   TS      `hl7:"25"`
	RxNumber             ST      `hl7:"26"`
	PrnStatus            ID      `hl7:"27"`
	PharmacyInstructions []TX    `hl7:"28"`
	PatientInstructions  []TX    `hl7:"29"`
	InstructionsSig      []TX    `hl7:"30"`
}

// UB1 - Ub82 Data
type UB1 struct {
	SetIdUb82                 SI   `hl7:"1"`
	BloodDeductible           ST   `hl7:"2"`
	BloodFurnPintsOf40        ST   `hl7:"3"`
	BloodReplacedPints41      ST   `hl7:"4"`
	BloodNotRplcdPints42      ST   `hl7:"5"`
	CoInsuranceDays25         ST   `hl7:"6"`
	ConditionCode             []ID `hl7:"7"`
	CoveredDays23             ST   `hl7:"8"`
	NonCoveredDays24          ST   `hl7:"9"`
	ValueAmountCode           []CM `hl7:"10"`
	NumberOfGraceDays90       ST   `hl7:"11"`
	SpecProgIndicator44       ID   `hl7:"12"`
	PsroUrApprovalInd87       ID   `hl7:"13"`
	PsroUrAprvdStayFm88       DT   `hl7:"14"`
	PsroUrAprvdStayTo89       DT   `hl7:"15"`
	Occurrence2832            []ID `hl7:"16"`
	OccurrenceSpan33          ID   `hl7:"17"`
	OccurrenceSpanStartDate33 DT   `hl7:"18"`
	OccurSpanEndDate33        DT   `hl7:"19"`
	Ub82Locator2              ST   `hl7:"20"`
	Ub82Locator9              ST   `hl7:"21"`
	Ub82Locator27             ST   `hl7:"22"`
	Ub82Locator45             ST   `hl7:"23"`
}

// URD - Results/update Definition
type URD struct {
	RUDateTime              TS   `hl7:"1"`
	ReportPriority          ID   `hl7:"2"`
	RUWhoSubjectDefinition  []ST `hl7:"3,required"`
	RUWhatSubjectDefinition []ID `hl7:"4"`
	RUWhatDepartmentCode    []ST `hl7:"5"`
	RUDisplayPrintLocations []ST `hl7:"6"`
	RUResultsLevel          ID   `hl7:"7"`
}

// URS - Unsolicited Selection
type URS struct {
	RUWhereSubjectDefinition    []ST `hl7:"1,required"`
	RUWhenDataStartDateTime     TS   `hl7:"2"`
	RUWhenDataEndDateTime       TS   `hl7:"3"`
	RUWhatUserQualifier         []ST `hl7:"4"`
	RUOtherResultsSubjectDefini []ST `hl7:"5"`
}
