// Code generated by "stringer -type=itemType -linecomment"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[itemErr-0]
	_ = x[itemSeg-1]
	_ = x[itemSegIdx-2]
	_ = x[itemField-3]
	_ = x[itemRep-4]
	_ = x[itemComp-5]
	_ = x[itemSub-6]
	_ = x[itemEOF-7]
}

const _itemType_name = "errorsegmentsegment_indexfieldrepetitioncomponentsubcomponenteof"

var _itemType_index = [...]uint8{0, 5, 12, 25, 30, 40, 49, 61, 64}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
