// Code generated by "enumer -type ActionType -yaml -json -linecomment -output=enums.go"; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ActionTypeName = "noopsaveforward"

var _ActionTypeIndex = [...]uint8{0, 4, 8, 15}

const _ActionTypeLowerName = "noopsaveforward"

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionTypeIndex)-1) {
		return fmt.Sprintf("ActionType(%d)", i)
	}
	return _ActionTypeName[_ActionTypeIndex[i]:_ActionTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActionTypeNoOp() {
	var x [1]struct{}
	_ = x[ActionNoop-(0)]
	_ = x[ActionSave-(1)]
	_ = x[ActionForward-(2)]
}

var _ActionTypeValues = []ActionType{ActionNoop, ActionSave, ActionForward}

var _ActionTypeNameToValueMap = map[string]ActionType{
	_ActionTypeName[0:4]:       ActionNoop,
	_ActionTypeLowerName[0:4]:  ActionNoop,
	_ActionTypeName[4:8]:       ActionSave,
	_ActionTypeLowerName[4:8]:  ActionSave,
	_ActionTypeName[8:15]:      ActionForward,
	_ActionTypeLowerName[8:15]: ActionForward,
}

var _ActionTypeNames = []string{
	_ActionTypeName[0:4],
	_ActionTypeName[4:8],
	_ActionTypeName[8:15],
}

// ActionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActionTypeString(s string) (ActionType, error) {
	if val, ok := _ActionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActionType values", s)
}

// ActionTypeValues returns all values of the enum
func ActionTypeValues() []ActionType {
	return _ActionTypeValues
}

// ActionTypeStrings returns a slice of all String values of the enum
func ActionTypeStrings() []string {
	strs := make([]string, len(_ActionTypeNames))
	copy(strs, _ActionTypeNames)
	return strs
}

// IsAActionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActionType) IsAActionType() bool {
	for _, v := range _ActionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ActionType
func (i ActionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ActionType
func (i *ActionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ActionType should be a string, got %s", data)
	}

	var err error
	*i, err = ActionTypeString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for ActionType
func (i ActionType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for ActionType
func (i *ActionType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ActionTypeString(s)
	return err
}
