// Code generated by "enumer -type=TableType,DataTypeType -json -text -sql -yaml -linecomment -output=schema_enums.go"; DO NOT EDIT.

//
package schema

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const _TableTypeName = "UnknownUserHL7LocalPreLoaded"

var _TableTypeIndex = [...]uint8{0, 7, 11, 14, 19, 28}

func (i TableType) String() string {
	if i < 0 || i >= TableType(len(_TableTypeIndex)-1) {
		return fmt.Sprintf("TableType(%d)", i)
	}
	return _TableTypeName[_TableTypeIndex[i]:_TableTypeIndex[i+1]]
}

var _TableTypeValues = []TableType{0, 1, 2, 3, 4}

var _TableTypeNameToValueMap = map[string]TableType{
	_TableTypeName[0:7]:   0,
	_TableTypeName[7:11]:  1,
	_TableTypeName[11:14]: 2,
	_TableTypeName[14:19]: 3,
	_TableTypeName[19:28]: 4,
}

// TableTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TableTypeString(s string) (TableType, error) {
	if val, ok := _TableTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TableType values", s)
}

// TableTypeValues returns all values of the enum
func TableTypeValues() []TableType {
	return _TableTypeValues
}

// IsATableType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TableType) IsATableType() bool {
	for _, v := range _TableTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TableType
func (i TableType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TableType
func (i *TableType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TableType should be a string, got %s", data)
	}

	var err error
	*i, err = TableTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TableType
func (i TableType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TableType
func (i *TableType) UnmarshalText(text []byte) error {
	var err error
	*i, err = TableTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for TableType
func (i TableType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for TableType
func (i *TableType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = TableTypeString(s)
	return err
}

func (i TableType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *TableType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := TableTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

const _DataTypeTypeName = "DataTypeComponent"

var _DataTypeTypeIndex = [...]uint8{0, 8, 17}

func (i DataTypeType) String() string {
	if i < 0 || i >= DataTypeType(len(_DataTypeTypeIndex)-1) {
		return fmt.Sprintf("DataTypeType(%d)", i)
	}
	return _DataTypeTypeName[_DataTypeTypeIndex[i]:_DataTypeTypeIndex[i+1]]
}

var _DataTypeTypeValues = []DataTypeType{0, 1}

var _DataTypeTypeNameToValueMap = map[string]DataTypeType{
	_DataTypeTypeName[0:8]:  0,
	_DataTypeTypeName[8:17]: 1,
}

// DataTypeTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DataTypeTypeString(s string) (DataTypeType, error) {
	if val, ok := _DataTypeTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DataTypeType values", s)
}

// DataTypeTypeValues returns all values of the enum
func DataTypeTypeValues() []DataTypeType {
	return _DataTypeTypeValues
}

// IsADataTypeType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DataTypeType) IsADataTypeType() bool {
	for _, v := range _DataTypeTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DataTypeType
func (i DataTypeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DataTypeType
func (i *DataTypeType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DataTypeType should be a string, got %s", data)
	}

	var err error
	*i, err = DataTypeTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DataTypeType
func (i DataTypeType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DataTypeType
func (i *DataTypeType) UnmarshalText(text []byte) error {
	var err error
	*i, err = DataTypeTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for DataTypeType
func (i DataTypeType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for DataTypeType
func (i *DataTypeType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = DataTypeTypeString(s)
	return err
}

func (i DataTypeType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *DataTypeType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := DataTypeTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
