// Code generated by gen_hl7v2. DO NOT EDIT.

package v271

// AD - Address
// This data type specifies the address of a person, place or organization.
//
// Note: Used only in the LA1 data type. Retained for backward compatibility as of v2.6. Replaced elsewhere by the XAD data type as of v2.3.
//
// Example:
// |10 ASH LN^#3^LIMA^OH^48132|
type AD struct {
	StreetAddress              ST `hl7:"1"`
	OtherDesignation           ST `hl7:"2"`
	City                       ST `hl7:"3"`
	StateOrProvince            ST `hl7:"4"`
	ZipOrPostalCode            ST `hl7:"5"`
	Country                    ID `hl7:"6"`
	AddressType                ID `hl7:"7"`
	OtherGeographicDesignation ST `hl7:"8"`
}

// AUI - Authorization Information
// This data type specifies the identifier or code for an insurance authorization instance and its associated detail.
//
// Note: Replaces the CM data type used in sections 6.5.6.14 IN1-14, as of v2.5.
type AUI struct {
	AuthorizationNumber ST `hl7:"1"`
	Date                DT `hl7:"2"`
	Source              ST `hl7:"3"`
}

// CCD - Charge Code And Date
// Specifies whether a charge action is based on an invocation event or is time-based.
//
// Note: Replaces the CM data type used in section 4.5.2.1 BLG-1, as of v2.5.
type CCD struct {
	InvocationEvent ID  `hl7:"1"`
	DateTime        DTM `hl7:"2"`
}

// CCP - Channel Calibration Parameters
// This data type identifies the corrections to channel sensitivity, the baseline, and the channel time skew when transmitting waveform results.
//
// Note: Replaces the CM data type used in 7.14.1.5 OBX-5.3 where OBX-5 Observation value (*) is data type CD as of v 2.5.
//
// Attention: Retained for backward compatibility only in version 2.7.  This is used only in the CD Channel Definition data type, which has been retained for backward compatibility only in v2.7.
type CCP struct {
	ChannelCalibrationSensitivityCorrectionFactor NM `hl7:"1"`
	ChannelCalibrationBaseline                    NM `hl7:"2"`
	ChannelCalibrationTimeSkew                    NM `hl7:"3"`
}

// CD - Channel Definition
// This data type is used for labeling of digital waveform data. It defines a recording channel, which is associated with one of the values in each time sample of waveform data. Each channel has a number (which generally defines its position in a multichannel display) and an optional name or label (also used in displays). One or two named waveform sources may also be associated with a channel (providing for the use of differential amplifiers with two inputs). The other components of the channel definition data type are optional.
//
// Attention: Retained for backward compatibility only in version 2.7.  This is used only in the waveform message, CHM category, which has been retained for backward compatibility only in version 2.7.
type CD struct {
	ChannelIdentifier            WVI `hl7:"1"`
	WaveformSource               WVS `hl7:"2"`
	ChannelSensitivityAndUnits   CSU `hl7:"3"`
	ChannelCalibrationParameters CCP `hl7:"4"`
	ChannelSamplingFrequency     NM  `hl7:"5"`
	MinimumAndMaximumDataValues  NR  `hl7:"6"`
}

// CF - Coded Element With Formatted Values
// This data type transmits codes and the formatted text associated with the code. This data type can be used to transmit for the first time the formatted text for the canned text portion of a report, for example, a standard radiological description for a normal chest X ray. The receiving system can store this information and in subsequent messages only the identifier need be sent. Another potential use of this data type is transmitting master file records that contain formatted text. This data type has six components as follows:
// The components, primary and alternate, are defined exactly as in the CE data type with the exception of the second and fifth components, which are of the formatted text data type.
//
// Example:
// OBX||CF|71020^CXR^99CPMC||79989^\H\Description:\N\\.sp\\ti+4\Heart is not enlarged. There is no evidence of pneumonia, effusion, pneumothorax or any masses. \.sp+3\\H\Impression:\N\\.sp\\.ti+4\Negative chest.^99CPMC
//
// As of v2.7 a third tuple, formerly known as triplet, has been added  to the CF data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CF as a whole.
type CF struct {
	Identifier                           ST  `hl7:"1"`
	FormattedText                        FT  `hl7:"2"`
	NameOfCodingSystem                   ID  `hl7:"3"`
	AlternateIdentifier                  ST  `hl7:"4"`
	AlternateFormattedText               FT  `hl7:"5"`
	NameOfAlternateCodingSystem          ID  `hl7:"6"`
	CodingSystemVersionId                ST  `hl7:"7"`
	AlternateCodingSystemVersionId       ST  `hl7:"8"`
	OriginalText                         ST  `hl7:"9"`
	SecondAlternateIdentifier            ST  `hl7:"10"`
	SecondAlternateFormattedText         FT  `hl7:"11"`
	NameOfSecondAlternateCodingSystem    ID  `hl7:"12"`
	SecondAlternateCodingSystemVersionId ST  `hl7:"13"`
	CodingSystemOid                      ST  `hl7:"14"`
	ValueSetOid                          ST  `hl7:"15"`
	ValueSetVersionId                    DTM `hl7:"16"`
	AlternateCodingSystemOid             ST  `hl7:"17"`
	AlternateValueSetOid                 ST  `hl7:"18"`
	AlternateValueSetVersionId           DTM `hl7:"19"`
	SecondAlternateCodingSystemOid       ST  `hl7:"20"`
	SecondAlternateValueSetOid           ST  `hl7:"21"`
	SecondAlternateValueSetVersionId     DTM `hl7:"22"`
}

// CNE - Coded With No Exceptions
// Specifies a coded element and its associated detail. The CNE data type is used when a required or mandatory coded field is needed. The specified HL7 table or imported or externally defined coding system must be used and may not be extended with local values. Text may not replace the code. A CNE field must have an HL7 defined or external table associated with it.  A CNE field may be context sensitive such that a choice of explicit coding systems might be designated. This allows for realm and other types of specificity. Every effort will be made to enumerate the valid coding system(s) to be specified in the 3rd component, however, the standards body realizes that this is impossible to fully enumerate.
//
// Note: The presence of two sets of equivalent codes in this data type is semantically different from a repetition of a CNE-type field. With repetition, several distinct codes (with distinct meanings) may be transmitted.
//
// Example 1: The drug must be coded and must be taken from the specified coding system. The coding system is an external coding system. Example is derived from FT1-26.
// |0006-0106-58^Prinivil 10mg oral tablet^NDC|
//
// Example 2: Consent mode must be coded and must be taken from the specified coding system. The coding system is an HL7 code table. Example is taken from CON-10.
// |V^Verbal^HL70497^^^^2.7|
//
// As of v2.7 a third tuple, formerly known as triplet, has been added  to the CNE data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CNE as a whole.
type CNE struct {
	Identifier                           ST  `hl7:"1"`
	Text                                 ST  `hl7:"2"`
	NameOfCodingSystem                   ID  `hl7:"3"`
	AlternateIdentifier                  ST  `hl7:"4"`
	AlternateText                        ST  `hl7:"5"`
	NameOfAlternateCodingSystem          ID  `hl7:"6"`
	CodingSystemVersionId                ST  `hl7:"7"`
	AlternateCodingSystemVersionId       ST  `hl7:"8"`
	OriginalText                         ST  `hl7:"9"`
	SecondAlternateIdentifier            ST  `hl7:"10"`
	SecondAlternateText                  ST  `hl7:"11"`
	NameOfSecondAlternateCodingSystem    ID  `hl7:"12"`
	SecondAlternateCodingSystemVersionId ST  `hl7:"13"`
	CodingSystemOid                      ST  `hl7:"14"`
	ValueSetOid                          ST  `hl7:"15"`
	ValueSetVersionId                    DTM `hl7:"16"`
	AlternateCodingSystemOid             ST  `hl7:"17"`
	AlternateValueSetOid                 ST  `hl7:"18"`
	AlternateValueSetVersionId           DTM `hl7:"19"`
	SecondAlternateCodingSystemOid       ST  `hl7:"20"`
	SecondAlternateValueSetOid           ST  `hl7:"21"`
	SecondAlternateValueSetVersionId     DTM `hl7:"22"`
}

// CNN - Composite Id Number And Name Simplified
// Specifies a person using both an identifier and the person’s name. Retained for backward compatibility only as of v2.6.
//
// Note: Restores the original data type CN as was initially implementable in the CM used in sections 4.5.3.32 and 7.4.1.32 - (OBR-32), 4.5.3.33 and 7.4.1.33 - ( OBR-33), 4.5.3.34 and 7.4.1.34 - ( OBR-34), 4.5.3.35 and 7.4.1.35 - (OBR-35). Components 7 and 8, however, have been promoted to data type IS to be consistent with current practice without violating backward compatibility.
//
// Attention: Retained for backward compatibility only in version 2.6. Fields associated with this data type have been replaced by the ROL segment.
type CNN struct {
	IdNumber                                    ST `hl7:"1"`
	FamilyName                                  ST `hl7:"2"`
	GivenName                                   ST `hl7:"3"`
	SecondAndFurtherGivenNamesOrInitialsThereof ST `hl7:"4"`
	SuffixEGJrOrIii                             ST `hl7:"5"`
	PrefixEGDr                                  ST `hl7:"6"`
	DegreeEGMd                                  IS `hl7:"7"`
	SourceTable                                 IS `hl7:"8"`
	AssigningAuthorityNamespaceId               IS `hl7:"9"`
	AssigningAuthorityUniversalId               ST `hl7:"10"`
	AssigningAuthorityUniversalIdType           ID `hl7:"11"`
}

// CP - Composite Price
// Note: This data type is often used to define a repeating field within a given segment.
//
// Example:
// |100.00&USD^UP^0^9^min^P~50.00&USD^UP^10^59^min^P~10.00&USD^UP^60^999^P~50.00&USD^AP~200.00&USD^PF~80.00&USD^DC|
type CP struct {
	Price      MO  `hl7:"1"`
	PriceType  ID  `hl7:"2"`
	FromValue  NM  `hl7:"3"`
	ToValue    NM  `hl7:"4"`
	RangeUnits CWE `hl7:"5"`
	RangeType  ID  `hl7:"6"`
}

// CQ - Composite Quantity With Units
// Note: CQ cannot be legally expressed when embedded within another data type. Its use is constrained to a segment field.
//
// Examples:
// kilograms is an ISO unit
// |123.7^kg|
//
// weight in pounds is a customary US unit defined within ANSI+.
// |150^lb&&ANSI+|
type CQ struct {
	Quantity NM  `hl7:"1"`
	Units    CWE `hl7:"2"`
}

// CSU - Channel Sensitivity And Units
// This data type defines the channel sensitivity (gain) and the units in which it is measured in a waveform result.
//
// Note: Replaces the CM data type used in 7.14.1.5 OBX-5.3 where OBX-5 Observation value (*) is data type CD as of v 2.5.
//
// Attention: Retained for backward compatibility only in version 2.7.  This is used only in the CD Channel Definition data type, which has been retained for backward compatibility only in version 2.7.
//
// As of v2.7 a third tuple, formerly known as triplet, has been added  to the CSU data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CSU as a whole.
type CSU struct {
	ChannelSensitivity                          NM  `hl7:"1"`
	UnitOfMeasureIdentifier                     ST  `hl7:"2"`
	UnitOfMeasureDescription                    ST  `hl7:"3"`
	UnitOfMeasureCodingSystem                   ID  `hl7:"4"`
	AlternateUnitOfMeasureIdentifier            ST  `hl7:"5"`
	AlternateUnitOfMeasureDescription           ST  `hl7:"6"`
	AlternateUnitOfMeasureCodingSystem          ID  `hl7:"7"`
	UnitOfMeasureCodingSystemVersionId          ST  `hl7:"8"`
	AlternateUnitOfMeasureCodingSystemVersionId ST  `hl7:"9"`
	OriginalText                                ST  `hl7:"10"`
	SecondAlternateUnitOfMeasureIdentifier      ST  `hl7:"11"`
	SecondAlternateUnitOfMeasureText            ST  `hl7:"12"`
	NameOfSecondAlternateUnitOfMeasureCodingSy  ID  `hl7:"13"`
	SecondAlternateUnitOfMeasureCodingSystemVer ST  `hl7:"14"`
	UnitOfMeasureCodingSystemOid                ST  `hl7:"15"`
	UnitOfMeasureValueSetOid                    ST  `hl7:"16"`
	UnitOfMeasureValueSetVersionId              DTM `hl7:"17"`
	AlternateUnitOfMeasureCodingSystemOid       ST  `hl7:"18"`
	AlternateUnitOfMeasureValueSetOid           ST  `hl7:"19"`
	AlternateUnitOfMeasureValueSetVersionId     DTM `hl7:"20"`
	AlternateUnitOfMeasureCodingSystemOid2      ST  `hl7:"21"`
	AlternateUnitOfMeasureValueSetOid2          ST  `hl7:"22"`
	AlternateUnitOfMeasureValueSetVersionId2    ST  `hl7:"23"`
}

// CWE - Coded With Exceptions
// Specifies a coded element and its associated detail. The CWE data type is used when 1) more than one table may be applicable or 2) the specified HL7 or externally defined table may be extended with local values or 3) when text is in place, the code may be omitted.
//
// The presence of two sets of equivalent codes in this data type is semantically different from a repetition of a CWE-type field. With repetition, several distinct codes (with distinct meanings) may be transmitted.
//
// Usage Notes:  The CWE data type should be used for coded fields with one or more of the following characteristics:
// - The identifier code (CWE.1) component is optional
// - The set of allowable values from which the identifier code is drawn may be extended on a site-specific basis
// - An exception identifier code may be encountered; that is, a code that is not defined in the value set (either model or site-extended).
//
// This is in contrast to the CNE data type, which requires a code from a non-extendable value set be sent in the identifier code component (CNE.1) in all cases (except, of course, if the entire field is empty and defined as optional at the segment level).
//
// As of v2.7 a third tuple, formerly known as triplet, has been added  to the CWE data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CWE as a whole.
type CWE struct {
	Identifier                           ST  `hl7:"1"`
	Text                                 ST  `hl7:"2"`
	NameOfCodingSystem                   ID  `hl7:"3"`
	AlternateIdentifier                  ST  `hl7:"4"`
	AlternateText                        ST  `hl7:"5"`
	NameOfAlternateCodingSystem          ID  `hl7:"6"`
	CodingSystemVersionId                ST  `hl7:"7"`
	AlternateCodingSystemVersionId       ST  `hl7:"8"`
	OriginalText                         ST  `hl7:"9"`
	SecondAlternateIdentifier            ST  `hl7:"10"`
	SecondAlternateText                  ST  `hl7:"11"`
	NameOfSecondAlternateCodingSystem    ID  `hl7:"12"`
	SecondAlternateCodingSystemVersionId ST  `hl7:"13"`
	CodingSystemOid                      ST  `hl7:"14"`
	ValueSetOid                          ST  `hl7:"15"`
	ValueSetVersionId                    DTM `hl7:"16"`
	AlternateCodingSystemOid             ST  `hl7:"17"`
	AlternateValueSetOid                 ST  `hl7:"18"`
	AlternateValueSetVersionId           DTM `hl7:"19"`
	SecondAlternateCodingSystemOid       ST  `hl7:"20"`
	SecondAlternateValueSetOid           ST  `hl7:"21"`
	SecondAlternateValueSetVersionId     DTM `hl7:"22"`
}

// CX - Extended Composite Id With Check Digit
// This data type is used for specifying an identifier with its associated administrative detail.
//
// Note: The check digit and check digit scheme are null if ID is alphanumeric.
//
// Example:
// |1234567^4^M11^ADT01^MR^University Hospital|
type CX struct {
	IdNumber                    ST  `hl7:"1"`
	IdentifierCheckDigit        ST  `hl7:"2"`
	CheckDigitScheme            ID  `hl7:"3"`
	AssigningAuthority          HD  `hl7:"4"`
	IdentifierTypeCode          ID  `hl7:"5"`
	AssigningFacility           HD  `hl7:"6"`
	EffectiveDate               DT  `hl7:"7"`
	ExpirationDate              DT  `hl7:"8"`
	AssigningJurisdiction       CWE `hl7:"9"`
	AssigningAgencyOrDepartment CWE `hl7:"10"`
	SecurityCheck               ST  `hl7:"11"`
	SecurityCheckScheme         ID  `hl7:"12"`
}

// DDI - Daily Deductible Information
// This data type specifies the detail information for the daily deductible.
//
// Note: Replaces the CM data type used in section 6.5.7.30 IN2-30, as of v 2.5.
type DDI struct {
	DelayDays      NM `hl7:"1"`
	MonetaryAmount MO `hl7:"2"`
	NumberOfDays   NM `hl7:"3"`
}

// DIN - Date And Institution Name
// Specifies the date and institution information where a staff member became active or inactive.
//
// Note: Replaces the CM data type used in sections 15.4.6.12 STF-12 and 15.4.6.14 STF-13, as of v 2.5.
type DIN struct {
	Date            DTM `hl7:"1"`
	InstitutionName CWE `hl7:"2"`
}

// DLD - Discharge To Location And Date
// Specifies the healthcare facility to which the patient was discharged and the date.
//
// Note: Replaces the CM data type used in section 3.4.3.37 PV1-37, as of v 2.5.
type DLD struct {
	DischargeToLocation CWE `hl7:"1"`
	EffectiveDate       DTM `hl7:"2"`
}

// DLN - Driver's License Number
// This field contains the driver’s license information. For state or province refer to official postal codes for that country; for country refer to ISO 3166 for codes.
type DLN struct {
	LicenseNumber               ST  `hl7:"1"`
	IssuingStateProvinceCountry CWE `hl7:"2"`
	ExpirationDate              DT  `hl7:"3"`
}

// DLT - Delta
// Describes the information that controls delta check warnings.
//
// Note: Replaces the CM data type used in section 8.8.4.9 – OM2-9, as of v 2.5.
type DLT struct {
	NormalRange       NR `hl7:"1"`
	NumericThreshold  NM `hl7:"2"`
	ChangeComputation ID `hl7:"3"`
	DaysRetained      NM `hl7:"4"`
}

// DR - Date/time Range
// Note: DR cannot be legally expressed when embedded within another data type. Its use is constrained to a segment field.
type DR struct {
	RangeStartDateTime DTM `hl7:"1"`
	RangeEndDateTime   DTM `hl7:"2"`
}

// DT - Date
// Specifies the century and year with optional precision to month and day.
//
// The number of digits populated specifies the precision using the format specification YYYY[MM[DD]].
//
// Examples:
// |19880704|
// |199503|
//
// The DT data type does not follow the normal truncation pattern, and the truncation character is never valid in the DT data type. Instead, the truncation behavior is based on the semantics of dates.
//
// Unless specified in the context where the DT type  is used, the DT type may not be truncated. When a DT is truncated, the truncated form SHALL still be a valid DT type. Systems should always be able to persist full dates. Refer to Chapter 2, section 2.5.5.2 "Truncation Pattern" for further information.
// Note: Prior to v2.3, this data type was specified in the format YYYYMMDD. As of v2.3, month and days are no longer required. By site-specific agreement, YYYYMMDD may be used where backward compatibility must be maintained.
type DT string

// DTM - Date/time
// Specifies a point in time using a 24-hour clock notation.
//
// The number of characters populated (excluding the time zone specification) specifies the precision.
//
// Format: YYYY[MM[DD[HH[MM[SS[.S[S[S[S]]]]]]]]][+/-ZZZZ].
//
// The time zone (+/-ZZZZ) is represented as +/-HHMM offset from Coordinated Universal Time (UTC) (formerly Greenwich Mean Time (GMT)), where +0000 or -0000 both represent UTC (without offset). The specific data representations used in the HL7 encoding rules are compatible with ISO 8824-1987(E).
//
// Note: The time zone [+/-ZZZZ], when used, is restricted to legally-defined time zones and is represented in HHMM format.
type DTM string

// DTN - Day Type And Number
// This data type specifies the type and number of days for which a certification is valid.
//
// Note: Replaces the CM data type used in section 6.5.8.11 IN3-11, as of v2.5.
type DTN struct {
	DayType      CWE `hl7:"1"`
	NumberOfDays NM  `hl7:"2"`
}

// ED - Encapsulated Data
// This data type transmits encapsulated data from a source system to a destination system. It contains the identity of the source system, the type of data, the encoding method of the data, and the data itself. This data type is similar to the RP (reference pointer) data type of Section 2.A.65, "RP - reference pointer," except that instead of pointing to the data on another system, it contains the data which is to be sent to that system.
type ED struct {
	SourceApplication HD `hl7:"1"`
	TypeOfData        ID `hl7:"2"`
	DataSubtype       ID `hl7:"3"`
	Encoding          ID `hl7:"4"`
	Data              TX `hl7:"5"`
}

// EI - Entity Identifier
// The entity identifier defines a given entity within a specified series of identifiers.
//
// The EI is appropriate for, but not limited to, machine or software generated identifiers. The generated identifier goes in the first component. The remaining components, 2 through 4, are known as the assigning authority; they identify the machine/system responsible for generating the identifier in component 1.
//
// The specified series, the assigning authority, is defined by components 2 through 4. The assigning authority is of the hierarchic designator (HD) data type, but it is defined as three separate components in the EI data type, rather than as a single component as would normally be the case. This is in order to maintain backward compatibility with the EI’s use as a component in several existing data fields. Otherwise, the components 2 through 4 are as defined in Section 2.A.33, "HD - hierarchic designator". Hierarchic designators (HD) are unique across a given HL7 implementation.
type EI struct {
	EntityIdentifier ST `hl7:"1"`
	NamespaceId      IS `hl7:"2"`
	UniversalId      ST `hl7:"3"`
	UniversalIdType  ID `hl7:"4"`
}

// EIP - Entity Identifier Pair
// Specifies an identifier assigned to an entity by either the placer or the filler system. If both components are populated the identifiers must refer to the same entity.
//
// Note: Replaces the CM data type used in sections 4.5.1.8 - ORC-8, 4.5.3.29 – OBR-29, 7.3.1.29 – OBR-29, as of v 2.5.
type EIP struct {
	PlacerAssignedIdentifier EI `hl7:"1"`
	FillerAssignedIdentifier EI `hl7:"2"`
}

// ERL - Error Location
// This data type identifies the segment and its constituent where an error has occurred.
type ERL struct {
	SegmentId          ST `hl7:"1"`
	SegmentSequence    NM `hl7:"2"`
	FieldPosition      NM `hl7:"3"`
	FieldRepetition    NM `hl7:"4"`
	ComponentNumber    NM `hl7:"5"`
	SubComponentNumber NM `hl7:"6"`
}

// FC - Financial Class
type FC struct {
	FinancialClassCode CWE `hl7:"1"`
	EffectiveDate      DTM `hl7:"2"`
}

// FN - Family Name
// This data type allows full specification of the surname of a person. Where appropriate, it differentiates the person's own surname from that of the person's partner or spouse, in cases where the person's name may contain elements from either name. It also permits messages to distinguish the surname prefix (such as "van" or "de") from the surname root.
//
// Note: Appears ONLY in the PPN, XCN and XPN.
type FN struct {
	Surname                        ST `hl7:"1"`
	OwnSurnamePrefix               ST `hl7:"2"`
	OwnSurname                     ST `hl7:"3"`
	SurnamePrefixFromPartnerSpouse ST `hl7:"4"`
	SurnameFromPartnerSpouse       ST `hl7:"5"`
}

// FT - Formatted Text Data
// This data type is derived from the TX data type by allowing the addition of embedded formatting instructions. These instructions are limited to those that are intrinsic and independent of the circumstances under which the field is being used. The actual instructions and their representation are described in section 2.7.6, “Usage and Examples of Formatted Text”. The FT field is of arbitrary length (up to 64k) and may contain formatting commands enclosed in escape characters.
//
// Example:
// |\.sp\(skip one vertical line)|
//
// For additional examples of formatting commands see Section 2.7, "Use of Escape Sequences in Text Fields".
//
// To include alternative character sets, use the appropriate escape sequence. See Chapter 2, "Control", section 2.15.9.18, "Character set" and section 2.14.9.20, "Alternate character set handling scheme".
//
// This specification applies no limit to the length of the FT data type, either here where the data type is defined, or elsewhere where the data type is used. While there is no intrinsic reason to limit the length of this data type for semantic or syntactical reasons, it is expected that some sort of limitation will be imposed for technical reasons in implementations. HL7 recommends that implementation length limits are published in implementation profiles. The contents of an FT field may be truncated, but the truncation pattern does not apply.
type FT string

// GTS - General Timing Specification
// The General Timing Specification data type is used to communicate complex inter-related information Timing information. The value of such a field follows the formatting rules for a ST field. The string data will be structured according to the rules set forth in the "Version 3 Data Types Part II Unabridged Specification" for the General Timing Specification (GTS) data type.
//
// There is no technical limit to the length of a GTS expression – the expression may be as long as logically required. The conformance length of 199 caters for all the common expressions. GTS expressions are not to be truncated.
type GTS string

// HD - Hierarchic Designator
// The basic definition of the HD is that it identifies an (administrative or system or application or other) entity that has responsibility for managing or assigning a defined set of instance identifiers (such as placer or filler number, patient identifiers, provider identifiers, etc.). This entity could be a particular health care application such as a registration system that assigns patient identifiers, a governmental entity such as a licensing authority that assigns professional identifiers or drivers’ license numbers, or a facility where such identifiers are assigned.
//
// The HD is designed to be a more powerful and more general replacement for the application identifier of HL7 versions 2.1 and 2.2. It adds two additional components, the <universal ID> and the <universal ID type> to the former application ID (which is renamed more generically to be the namespace ID).
//
// In the case where an HD identifies an entity that assigns/creates instance identifiers such as a particular patient registration system, it defines an "assigning authority". In the case where an HD identifies a location where instance identifiers are given out (although they may be created by another entity at another location) such as a particular "department of motor vehicles office location," it defines an "assigning facility". These two different uses of the HD appear in many of the extended data types.
//
// The "assigning authority" defined by the HD is similar in its role to the coding system (and version) part of the coded element data types: both identify a set of more discrete instance identifiers. The difference is that the set of HD-defined discrete instances contain identifiers of "real-world" things such as patient or clinical orders, while the coded element-defined set of discrete instances contains concept identifiers (codes).
//
// The HD is designed to be used either as a local identifier (with only the <namespace ID> valued) or a publicly-assigned identifier, a UID (<universal ID> and <universal ID type> both valued). Syntactically, the HD is a group of two identifiers: a local identifier defined by the first component and a universal identifier defined by the second and third components. HDs that have defined third components (defined UID types) must have a second component that is unique within the series of IDs defined by that component.
//
// Note: 	The HD is used in fields that in earlier versions of HL7 used the IS data type. Thus, a single component HD (only the first component valued) will look like a simple IS data type for older systems expecting a single component in the place of the HD data type.
//
// If the first component for the HD data type is present, the second and third components are optional. If the third component is present, then the second must also be present (although in this case the first is optional). The second and third components must either both be valued (both non-null), or both be not valued (both null).
// This means that if all three components of the HD are valued, the entity identified by the first component is the same as the entity identified by components two and three taken together. However, implementers may choose, by site agreement, to specify that if all three components of the HD are valued, the first component defines a member in the set defined by the second and third components.
//
// Examples:
// Example 1: ISO example with only the 2nd and 3rd components valued:
// |^2.16.840.1.113883.19^ISO|
//
// The syntax of the second component is defined by the ISO standard for object identifiers, not by HL7 (for which the second component is of the ST data type).
//
// Thus the periods (".") in the second component are part of the ISO syntax, and are legal by the definition of the HL7 ST data type.
//
// Example 2: A UUID example
// |^478A0114-EBF0-7701-A023-6841FF05731A^UUID|
//
// Example 3: A DNS example
// |^falcon.iupui.edu^DNS|
type HD struct {
	NamespaceId     IS `hl7:"1"`
	UniversalId     ST `hl7:"2"`
	UniversalIdType ID `hl7:"3"`
}

// ICD - Insurance Certification Definition
// This data type specifies whether insurance certification is required for particular patient types, and the time window for obtaining the certification.
//
// Note: Replaces the CM data type used in section 6.5.8.20 IN3-20, as of v2.5.
type ICD struct {
	CertificationPatientType      CWE `hl7:"1"`
	CertificationRequired         ID  `hl7:"2"`
	DateTimeCertificationRequired DTM `hl7:"3"`
}

// ID - Coded Value For Hl7 Defined Tables
// The value of such a field follows the formatting rules for an ST field except that it is drawn from a table of legal values. There shall be an HL7 table number associated with ID data types. An example of an ID field is OBR-25 Result Status. This data type should be used only for HL7 tables (see Chapter 2C, section 2.C.1.2, "HL7 Tables"). The reverse is not true, since in some circumstances it is more appropriate to use the CNE or CWE data type for HL7 tables.
//
// The minimum and maximum lengths are specified in the context in which the ID data type is used. The longest HL7 defined legal value is 15 characters, but there are a few circumstances where the legal values are taken from code systems defined by other bodies (such as IANA mime types). In these cases, a different conformance length may be specified where the ID data type is used. It is never acceptable to truncate an ID value.
type ID string

// IS - Coded Value For User-defined Tables
// As of v2.7, the only approved use of the IS data type is in the HD.1, EI.2 and PL.6 plus a limited number of fields where a determination could not readily be made as to whether the item is an identifier or an actual coded item. Additionally, in accordance with chapter 2 rules, any field or data type component marked as "Retained for backward compatibility" will retain any IS data type.
//
// The value of such a field follows the formatting rules for a ST field except that it is drawn from a site-defined (or user-defined) table of legal values. There shall be an HL7 table number associated with IS data types. An example of an IS field is the Event reason code defined in Chapter 3, "Patient Administration", section 3.4.1.4, "Event reason code". This data type should be used only for user-defined tables (see Chapter 2C, "Code Tables", section 2.C.1.1, "User-defined Tables"). The reverse is not true, since in some circumstances, it is more appropriate to use the CWE data type for user-defined tables.
//
// It is never acceptable to truncate an IS value.
type IS string

// JCC - Job Code/class
// Example 1: Codified job (where 1 represents the code for Administrator and F represents full time)
// |1^F^Administrator|
//
// Example 2: Uncodified job (where job codes are not codified and PT represents part time)
// |^PT^Analyst|.
type JCC struct {
	JobCode            CWE `hl7:"1"`
	JobClass           CWE `hl7:"2"`
	JobDescriptionText TX  `hl7:"3"`
}

// LA1 - Location With Address Variation 1
// Specifies a location and its address.
//
// Note: Replaces the CM data type used in 4.14.1.8 RXO-8 and 4.14.4.8 RXE-8 as of v 2.5. Retained for backward compatibility only as of v 2.5.
//
// Attention: Retained for backward compatibility only in v2.6. Fields associated with this data type have been replaced by 4 new fields in the RXO and RXE segments.
type LA1 struct {
	PointOfCare         IS `hl7:"1"`
	Room                IS `hl7:"2"`
	Bed                 IS `hl7:"3"`
	Facility            HD `hl7:"4"`
	LocationStatus      IS `hl7:"5"`
	PatientLocationType IS `hl7:"6"`
	Building            IS `hl7:"7"`
	Floor               IS `hl7:"8"`
	Address             AD `hl7:"9"`
}

// LA2 - Location With Address Variation 2
// Specifies a location and its address.
//
// Note: Replaces the CM data type used in 4.14.5.13 RXD-13, 4.14.6.11 RXG-11 and 4.14.7.11 RXA-11 as of v 2.5. Retained for backward compatibility only as of v 2.5,
//
// Attention: Retained for backward compatibility only in v2.6. Fields associated with this data type have been replaced by 2 new fields in the RXD, RXG and RXA segments.
type LA2 struct {
	PointOfCare                IS `hl7:"1"`
	Room                       IS `hl7:"2"`
	Bed                        IS `hl7:"3"`
	Facility                   HD `hl7:"4"`
	LocationStatus             IS `hl7:"5"`
	PatientLocationType        IS `hl7:"6"`
	Building                   IS `hl7:"7"`
	Floor                      IS `hl7:"8"`
	StreetAddress              ST `hl7:"9"`
	OtherDesignation           ST `hl7:"10"`
	City                       ST `hl7:"11"`
	StateOrProvince            ST `hl7:"12"`
	ZipOrPostalCode            ST `hl7:"13"`
	Country                    ID `hl7:"14"`
	AddressType                ID `hl7:"15"`
	OtherGeographicDesignation ST `hl7:"16"`
}

// MA - Multiplexed Array
// This data type is used to represent channel-multiplexed waveform data. Assuming that fields that utilize this data type repeat and that Y represents the specific repetition, the components of the repetition will reflect sample Y from each channel.
//
// Usage Note: The MA data type is preferred when the signal recording device outputs the waveform data by time (all signal amplitudes at time sample 1, followed by all signal amplitudes at time sample 2, followed by all signal amplitudes at time sample 3, etc.). The typical count is 32, 64, or 128 channels. At the time of this writing, the MA data type is the one used by most commercial EEG instruments, while other electrophysiological instruments (such as evoked potential instruments) may use the NA data type. The MA data type is the "natural" one for multi-channel EEG instruments since the signal acquisition process involves digitizing each channel in succession as rapidly as possible, then after a fixed interval (like 0.004 seconds) digitizing all the channels again in succession, and repeating this every 0.004 seconds as long as the recording continues.
//
// Use Case: Commercial EEG instruments
//
// Example 1: 3 channels (identical), 6 time-samples
// |0^0^0~1^1^1~2^2^2~3^3^3~4^4^4~5^5^5|
//
// Example 2: 1 channel, 11 time-samples
// |0~1~2~3~4~5~6~7~8~9~10|
type MA struct {
	SampleYFromChannel1 NM `hl7:"1"`
	SampleYFromChannel2 NM `hl7:"2"`
	SampleYFromChannel3 NM `hl7:"3"`
	SampleYFromChannel4 NM `hl7:"4"`
}

// MO - Money
// This data type specifies an amount of money and the denomination in which it is expressed.
type MO struct {
	Quantity     NM `hl7:"1"`
	Denomination ID `hl7:"2"`
}

// MOC - Money And Code
// Transmits monetary information and the associated charge code for services performed.
//
// Note: Replaces the CM data type used in sections 4.5.3.23 OBR-23 and 7.4.1.23- OBR-23 as of v 2.5.
type MOC struct {
	MonetaryAmount MO  `hl7:"1"`
	ChargeCode     CWE `hl7:"2"`
}

// MOP - Money Or Percentage
// This data type specifies an amount that may be either currency or a percentage. It is a variation on the MO data type that is limited to currency.
//
// Note: Replaces the CM data type used in section 6.5.8.5 IN3-5, as of v 2.5. This data type is restricted to this field.
//
// Example: USD is the ISO 4217 code for the U.S. American dollar.
// |AT^99.50^USD|
type MOP struct {
	MoneyOrPercentageIndicator ID `hl7:"1"`
	MoneyOrPercentageQuantity  NM `hl7:"2"`
	MonetaryDenomination       ID `hl7:"3"`
}

// MSG - Message Type
// This field contains the message type, trigger event, and the message structure ID for the message.
//
// Note: Replaces the CM data type used in 2.16.9.9 MSH-9 as of v 2.5.
type MSG struct {
	MessageCode      ID `hl7:"1"`
	TriggerEvent     ID `hl7:"2"`
	MessageStructure ID `hl7:"3"`
}

// NA - Numeric Array
// This data type is used to represent a series (array) of numeric values. A field of this type may contain a one-dimensional array (vector or row) of numbers. Also, by allowing the field to repeat, a two-dimensional array (table) of numbers may be transmitted using this format, with each row of the table represented as one repetition of the field. Arrays that have one or more values not present may be transmitted using this data type. "Not present" values are represented as two adjacent component delimiters. If the absent values occur at the end of a row, the trailing component delimiters may be omitted. If an entire row of a table has no values, no component delimiters are necessary (in this case, there will be two adjacent repetition delimiters).
//
// Example 1: vector of 8 numbers
// |125^34^-22^-234^569^442^-212^6|
//
// Example 2: 3 x 3 array of numbers
// |1.2^-3.5^5.2~2.0^3.1^-6.2~3.5^7.8^-1.3|
//
// Example 3: 5 x 4 array of numbers with the values in positions (1,1), (2,2), (2,3), (3,3), (3,4), (4,1), (4,2), (4,3), and (4,4) not present
// |^2^3^4~5^^^8~9^10~~17^18^19^20|
type NA struct {
	Value1 NM `hl7:"1"`
	Value2 NM `hl7:"2"`
	Value3 NM `hl7:"3"`
	Value4 NM `hl7:"4"`
}

// NDL - Name With Date And Location
// Specifies the name of the person performing a service, when the person performed the service and where the person performed the service. Retained for backward compatibility as of v2.6.
//
// Note: Replaces the CM data type used in sections 4.5.3.32 and 7.4.1.32-( OBR-32), 4.5.3.33 and 7.4.1.33  - ( OBR-33) 4.5.3.34 and 7.4.1.34 - ( OBR-34) 4.5.3.35 and 7.4.1.35 - ( OBR-35) as of v 2.5.
//
// Attention: Retained for backward compatibility only in v2.6. Fields associated with this data type have been replaced by the ROL segment.
type NDL struct {
	Name                CNN `hl7:"1"`
	StartDateTime       DTM `hl7:"2"`
	EndDateTime         DTM `hl7:"3"`
	PointOfCare         IS  `hl7:"4"`
	Room                IS  `hl7:"5"`
	Bed                 IS  `hl7:"6"`
	Facility            HD  `hl7:"7"`
	LocationStatus      IS  `hl7:"8"`
	PatientLocationType IS  `hl7:"9"`
	Building            IS  `hl7:"10"`
	Floor               IS  `hl7:"11"`
}

// NM - Numeric
// Definition: A number represented as a series of ASCII numeric characters consisting of an optional leading sign (+ or -), the digits and an optional decimal point. In the absence of a sign, the number is assumed to be positive. If there is no decimal point the number is assumed to be an integer.
//
// Examples:
// |999|
// |-123.792|
//
// Leading zeros, or trailing zeros after a decimal point, are not significant. For example, the following two values with different representations, “01.20” and “1.2," are identical. Except for the optional leading sign (+ or -) and the optional decimal point (.), no non-numeric ASCII characters are allowed. Thus, the value <12 should be encoded as a structured numeric (SN) (preferred) or as a string (ST) (allowed, but not preferred) data type.
//
// The NM data type does not follow the normal truncation pattern, and the truncation character is never valid in the NM data type. Instead, the truncation behavior is based on the semantics of numbers.
//
// Values of type NM may always have leading zeros truncated. Note that HL7 recommends that leading zeros not be used. Unless NM is used to represent a monetary amount, implementations may truncate trailing zeros after the decimal point up to the first non-zero digit or the decimal point, which ever comes first. Any digits to the left of the decimal point may never be truncated (other than leading zeros).
//
// Example: 1.0200 may be truncated to 1.02, but not to 1.0.
type NM string

// NR - Numeric Range
// Specifies the interval between the lowest and the highest values in a series of data. In the case where a numeric range is unbounded on one side, the component of the unbounded side is null. Whether the end points are included in the range is defined in the usage note for the field.
//
// Note: Replaces the CM data type used in sections 8.8.4.6.1– OM2-6.1, 8.8.4.6.3– OM2-6.3and 8.8.4.6.4– OM2-6.4, as of v 2.5.
type NR struct {
	LowValue  NM `hl7:"1"`
	HighValue NM `hl7:"2"`
}

// OCD - Occurrence Code And Date
// The code and associated date defining a significant event relating to a bill that may affect payer processing.
//
// Note: Replaces the CM data type used in sections 6.5.10.10 UB1-16 and 6.5.11.7 UB2-7, as of v 2.5.
//
// This data type carries data defined by CMS or other regulatory agencies. It corresponds to UB82 Fields 28 32 and UB92 fields 32a, 32b, 33a, 33b, 34a, 34b, 35a, and 35b. Refer to a UB specification for additional information.
//
// Use Case: A Medicare beneficiary was confined in hospital from January 1, 1992 to January 10, 1992, however, his Medicare Part A benefits were exhausted as of January 8, 1992, and he was not entitled to Part B benefits. Therefore, Form Locator 32 should contain code 23 and the date 010892.
//
// Example:
// |23&Benefits Exhausted&NUBC^19920108|
type OCD struct {
	OccurrenceCode CNE `hl7:"1"`
	OccurrenceDate DT  `hl7:"2"`
}

// OSP - Occurrence Span Code And Date
// A code and the related dates that identify an event that relates to the payment of the claim. For example, Prior Stay Dates which is the from/through dates given by the patient of any hospital stay that ended within 60 days of this hospital or SNF admission.
//
// Note: Replaces the CM data type used in section 6.5.11.8 UB2-8, as of v 2.5.
//
// Use case: The patient was admitted for minor surgery (1/6/03) and discharged the following day (1/7/03). Complications ensured and the patient was readmitted the following day (1/8/03). When the claim for 1/8/03 is filed, the prior stay dates (1/6/03-1/7/03) must be reported (per the Health Plan) using Occurrence Span Code and Dates 71 - Prior Stay Date.
//
// Example:
// |71&Prior Stay Date&NUBC^20030106^20030107|
type OSP struct {
	OccurrenceSpanCode      CNE `hl7:"1"`
	OccurrenceSpanStartDate DT  `hl7:"2"`
	OccurrenceSpanStopDate  DT  `hl7:"3"`
}

// PIP - Practitioner Institutional Privileges
// This data type specifies the institutional privileges with associated detail granted to a provider.
//
// Note: Replaces the CM data type used in 15.4.5.7 PRA-7 as of v 2.5.
type PIP struct {
	Privilege      CWE `hl7:"1"`
	PrivilegeClass CWE `hl7:"2"`
	ExpirationDate DT  `hl7:"3"`
	ActivationDate DT  `hl7:"4"`
	Facility       EI  `hl7:"5"`
}

// PL - Person Location
// This data type is used to specify a patient location within a healthcare institution. Which components are valued depends on the needs of the site. For example for a patient treated at home, only the person location type is valued. It is most commonly used for specifying patient locations, but may refer to other types of locations within a healthcare setting.
//
// Note: This data type contains several location identifiers that should be thought of in the following order from the most general to the most specific: facility, building, floor, point of care, room, bed.
//
// Additional data about any location defined by these components can be added in the following components: person location type, location description and location status.
//
// Example: Nursing Unit
// A nursing unit at Community Hospital: 4 East, room 136, bed B
// 4E^136^B^CommunityHospital^^N^^^
//
// Example: Clinic
// A clinic at University Hospitals: Internal Medicine Clinic located in the Briones building, 3rd floor.
// InternalMedicine^^^UniversityHospitals^^C^Briones^3^
type PL struct {
	PointOfCare                     HD `hl7:"1"`
	Room                            HD `hl7:"2"`
	Bed                             HD `hl7:"3"`
	Facility                        HD `hl7:"4"`
	LocationStatus                  IS `hl7:"5"`
	PersonLocationType              IS `hl7:"6"`
	Building                        HD `hl7:"7"`
	Floor                           HD `hl7:"8"`
	LocationDescription             ST `hl7:"9"`
	ComprehensiveLocationIdentifier EI `hl7:"10"`
	AssigningAuthorityForLocation   HD `hl7:"11"`
}

// PLN - Practitioner License Or Other Id Number
// This data type specifies a practitioner’s license number, or other ID number such as UPIN, Medicare and Medicaid number, and associated detail.
//
// Note: Replaces the CM data type used in 15.4.5.6 PRA-6, 11.6.3.7 PRD-7 and 11.6.4.7 CTD-7 as of v 2.5.
type PLN struct {
	IdNumber                        ST  `hl7:"1"`
	TypeOfIdNumber                  CWE `hl7:"2"`
	StateOtherQualifyingInformation ST  `hl7:"3"`
	ExpirationDate                  DT  `hl7:"4"`
}

// PPN - Performing Person Time Stamp
// This data type is the equivalent of an XCN data type joined with a DTM data type. However, the XCN data type has been flattened to allow legal expression of its embedded complex data types HD, CWE and CWE.
type PPN struct {
	PersonIdentifier                            ST  `hl7:"1"`
	FamilyName                                  FN  `hl7:"2"`
	GivenName                                   ST  `hl7:"3"`
	SecondAndFurtherGivenNamesOrInitialsThereof ST  `hl7:"4"`
	SuffixEGJrOrIii                             ST  `hl7:"5"`
	PrefixEGDr                                  ST  `hl7:"6"`
	DegreeEGMd                                  ST  `hl7:"7"`
	SourceTable                                 CWE `hl7:"8"`
	AssigningAuthority                          HD  `hl7:"9"`
	NameTypeCode                                ID  `hl7:"10"`
	IdentifierCheckDigit                        ST  `hl7:"11"`
	CheckDigitScheme                            ID  `hl7:"12"`
	IdentifierTypeCode                          ID  `hl7:"13"`
	AssigningFacility                           HD  `hl7:"14"`
	DateTimeActionPerformed                     DTM `hl7:"15"`
	NameRepresentationCode                      ID  `hl7:"16"`
	NameContext                                 CWE `hl7:"17"`
	NameValidityRange                           ST  `hl7:"18"`
	NameAssemblyOrder                           ID  `hl7:"19"`
	EffectiveDate                               DTM `hl7:"20"`
	ExpirationDate                              DTM `hl7:"21"`
	ProfessionalSuffix                          ST  `hl7:"22"`
	AssigningJurisdiction                       CWE `hl7:"23"`
	AssigningAgencyOrDepartment                 CWE `hl7:"24"`
	SecurityCheck                               ST  `hl7:"25"`
	SecurityCheckScheme                         ID  `hl7:"26"`
}

// PRL - Parent Result Link
// Uniquely identifies the parent result’s OBX segment related to the current order, together with the information in OBR-29 - Parent.
//
// Usage Note: This data type is applied only to OBR-26 - Parent Result where it serves to make information available for other types of linkages (e.g., toxicology). This important information, together with the information in OBR-29 - Parent, uniquely identifies the parent result’s OBX segment related to this order. The value of this OBX segment in the parent result is the organism or chemical species about which this battery reports. For example, if the current battery is an antimicrobial susceptibility, the parent results identified OBX contains a result that identifies the organism on which the susceptibility was run. This indirect linkage is preferred because the name of the organism in the parent result may undergo several preliminary values prior to finalization.
//
// We emphasize that this field does not take the entire result field from the parent. It is meant only for the text name of the organism or chemical subspecies identified. This field is included only to provide a method for linking back to the parent result for those systems that could not generate unambiguous Observation IDs and sub-IDs.
// This field is present only when the parent result is identified by OBR-29 - Parent and the parent spawns child orders for each of many results. See Chapter 7, "Observations", for more details about this linkage.
//
// Note: Replaces the CM data type used in sections 4.5.3.26 - OBR-26 and 7.4.1.26 - OBR-26 as of v 2.5.
type PRL struct {
	ParentObservationIdentifier      CWE `hl7:"1"`
	ParentObservationSubIdentifier   ST  `hl7:"2"`
	ParentObservationValueDescriptor TX  `hl7:"3"`
}

// PT - Processing Type
// This data type indicates whether to process a message as defined in HL7 Application (level 7) Processing rules.
type PT struct {
	ProcessingId   ID `hl7:"1"`
	ProcessingMode ID `hl7:"2"`
}

// PTA - Policy Type And Amount
// This data type specifies the policy type and amount covered by the insurance.
//
// Note: Replaces the CM data type used in section 6.5.7.29 IN2-29, as of v 2.5.
type PTA struct {
	PolicyType                CWE `hl7:"1"`
	AmountClass               CWE `hl7:"2"`
	MoneyOrPercentageQuantity ST  `hl7:"3"`
	MoneyOrPercentage         MOP `hl7:"4"`
}

// QIP - Query Input Parameter List
// This data type contains a segment field name and the list of values to be passed to the query processor.
//
// Example:
// |@PID.5.1^EVANS|
type QIP struct {
	SegmentFieldName ST `hl7:"1"`
	Values           ST `hl7:"2"`
}

// QSC - Query Selection Criteria
// This field indicates the conditions that qualify the rows to be returned in the query response. Note that this field conveys the same information as the "WHERE" clause in the corresponding SQL expression of the query, but is formatted differently.
//
// Example:
// |@PID.5.1^EQ^EVANS|
type QSC struct {
	SegmentFieldName      ST `hl7:"1"`
	RelationalOperator    ID `hl7:"2"`
	Value                 ST `hl7:"3"`
	RelationalConjunction ID `hl7:"4"`
}

// RCD - Row Column Definition
// This specifies the format of a column in terms of a segment field name, a data type, and a maximum length.
//
// Example: This defines a column containing the value of the "last name" component of PID-5, expressed as a ST data type with a maximum width of 20.
// |@PID.5.1^ST^20|
type RCD struct {
	SegmentFieldName   ST `hl7:"1"`
	Hl7DataType        ID `hl7:"2"`
	MaximumColumnWidth NM `hl7:"3"`
}

// RFR - Reference Range
// Describes a reference range and its supporting detail.
//
// Note: Replaces the CM data type used in sections 8.8.4.6 - OM2-6, 8.8.4.7 - OM2-7 and 8.8.4.8 - OM2-8 as of v 2.5.
//
// Examples:
// A range that applies unconditionally, such as albumin, is transmitted as:
// |3.0&5.5|
//
// A normal range that depends on sex, such as Hgb, is transmitted as:
// |13.5&18^M~12.0 & 16^F|
//
// A normal range that depends on age, sex, and race (a concocted example) is:
// |10&13^M^0&2^^^B11&13.5^M^2&20^^^B~12&14.5^M^20&70^^^B~13&16.0^M^70&^^^B|
//
// When no value is specified for a particular component, the range given applies to all categories of that component. For example, when nothing is specified for race/species, the range should be taken as the human range without regard to race. If no age range is specified, the normal range given is assumed to apply to all ages.
type RFR struct {
	NumericRange        NR  `hl7:"1"`
	AdministrativeSex   CWE `hl7:"2"`
	AgeRange            NR  `hl7:"3"`
	GestationalAgeRange NR  `hl7:"4"`
	Species             ST  `hl7:"5"`
	RaceSubspecies      ST  `hl7:"6"`
	Conditions          TX  `hl7:"7"`
}

// RI - Repeat Interval
// contains the interval between repeated services.
//
// Note: The reader is referred to the RPT – Repeat pattern data type, which provides a more rigorous framework for defining repeating time intervals.
type RI struct {
	RepeatPattern        CWE `hl7:"1"`
	ExplicitTimeInterval ST  `hl7:"2"`
}

// RMC - Room Coverage
// This data type specifies insurance coverage detail for a room.
//
// Note: Replaces the CM data type used in section 6.5.7.28 IN2-28, as of v 2.5.
type RMC struct {
	RoomType          CWE `hl7:"1"`
	AmountType        CWE `hl7:"2"`
	CoverageAmount    ST  `hl7:"3"`
	MoneyOrPercentage MOP `hl7:"4"`
}

// RP - Reference Pointer
// This data type transmits information about data stored on another system. It contains a reference pointer that uniquely identifies the data on the other system, the identity of the other system, and the type of data.
type RP struct {
	Pointer       ST `hl7:"1"`
	ApplicationId HD `hl7:"2"`
	TypeOfData    ID `hl7:"3"`
	Subtype       ID `hl7:"4"`
}

// RPT - Repeat Pattern
// The repeat pattern data type should be used where it is necessary to define the frequency at which an event is to take place. This data type provides a way to define repeat pattern codes "on the fly". The repeat pattern code is equivalent to the TQ data type, component 2, sub-component 1 (repeat pattern). The additional components define the meaning of the repeat pattern code. Components 2 - 10 are used to define relatively simple repeat patterns. Component 11 is provided to define complex repeat patterns. This data type forms a bridge between the 2.x Repeat Pattern concept from Quantity/Timing, and the Version 3.0 GTS General Timing Specification. Component 1 is the 2.x concept of repeat pattern. Components 2-7 are derived from the version 3.0 data type PIVL. Components 8-10 are derived from the version 3.0 EIVL data type. If a repeat pattern cannot be defined using components 2-10, then component 11, General Timing Specification is provided. This allows the full literal form of the version 3.0 GTS to be specified.
//
// When using the RPT, if an application doesn't recognize the code in component 1, then it may attempt to determine the appropriate frequency using the remaining components. If the application does recognize the code in component 1, the application is not required to determine the frequency from the remaining components.
// Use Case: The use case supporting this proposal is the need to define repeat patterns on the fly while placing an order. The TQ data type did not have the capability to define the meaning of a repeat pattern on the fly. To get around this problem, vendors have implemented a variety of solutions to solve this issue. One way was to add Z-components to the TQ data type to transmit information about the repeat pattern. Another solution was to attempt to parse the repeat pattern code in an attempt to decipher what the code meant.
//
// Examples:
// |Q1H&Every 1 Hour&HL7xxx^^^^1^h|
// |Q2J2&Every second Tuesday&HL7xxx^DW^2^^2^wk|
// |BID&Twice a day at institution specified times&HL7xxx^^^^12^h^Y|
// |QAM&Every morning at the institution specified time&HL7xxx^HD^00^11^1^d^Y|
// |QHS&Every day before the hours of sleep&HL7xxx^^^^1^d^^AHS|
// |ACM&Before Breakfast&HL7xxx^^^^^^^ACM|
type RPT struct {
	RepeatPatternCode          CWE `hl7:"1"`
	CalendarAlignment          ID  `hl7:"2"`
	PhaseRangeBeginValue       NM  `hl7:"3"`
	PhaseRangeEndValue         NM  `hl7:"4"`
	PeriodQuantity             NM  `hl7:"5"`
	PeriodUnits                CWE `hl7:"6"`
	InstitutionSpecifiedTime   ID  `hl7:"7"`
	Event                      ID  `hl7:"8"`
	EventOffsetQuantity        NM  `hl7:"9"`
	EventOffsetUnits           CWE `hl7:"10"`
	GeneralTimingSpecification GTS `hl7:"11"`
}

// SAD - Street Address
// This data type specifies an entity's street address and associated detail.
// Note: Appears ONLY in the XAD data type
type SAD struct {
	StreetOrMailingAddress ST `hl7:"1"`
	StreetName             ST `hl7:"2"`
	DwellingNumber         ST `hl7:"3"`
}

// SCV - Scheduling Class Value Pair
// This data type is used to communicate parameters and preferences to the filler application regarding the selection of an appropriate time slot, resource, location, or filler override criterion for an appointment.
//
// For use only with the scheduling chapter.
type SCV struct {
	ParameterClass CWE `hl7:"1"`
	ParameterValue ST  `hl7:"2"`
}

// SI - Sequence Id
// A non-negative integer in the form of a NM field. The uses of this data type are defined in the chapters defining the segments and messages in which it appears.
//
// This allows for a number between 0 and 9999 to be specified.
type SI string

// SN - Structured Numeric
// The structured numeric data type is used to unambiguously express numeric clinical results along with qualifications. This enables receiving systems to store the components separately, and facilitates the use of numeric database queries. The corresponding sets of values indicated with the <comparator> and <separator/suffix> components are intended to be the authoritative and complete set of values. If additional values are needed for the <comparator> and <separator/suffix> components, they should be submitted to HL7 for inclusion in the Standard.
//
// If <num1> and <num2> are both non-null, then the separator/suffix must be non-null. If the separator is "-", the data range is inclusive; e.g., <num1> - <num2> defines a range of numbers x, such that: <num1> <=x<= <num2>.
type SN struct {
	Comparator      ST `hl7:"1"`
	Num1            NM `hl7:"2"`
	SeparatorSuffix ST `hl7:"3"`
	Num2            NM `hl7:"4"`
}

// SNM - String Of Telephone Number Digits
// :A string whose characters are limited to "+" and/or the decimal digits 0  through 9.  As a string, leading zeros are always considered significant.
//
// Used only in the XTN data type as of v2.7.
//
// SNM is used for telephone numbers, so it is never appropriate to truncate values of type SNM.
type SNM string

// SPD - Specialty Description
// This data type specifies the practitioner’s specialty and related information.
//
// Note: Replaces the CM data type used in 15.4.5.5 PRA-5 as of v 2.5.
type SPD struct {
	SpecialtyName       ST `hl7:"1"`
	GoverningBoard      ST `hl7:"2"`
	EligibleOrCertified ID `hl7:"3"`
	DateOfCertification DT `hl7:"4"`
}

// SRT - Sort Order
// Specifies those parameters by which the response will be sorted and by what method.
//
// Example: In a tabular response query, where the return data is known by column name, the SRT might look like:
// |LastName^A~FirstName^A|
//
// Example: In a segment response query, where the return data is known by segment and offset, the SRT field would use segment field name notation:
// |PID.3.1^A~PID.3.2|
type SRT struct {
	SortByField ST `hl7:"1"`
	Sequencing  ID `hl7:"2"`
}

// ST - String Data
// The String data type is used for text data when the appearance of text does not bear meaning. This is true for formalized text, symbols and formal expressions, and all kinds of names intended for machine processing (e.g., sorting, querying, indexing, etc.).
//
// String data is left justified (i.e., no leading blank space) with trailing blanks optional. Any displayable (printable) ACSII characters (hexadecimal values between 20 and 7E, inclusive, or ASCII decimal values between 32 and 126), except the defined escape characters and defined delimiter characters.
//
// Example 1: A textual ST field:
// |almost any data at all|
//
// To include any HL7 delimiter character (except the segment terminator) within a string data field, use the appropriate HL7 escape sequence (see Section 2.7.1, "Formatting Codes”).
//
// ST has no inbuilt semantics – these are assigned where the ST is used. In each case where ST is used, minimum, maximum, and conformance lengths may be specified.  Unless specified in the context of use, values of type ST may not be truncated.
//
// Usage note: The ST data type is intended for short strings (e.g., less than 1000 characters). For longer strings the TX or FT data types should be used (see Sections 2.A.79, “TX - text data” or 2.A.31, “FT - formatted text data”).
//
// Alternate character set note: ST - string data may also be used to express other character sets. See Section 2.15.9.18, "Character set," and Section 2.15.9.20, "Alternate character set handling" for details.
type ST string

// TM - Time
// Specifies the hour of the day with optional minutes, seconds, fraction of second using a 24-hour clock notation and time zone.
//
// As of v 2.3, the number of characters populated (excluding the time zone specification) specifies the precision.
//
// Format: HH[MM[SS[.S[S[S[S]]]]]][+/-ZZZZ]
//
// Example: |0630| specifies 6: 30 AM.
//
// The fractional seconds could be sent by a transmitter who requires greater precision than whole seconds. Fractional representations of minutes, hours or other higher-order units of time are not permitted.
//
// Note: The time zone [+/-ZZZZ], when used, is restricted to legally-defined time zones and is represented in HHMM format.
//
// Prior to v 2.3, this data type was specified in the format HHMM[SS[.SSSS]][+/-ZZZZ]. As of v 2.3 minutes are no longer required. By site-specific agreement, HHMM[SS[.SSSS]][+/-ZZZZ] may be used where backward compatibility must be maintained.This corresponds a minimum length of 4.
//
// The TM data type does not follow the normal truncation pattern, and the truncation character is never valid in the TM data type. Instead, the truncation behavior is based on the semantics of times.
//
// Unless otherwise specified in the context where the DTM type is used, the DTM type may be truncated to a particular minute. When a TM is truncated, the truncated form SHALL still be a valid TM type. Refer to Chapter 2, section 2.5.5.2, "Truncation Pattern", for further information.
type TM string

// TX - Text Data
// String data meant for user display (on a terminal or printer). Such data would not necessarily be left justified since leading spaces may contribute greatly to the clarity of the presentation to the user. Because this type of data is intended for display, it may contain certain escape character sequences designed to control the display. Escape sequence formatting is defined in Section 2.7, "Use of escape sequences in text fields". Leading spaces should be included. Trailing spaces should be removed.
//
// Example:
// |  leading spaces are allowed.|
//
// Since TX data is intended for display purposes, the repeat delimiter, when used with a TX data field, implies a series of repeating lines to be displayed on a printer or terminal. Therefore, the repeat delimiters are regarded as paragraph terminators or hard carriage returns (e.g., they would display as though a CR/LF were inserted in the text (DOS type system) or as though a LF were inserted into the text (UNIX style system)).
//
// A receiving system would word wrap the text between repeat delimiters in order to fit it into an arbitrarily sized display window but start any line beginning with a repeat delimiter on a new line.
//
// To include alternative character sets, use the appropriate escape sequence. See Chapter 2, section 2.14.9.18, "MSH-18 - Character Set" and section 2.14.9.20, "MSH-20 - Alternate Character Set Handling Scheme".
//
// This specification applies no limit to the length of the TX data type, either here where the data type is defined, or elsewhere where the data type is used. While there is no intrinsic reason to limit the length of this data type for semantic or syntactical reasons, it is expected that some sort of limitation will be imposed for technical reasons in implementations. HL7 recommends that implementation length limits be published in implementation profiles.
type TX string

// UVC - Ub Value Code And Amount
// A code structure to relate amounts or values to identified data elements necessary to process this claim as qualified by the payer organization.
//
// This data type is used to convey information defined by CMS or other regulatory agencies. It corresponds to UB fields 46A, 47A, 48A, 49A, 46B, 47B, 48B, and 49B and UB92 fields 39a, 39b, 39c, 39d, 40a, 40b, 40c, 40d, 41a, 41b, 41c, and 41d.
//
// Note: Replaces the CM data type used in sections 6.5.10.10 UB1-10 and 6.5.11.6 UB2-6, as of v 2.5.
//
// The most common semi-private room rate is used in instances where the patient is placed in a private room at their request but their insurance only covers a semi-private room rate, which can be calculated using the 01-most common semi-private room rate.
//
// Example:
// |01&most common semi private rate&NUBC^750&USD|
type UVC struct {
	ValueCode                      CWE `hl7:"1"`
	ValueAmount                    MO  `hl7:"2"`
	NonMonetaryValueAmountQuantity NM  `hl7:"3"`
	NonMonetaryValueAmountUnits    CWE `hl7:"4"`
}

// VH - Visiting Hours
// This data type contains the hours when a patient location is open for visiting. Refer to HL7 Table 0267 - Days of the Week for valid values for the first two components.
type VH struct {
	StartDayRange  ID `hl7:"1"`
	EndDayRange    ID `hl7:"2"`
	StartHourRange TM `hl7:"3"`
	EndHourRange   TM `hl7:"4"`
}

// VID - Version Identifier
type VID struct {
	VersionId                ID  `hl7:"1"`
	InternationalizationCode CWE `hl7:"2"`
	InternationalVersionId   CWE `hl7:"3"`
}

// VR - Value Range
// This data type contains the lower bound value and upper bound values that constitute a range. Either or both components may be populated.
// Note: Replaces the CM data type used in 5.10.5.3.11 QRD-11 as of v 2.5.
//
// The VR differs from the Numeric Range (NR) data type only in that the values are not restricted to numbers. If the range is not numeric, the set must be orderable in some intuitive way such as alpha or the order must be defined in the field where the data type is used.
//
// Example 1:
// |+^+++|
//
// Example 2: Colors of the rainbow
// |violet^red|
type VR struct {
	FirstDataCodeValue ST `hl7:"1"`
	LastDataCodeValue  ST `hl7:"2"`
}

// WVI - Channel Identifier
// This data type specifies the number and name of the recording channel where waveform data is transmitted.
//
// Note: Replaces the CM data type used in 7.14.1.3.1 OBX-5.1 where OBX-5 Observation value (*) is data type CD as of v 2.5.
//
// Attention: Retained for backward compatibility only in v 2.7.  This is used only in the CD Channel Definition data type, which has been retained for backward compatibility only in v2.7.
type WVI struct {
	ChannelNumber NM `hl7:"1"`
	ChannelName   ST `hl7:"2"`
}

// WVS - Waveform Source
// This data type identifies the source of the waveform connected to a channel.
//
// Note: Replaces the CM data type used in 7.14.1.4 OBX-5.2 where OBX-5 Observation value (*) is data type CD as of v 2.5.
//
// Attention: Retained for backward compatibility only in v2.7.  It is used only in the CD Channel Definition data type, which has been retained for backward compatibility only in v2.7.
type WVS struct {
	SourceOneName ST `hl7:"1"`
	SourceTwoName ST `hl7:"2"`
}

// XAD - Extended Address
// This data type specifies the address of a person, place or organization plus associated information.
//
// Note: Replaces the AD data type as of v2.3.
//
// Example of usage for US:
// |1000 Hospital Lane^Ste. 123^Ann Arbor ^MI^99999^USA^B^^WA^|
//
// This would be formatted for postal purposes as
// 1000 Hospital Lane
// Ste. 123
// Ann Arbor MI 99999
type XAD struct {
	StreetAddress              SAD `hl7:"1"`
	OtherDesignation           ST  `hl7:"2"`
	City                       ST  `hl7:"3"`
	StateOrProvince            ST  `hl7:"4"`
	ZipOrPostalCode            ST  `hl7:"5"`
	Country                    ID  `hl7:"6"`
	AddressType                ID  `hl7:"7"`
	OtherGeographicDesignation ST  `hl7:"8"`
	CountyParishCode           CWE `hl7:"9"`
	CensusTract                CWE `hl7:"10"`
	AddressRepresentationCode  ID  `hl7:"11"`
	AddressValidityRange       ST  `hl7:"12"`
	EffectiveDate              DTM `hl7:"13"`
	ExpirationDate             DTM `hl7:"14"`
	ExpirationReason           CWE `hl7:"15"`
	TemporaryIndicator         ID  `hl7:"16"`
	BadAddressIndicator        ID  `hl7:"17"`
	AddressUsage               ID  `hl7:"18"`
	Addressee                  ST  `hl7:"19"`
	Comment                    ST  `hl7:"20"`
	PreferenceOrder            NM  `hl7:"21"`
	ProtectionCode             CWE `hl7:"22"`
	AddressIdentifier          EI  `hl7:"23"`
}

// XCN - Extended Composite Id Number And Name For Persons
// Note: Replaces CN data type as of v 2.3.
//
// This data type is used extensively appearing in the PV1, ORC, RXO, RXE, OBR and SCH segments, as well as others, where there is a need to specify the ID number and name of a person.
//
// Example without assigning authority and assigning facility:
// |1234567^Everyman^Adam^A^III^DR^PHD^ADT01^^L^4^M11^MR|
//
// Examples with assigning authority and assigning facility:
//
// Dr. Harold Hippocrates’ provider ID was assigned by the Provider Master and was first issued at Good Health Hospital within the Community Health and Hospitals System. Since IS table values (first component of the HD) were not used for assigning authority and assigning facility, components 2 and 3 of the HD data type are populated and demoted to sub-components as follows:
// 12188^Hippocrates^Harold^H^IV^Dr^MD^^&Provider Master.Community Health and Hospitals&L^L^9^M10^DN^&Good Health Hospital.Community Health and Hospitals&L^A
//
// Ludwig van Beethoven's medical record number was assigned by the Master Patient Index and was first issued at Fairview Hospital within the University Hospitals System.
// 10535^van Beethoven&van^Ludwig^A^III^Dr^PHD^^&MPI.Community Health and Hospitals&L^L^3^M10^MR^& Good Health Hospital.Community Health and Hospitals&L^A
type XCN struct {
	PersonIdentifier                            ST  `hl7:"1"`
	FamilyName                                  FN  `hl7:"2"`
	GivenName                                   ST  `hl7:"3"`
	SecondAndFurtherGivenNamesOrInitialsThereof ST  `hl7:"4"`
	SuffixEGJrOrIii                             ST  `hl7:"5"`
	PrefixEGDr                                  ST  `hl7:"6"`
	DegreeEGMd                                  ST  `hl7:"7"`
	SourceTable                                 CWE `hl7:"8"`
	AssigningAuthority                          HD  `hl7:"9"`
	NameTypeCode                                ID  `hl7:"10"`
	IdentifierCheckDigit                        ST  `hl7:"11"`
	CheckDigitScheme                            ID  `hl7:"12"`
	IdentifierTypeCode                          ID  `hl7:"13"`
	AssigningFacility                           HD  `hl7:"14"`
	NameRepresentationCode                      ID  `hl7:"15"`
	NameContext                                 CWE `hl7:"16"`
	NameValidityRange                           ST  `hl7:"17"`
	NameAssemblyOrder                           ID  `hl7:"18"`
	EffectiveDate                               DTM `hl7:"19"`
	ExpirationDate                              DTM `hl7:"20"`
	ProfessionalSuffix                          ST  `hl7:"21"`
	AssigningJurisdiction                       CWE `hl7:"22"`
	AssigningAgencyOrDepartment                 CWE `hl7:"23"`
	SecurityCheck                               ST  `hl7:"24"`
	SecurityCheckScheme                         ID  `hl7:"25"`
}

// XON - Extended Composite Name And Identification Number For Organizations
// This data type is used in fields (e.g., PV2-23, NK1-13, PD1-3, OBR-44) to specify the name and ID number of an organization.
//
// Example 1:
// The ID for Good Health Hospital was assigned by the Community Health and Hospitals enterprise’s Hospital Master and was first issued at the Central Offices.
// Good Health Hospital^L^716^9^M10^&Hospital Master.Community Health and Hospitals&L^XX^&Central Offices.Community Health and Hospitals&L^A
//
// Example 2:
// Good Health Hospital has another ID that was issued by CMS. Assigning Authority, CMS, values only the first HD component, an IS data type and assigning facility is not relevant. This information might be transmitted accordingly:
// Good Health Hospital^L^4544^3^M10^CMS^XX^^A
type XON struct {
	OrganizationName         ST  `hl7:"1"`
	OrganizationNameTypeCode CWE `hl7:"2"`
	IdNumber                 ST  `hl7:"3"`
	IdentifierCheckDigit     NM  `hl7:"4"`
	CheckDigitScheme         ID  `hl7:"5"`
	AssigningAuthority       HD  `hl7:"6"`
	IdentifierTypeCode       ID  `hl7:"7"`
	AssigningFacility        HD  `hl7:"8"`
	NameRepresentationCode   ID  `hl7:"9"`
	OrganizationIdentifier   ST  `hl7:"10"`
}

// XPN - Extended Person Name
// Note: Replaces PN data type as of v 2.3.
//
// Example 1: Adam A. Everyman III PhD
// |Everyman^Adam^A^III^DR^^L^^^^^^^PHD|
//
// Example 2: Ludwig van Beethoven
// |Beethoven&van^Ludwig^^^^^L|
//
// Example 3: Hermann Egon Mayer zur alten Schildesche
// |Mayer^Hermann^Egon^zur alten Schildesche|
type XPN struct {
	FamilyName                                  FN  `hl7:"1"`
	GivenName                                   ST  `hl7:"2"`
	SecondAndFurtherGivenNamesOrInitialsThereof ST  `hl7:"3"`
	SuffixEGJrOrIii                             ST  `hl7:"4"`
	PrefixEGDr                                  ST  `hl7:"5"`
	DegreeEGMd                                  ST  `hl7:"6"`
	NameTypeCode                                ID  `hl7:"7"`
	NameRepresentationCode                      ID  `hl7:"8"`
	NameContext                                 CWE `hl7:"9"`
	NameValidityRange                           ST  `hl7:"10"`
	NameAssemblyOrder                           ID  `hl7:"11"`
	EffectiveDate                               DTM `hl7:"12"`
	ExpirationDate                              DTM `hl7:"13"`
	ProfessionalSuffix                          ST  `hl7:"14"`
	CalledBy                                    ST  `hl7:"15"`
}

// XTN - Extended Telecommunication Number
// Example 1: A Work fax number
// ^WPN^FX^^^734^6777777
//
// Example 2: Telephone number with extension
// ^WPN^PH^^^734^6777777^1
//
// Example 4: home e-mail address. In this example, assume that a person has a primary home e-mail address such as someone@somewhere.com.  The components would be:
// ^PRN^Internet^someone@somewhere.com
type XTN struct {
	TelephoneNumber                   ST  `hl7:"1"`
	TelecommunicationUseCode          ID  `hl7:"2"`
	TelecommunicationEquipmentType    ID  `hl7:"3"`
	CommunicationAddress              ST  `hl7:"4"`
	CountryCode                       SNM `hl7:"5"`
	AreaCityCode                      SNM `hl7:"6"`
	LocalNumber                       SNM `hl7:"7"`
	Extension                         SNM `hl7:"8"`
	AnyText                           ST  `hl7:"9"`
	ExtensionPrefix                   ST  `hl7:"10"`
	SpeedDialCode                     ST  `hl7:"11"`
	UnformattedTelephoneNumber        ST  `hl7:"12"`
	EffectiveStartDate                DTM `hl7:"13"`
	ExpirationDate                    DTM `hl7:"14"`
	ExpirationReason                  CWE `hl7:"15"`
	ProtectionCode                    CWE `hl7:"16"`
	SharedTelecommunicationIdentifier EI  `hl7:"17"`
	PreferenceOrder                   NM  `hl7:"18"`
}

// varies - Varies
type varies string
