// Code generated by gen_hl7v2. DO NOT EDIT.

package v22

// ACK - General acknowledgement
// The simple general acknowledgement (ACK) can be used where the application does not define a special application level acknowledgement message or where there has been an error that precludes application processing.  It is also used for accept level acknowlegements.
type ACK struct {
	MSH MSH `hl7:"MSH,required"`
	MSA MSA `hl7:"MSA,required"`
	ERR ERR `hl7:"ERR"`
}

type ADR_A19_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

type ADR_A19_QUERYRESPONSE struct {
	EVN       EVN                 `hl7:"EVN"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADR_A19_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// ADR_A19 - Patient query
// The following trigger event is served by QRY (a query from another system) and ADR (a response from an Patient Administration system.)
//
// Another application determines a need for Patient Administration data about a patient and sends a query to the Patient Administration system.  The Who Filter in the QRD can identify the patient or account number upon which the query is defined and can contain a format code of “R” (record-oriented).  If the query is based on the Patient ID and there are data associated with multiple accounts, the problem of which account data should be returned becomes an implementation issue.  The ADT event-type segment, if included in the response, describes the last event for which the Patient Administration system initiated an unsolicited update
type ADR_A19 struct {
	MSH           MSH                     `hl7:"MSH,required"`
	MSA           MSA                     `hl7:"MSA,required"`
	ERR           ERR                     `hl7:"ERR"`
	QRD           QRD                     `hl7:"QRD,required"`
	QUERYRESPONSE []ADR_A19_QUERYRESPONSE `hl7:"QUERY RESPONSE,required"`
	DSC           DSC                     `hl7:"DSC"`
}

type ADT_A01_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A01 - Admit a Patient
// Normally entered in the primary ADT system and broadcast to the nursing units and ancillary systems.  Includes short-stay and John Doe admissions
type ADT_A01 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A01_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// ADT_A02 - Transfer a patient
// A patient moves from one location to another
type ADT_A02 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A03 - Discharge a patient
// Refers to changing a patient's status from, for example, inpatient to discharged
type ADT_A03 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

type ADT_A04_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A04 - Register a Patient
// Includes emergency room patients and outpatients
type ADT_A04 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A04_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

type ADT_A05_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A05 - Pre-admit a Patient
// A patient may be pre-admitted for a variety of reasons; e.g., prior to surgery so that they will be able to receive tests administered in the lab.  The data may be entered into the surgery scheduling system and passed to the ADT system
type ADT_A05 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A05_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

type ADT_A06_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A06 - Transfer an Outpatient to Inpatient
type ADT_A06 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	MRG       MRG                 `hl7:"MRG"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A06_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

type ADT_A07_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A07 - Transfer an Inpatient to Outpatient
type ADT_A07 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	MRG       MRG                 `hl7:"MRG"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A07_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

type ADT_A08_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A08 - Update Patient Information
// This trigger event is used when any patient information has changed, but no other trigger event has occurred
type ADT_A08 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A08_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// ADT_A09 - Patient Departing
// A patient is being moved from his assigned location to a new location.  For example, this can be used when the nursing system is not the same as the ADT system or to indicate a patient leaving an outpatient bed.  The DG1 segment remains in this message for backwards compatibility only.
type ADT_A09 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	DG1 []DG1 `hl7:"DG1"`
}

// ADT_A10 - Patient Arriving
// The patient arrives at his new assigned location
type ADT_A10 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	DG1 []DG1 `hl7:"DG1"`
}

// ADT_A11 - Cancel Admit
type ADT_A11 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	DG1 []DG1 `hl7:"DG1"`
}

// ADT_A12 - Cancel Transfer
// New location must show the location of the patient prior to the transfer
type ADT_A12 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	DG1 []DG1 `hl7:"DG1"`
}

type ADT_A13_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A13 - Cancel Discharge
// New location must show the location of the patient prior to the discharge
type ADT_A13 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A13_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

type ADT_A14_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A14 - Pending Admit
// Reservation or when patient admission is to occur imminently.  Similar to a pre-admit
type ADT_A14 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A14_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// ADT_A15 - Pending Transfer
type ADT_A15 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	DG1 []DG1 `hl7:"DG1"`
}

// ADT_A16 - Pending Discharge
type ADT_A16 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	DG1 []DG1 `hl7:"DG1"`
}

// ADT_A17 - Swap Patients
// Used when it is decided that two patients will exchange beds.  The patient ID and visit data are repeated for the two patients being swapped.  See Section 3.5.1 for a discussion of issues related to implementing this trigger event.
type ADT_A17 struct {
	MSH  MSH   `hl7:"MSH,required"`
	EVN  EVN   `hl7:"EVN,required"`
	PID  PID   `hl7:"PID,required"`
	PV1  PV1   `hl7:"PV1,required"`
	PV2  PV2   `hl7:"PV2"`
	OBX  []OBX `hl7:"OBX"`
	PID2 PID   `hl7:"PID,required"`
	PV12 PV1   `hl7:"PV1,required"`
	PV22 PV2   `hl7:"PV2"`
	OBX2 []OBX `hl7:"OBX"`
}

// ADT_A18 - Merge Patient Information
// Used to merge current and previous patient identification numbers:  patient ID - internal, patient ID - external, alternate patient ID and patient account number.  This is required, for example, when a patient has previously been registered under a new patient identification number because of an error or because there was insufficient time to determine the actual patient identification number.  The merge event occurs when the decision is made to combine the information under either the new or old identifier(s).  It is recommended that events A34, A35 and A36 be utilized in place of the A18 event whenever possible.  [Event A18 is being kept for backwards compatibility.]
//
// The PID segment contains the surviving patient ID information.  The MRG segment contains the non-surviving information.
type ADT_A18 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	MRG MRG `hl7:"MRG"`
	PV1 PV1 `hl7:"PV1,required"`
}

// ADT_A20 - Bed Status Update
// Certain nursing/census applications need to be able to update the ADT system's bed status.  The following is the associated record layout
type ADT_A20 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	NPU NPU `hl7:"NPU,required"`
}

// ADT_A21 - A Patient Goes On A "Leave Of Absence"
type ADT_A21 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A22 - A Patient Returns From A "Leave Of Absence"
type ADT_A22 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A23 - Delete a Patient Record
// Delete visit specific information
type ADT_A23 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A24 - Link Patient Information
// Where the first PID segment needs to be linked to the second PID segment.  See Section 3.5.3 for a discussion of issues related to implementing patient link messages
type ADT_A24 struct {
	MSH  MSH `hl7:"MSH,required"`
	EVN  EVN `hl7:"EVN,required"`
	PID  PID `hl7:"PID,required"`
	PV1  PV1 `hl7:"PV1"`
	PID2 PID `hl7:"PID,required"`
	PV12 PV1 `hl7:"PV1"`
}

// ADT_A25 - Cancel Pending Discharge
type ADT_A25 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A26 - Cancel Pending Transfer
type ADT_A26 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A27 - Cancel Pending Admit
type ADT_A27 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

type ADT_A28_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A28 - Add person information
// The purpose of this message and the three following messages is to allow sites with multiple systems and respective master data bases to communicate activity related to a person between systems.  Each system has an interest in the data base activity of the others in order to maintain data integrity across an institution.  While defined within the ADT message set, these messages differ in that they are not patient specific.
type ADT_A28 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A28_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// ADT_A29 - Delete person information
// Delete all demographic information related to this person
type ADT_A29 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A30 - Merge Patient information
type ADT_A30 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	MRG MRG `hl7:"MRG,required"`
}

type ADT_A31_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

// ADT_A31 - Update person information
type ADT_A31 struct {
	MSH       MSH                 `hl7:"MSH,required"`
	EVN       EVN                 `hl7:"EVN,required"`
	PID       PID                 `hl7:"PID,required"`
	NK1       []NK1               `hl7:"NK1"`
	PV1       PV1                 `hl7:"PV1,required"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	INSURANCE []ADT_A31_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// ADT_A32 - Cancel patient arriving
type ADT_A32 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A33 - Cancel patient departing
type ADT_A33 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1,required"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
}

// ADT_A34 - patient ID only
// Only Patient Identification - Internal has changed as a result of the merge.  See Section 3.5.2 for a discussion of issues related to implementing merge messages
type ADT_A34 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	MRG MRG `hl7:"MRG,required"`
}

// ADT_A35 - account number only
// Only Patient Account Number has changed as a result of the merge.  See Section 3.5.2 for a discussion of issues related to implementing merge messages
type ADT_A35 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	MRG MRG `hl7:"MRG,required"`
}

// ADT_A36 - pat ID and account number
// Both Patient Identification - Internal and Patient Account Number have changed as a result of the merge.  See Section 3.5.2 for a discussion of issues related to implementing merge messages
type ADT_A36 struct {
	MSH MSH `hl7:"MSH,required"`
	EVN EVN `hl7:"EVN,required"`
	PID PID `hl7:"PID,required"`
	MRG MRG `hl7:"MRG,required"`
}

// ADT_A37 - unlink patient information
// Unlinks two PID segments previously linked via an A24.
type ADT_A37 struct {
	MSH  MSH `hl7:"MSH,required"`
	EVN  EVN `hl7:"EVN,required"`
	PID  PID `hl7:"PID,required"`
	PV1  PV1 `hl7:"PV1"`
	PID2 PID `hl7:"PID,required"`
	PV12 PV1 `hl7:"PV1"`
}

type BAR_P01_INSURANCE struct {
	IN1 IN1 `hl7:"IN1,required"`
	IN2 IN2 `hl7:"IN2"`
	IN3 IN3 `hl7:"IN3"`
}

type BAR_P01_VISIT struct {
	PV1       PV1                 `hl7:"PV1"`
	PV2       PV2                 `hl7:"PV2"`
	OBX       []OBX               `hl7:"OBX"`
	AL1       []AL1               `hl7:"AL1"`
	DG1       []DG1               `hl7:"DG1"`
	PR1       []PR1               `hl7:"PR1"`
	GT1       []GT1               `hl7:"GT1"`
	NK1       []NK1               `hl7:"NK1"`
	INSURANCE []BAR_P01_INSURANCE `hl7:"INSURANCE"`
	ACC       ACC                 `hl7:"ACC"`
	UB1       UB1                 `hl7:"UB1"`
	UB2       UB2                 `hl7:"UB2"`
}

// BAR_P01 - Add and Update Patient Accounts
// Data is sent from some application (usually a Registration or an ADT system) to the patient accounting system to establish an account for a patient's billing/accounts receivable record.  Many of the segments associated with this event are optional.  This optionality allows those systems needing these fields to set up transactions which fulfill their requirements yet satisfy the HL7 requirements.  Sample event codes are in table 0003 - event type code.
type BAR_P01 struct {
	MSH   MSH             `hl7:"MSH,required"`
	EVN   EVN             `hl7:"EVN,required"`
	PID   PID             `hl7:"PID,required"`
	VISIT []BAR_P01_VISIT `hl7:"VISIT,required"`
}

type BAR_P02_PATIENT struct {
	PID PID `hl7:"PID,required"`
	PV1 PV1 `hl7:"PV1"`
}

// BAR_P02 - Purge Patient Accounts
// Generally, the elimination of all billing/accounts receivable records will be an internal function controlled by the financial system.  However, on occasion, there is a need to correct an account, or series of accounts, which may require a notice of account deletion to be sent from another sub-system and processed by the financial system.  Although a series of accounts may be purged within this one event, it is recommended that only one PID segment per event be sent
type BAR_P02 struct {
	MSH     MSH               `hl7:"MSH,required"`
	EVN     EVN               `hl7:"EVN,required"`
	PATIENT []BAR_P02_PATIENT `hl7:"PATIENT,required"`
}

// DFT_P03 - Post Detail Financial Transactions
// The Detail Financial Transaction is used to describe a financial transaction transmitted between systems, ie., to HIS for ancillary charges, ADT to HIS for patient deposits, etc.
type DFT_P03 struct {
	MSH MSH   `hl7:"MSH,required"`
	EVN EVN   `hl7:"EVN,required"`
	PID PID   `hl7:"PID,required"`
	PV1 PV1   `hl7:"PV1"`
	PV2 PV2   `hl7:"PV2"`
	OBX []OBX `hl7:"OBX"`
	FT1 []FT1 `hl7:"FT1,required"`
}

// DSR_Q01 - Display Response Message
// When display data is involved, these trigger events are served by the Query (QRY) and Display Response (DSR) and General Acknowledgement (ACK) messages.  When the query is for record-oriented data, the QRY message is used, but the response message is specific to a functional area.  Record-oriented queries are described in other chapters.  Display-oriented queries are described here.
type DSR_Q01 struct {
	MSH MSH   `hl7:"MSH,required"`
	MFA MFA   `hl7:"MFA,required"`
	ERR ERR   `hl7:"ERR"`
	QRD QRD   `hl7:"QRD,required"`
	QRF QRF   `hl7:"QRF"`
	DSP []DSP `hl7:"DSP,required"`
	DSC DSC   `hl7:"DSC"`
}

// DSR_Q03 - Deferred Response to A Query
// For clarity, A is the system initiating the query and B is the system sending the responses.  Multiple queries and responses are permitted within single messages.  The responses to a given query may be broken into several separate DSR messages.  A single DSR message may contain responses to more than one QRY
type DSR_Q03 struct {
	MSH MSH   `hl7:"MSH,required"`
	MSA MSA   `hl7:"MSA"`
	QRD QRD   `hl7:"QRD,required"`
	QRF QRF   `hl7:"QRF"`
	DSP []DSP `hl7:"DSP,required"`
	DSC DSC   `hl7:"DSC"`
}

// DSR_R03 - oriented results, query/unsol. update
type DSR_R03 struct {
	MSH MSH   `hl7:"MSH,required"`
	MSA MSA   `hl7:"MSA"`
	QRD QRD   `hl7:"QRD,required"`
	QRF QRF   `hl7:"QRF"`
	DSP []DSP `hl7:"DSP,required"`
	DSC DSC   `hl7:"DSC"`
}

// MCF - Delayed acknowledgement
// This message remains in the specification only for reasons of backwards compatibility.  It is used as part of the protocol which creates a generic form of an asynchronous application level acknowledgement, the MCF message.
type MCF struct {
	MSH MSH `hl7:"MSH,required"`
	MFA MFA `hl7:"MFA,required"`
	ERR ERR `hl7:"ERR"`
}

// MFD_M01 - Master files change not otherwise specified (for backwards comp.)
type MFD_M01 struct {
	MSH MSH   `hl7:"MSH,required"`
	MFI MFI   `hl7:"MFI,required"`
	MFA []MFA `hl7:"MFA"`
}

// MFD_M02 - Staff Practitioneer
type MFD_M02 struct {
	MSH MSH   `hl7:"MSH,required"`
	MFI MFI   `hl7:"MFI,required"`
	MFA []MFA `hl7:"MFA"`
}

// MFD_M03 - Test/Observation
type MFD_M03 struct {
	MSH MSH   `hl7:"MSH,required"`
	MFI MFI   `hl7:"MFI,required"`
	MFA []MFA `hl7:"MFA"`
}

type MFN_M01_MF struct {
	MFE MFE `hl7:"MFE,required"`
	Zxx Zxx `hl7:"Zxx"`
}

// MFN_M01 - Master files change not otherwise specified (for backwards comp.)
type MFN_M01 struct {
	MSH MSH          `hl7:"MSH,required"`
	MFI MFI          `hl7:"MFI,required"`
	MF  []MFN_M01_MF `hl7:"MF,required"`
}

type MFN_M02_MFSTAFF struct {
	MFE MFE `hl7:"MFE,required"`
	Zxx Zxx `hl7:"Zxx"`
}

// MFN_M02 - Staff Practitioneer
type MFN_M02 struct {
	MSH     MSH               `hl7:"MSH,required"`
	MFI     MFI               `hl7:"MFI,required"`
	MFSTAFF []MFN_M02_MFSTAFF `hl7:"MF_STAFF,required"`
}

type MFN_M03_MFTEST struct {
	MFE MFE `hl7:"MFE,required"`
	Zxx Zxx `hl7:"Zxx"`
}

// MFN_M03 - Test/Observation
type MFN_M03 struct {
	MSH    MSH              `hl7:"MSH,required"`
	MFI    MFI              `hl7:"MFI,required"`
	MFTEST []MFN_M03_MFTEST `hl7:"MF_TEST,required"`
}

// MFQ_M01 - Master files change not otherwise specified (for backwards comp.)
type MFQ_M01 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// MFQ_M02 - Staff Practitioneer
type MFQ_M02 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// MFQ_M03 - Test/Observation
type MFQ_M03 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

type NMD_N01_APPSTATUS struct {
	NSC NSC   `hl7:"NSC,required"`
	NTE []NTE `hl7:"NTE"`
}

type NMD_N01_APPSTATS struct {
	NST       NST               `hl7:"NST,required"`
	NTE       []NTE             `hl7:"NTE"`
	APPSTATUS NMD_N01_APPSTATUS `hl7:"APP_STATUS"`
}

type NMD_N01_CLOCK struct {
	NCK      NCK              `hl7:"NCK,required"`
	NTE      []NTE            `hl7:"NTE"`
	APPSTATS NMD_N01_APPSTATS `hl7:"APP_STATS"`
}

type NMD_N01_CLOCKANDSTATSWITHNOTES struct {
	CLOCK NMD_N01_CLOCK `hl7:"CLOCK"`
}

// NMD_N01 - Network Management Data
// One system creates an unsolicited update (UU) Network Management Data message (NMD) to transmit network management information to another system. In this case, the initiating system sends an NMD message as an unsolicited update (UU) containing network management information to a receiving system, which responds with a generic acknowledgement message (ACK).
type NMD_N01 struct {
	MSH                    MSH                              `hl7:"MSH,required"`
	CLOCKANDSTATSWITHNOTES []NMD_N01_CLOCKANDSTATSWITHNOTES `hl7:"CLOCK_AND_STATS_WITH_NOTES,required"`
}

type NMQ_N02_CLOCKANDSTATISTICS struct {
	NCK NCK `hl7:"NCK"`
	NST NST `hl7:"NST"`
	NSC NSC `hl7:"NSC"`
}

type NMQ_N02_QRYWITHDETAIL struct {
	QRD                QRD                          `hl7:"QRD,required"`
	QRF                QRF                          `hl7:"QRF"`
	CLOCKANDSTATISTICS []NMQ_N02_CLOCKANDSTATISTICS `hl7:"CLOCK_AND_STATISTICS,required"`
}

// NMQ_N02 - Network Management Query
// The NMQ (Network Management Query) message is used by one system to make system-level requests for information or action to another system. It has three segments, the NCK segment (network clock), the NST segment (network statistics), and the NSC segment (network status change). An example of the last type, NSC (network status change) would be an application or system startup/shut down request. At least one of these three segments must be present in the NMQ message. If a segment is present in the NMQ message, the corresponding segment needs to be present in the NMR message to return the requested data or status.
type NMQ_N02 struct {
	MSH           MSH                   `hl7:"MSH,required"`
	QRYWITHDETAIL NMQ_N02_QRYWITHDETAIL `hl7:"QRY_WITH_DETAIL"`
}

type NMR_N02_RESPONSE struct {
	NCK  NCK   `hl7:"NCK"`
	NTE  []NTE `hl7:"NTE"`
	NST  NST   `hl7:"NST"`
	NTE2 []NTE `hl7:"NTE"`
	NSC  NSC   `hl7:"NSC"`
	NTE3 []NTE `hl7:"NTE"`
}

// NMR_N02 - Network Management Response
// The NMQ/NMR (Network Management Query) message is used by one system to make system-level requests for information or action to another system. It has three segments, the NCK segment (network clock), the NST segment (network statistics), and the NSC segment (network status change). An example of the last type, NSC (network status change) would be an application or system startup/shut down request. At least one of these three segments must be present in the NMQ message. If a segment is present in the NMQ message, the corresponding segment needs to be present in the NMR message to return the requested data or status.
type NMR_N02 struct {
	MSH      MSH                `hl7:"MSH,required"`
	MSA      MSA                `hl7:"MSA,required"`
	ERR      ERR                `hl7:"ERR"`
	QRD      QRD                `hl7:"QRD"`
	RESPONSE []NMR_N02_RESPONSE `hl7:"RESPONSE,required"`
}

type ORF_R04_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
}

type ORF_R04_ORDER struct {
	ORC         ORC                   `hl7:"ORC"`
	OBR         OBR                   `hl7:"OBR,required"`
	NTE         []NTE                 `hl7:"NTE"`
	OBSERVATION []ORF_R04_OBSERVATION `hl7:"OBSERVATION,required"`
}

type ORF_R04_QUERYRESPONSE struct {
	QRD   QRD             `hl7:"QRD,required"`
	QRF   QRF             `hl7:"QRF"`
	PID   PID             `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []ORF_R04_ORDER `hl7:"ORDER,required"`
}

// ORF_R04 - Response to query; transmission of requested observation
type ORF_R04 struct {
	MSH           MSH                     `hl7:"MSH,required"`
	MSA           MSA                     `hl7:"MSA,required"`
	QUERYRESPONSE []ORF_R04_QUERYRESPONSE `hl7:"QUERY_RESPONSE,required"`
	DSC           DSC                     `hl7:"DSC"`
}

type ORM_O01_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
	AL1 []AL1 `hl7:"AL1"`
	PV1 PV1   `hl7:"PV1"`
}

type ORM_O01_ORDERDETAILSEGMENT struct {
	OBR OBR `hl7:"OBR"`
	RQD RQD `hl7:"RQD"`
	RQ1 RQ1 `hl7:"RQ1"`
	RXO RXO `hl7:"RXO"`
	ODS ODS `hl7:"ODS"`
	ODT ODT `hl7:"ODT"`
}

type ORM_O01_OBSERVATION struct {
	OBX OBX   `hl7:"OBX,required"`
	NTE []NTE `hl7:"NTE"`
}

type ORM_O01_ORDERDETAIL struct {
	ORDERDETAILSEGMENT ORM_O01_ORDERDETAILSEGMENT `hl7:"ORDER DETAIL SEGMENT,required"`
	NTE                []NTE                      `hl7:"NTE"`
	OBSERVATION        []ORM_O01_OBSERVATION      `hl7:"OBSERVATION"`
}

type ORM_O01_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL ORM_O01_ORDERDETAIL `hl7:"ORDER_DETAIL"`
	BLG         BLG                 `hl7:"BLG"`
}

// ORM_O01 - Order Message
// The function of this message is to initiate the transmission of information about an order.  This includes placing new orders, cancellation of existing orders, discontinuation, holding, etc.  ORM messages can originate also with a placer, filler, or an interested third party.
type ORM_O01 struct {
	MSH     MSH             `hl7:"MSH,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT ORM_O01_PATIENT `hl7:"PATIENT"`
	ORDER   []ORM_O01_ORDER `hl7:"ORDER,required"`
}

type ORR_O02_ORDERDETAILSEGMENT struct {
	OBR OBR `hl7:"OBR"`
	RQD RQD `hl7:"RQD"`
	RQ1 RQ1 `hl7:"RQ1"`
	RXO RXO `hl7:"RXO"`
	ODS ODS `hl7:"ODS"`
	ODT ODT `hl7:"ODT"`
}

type ORR_O02_ORDERDETAIL struct {
	ORDERDETAILSEGMENT ORR_O02_ORDERDETAILSEGMENT `hl7:"ORDER DETAIL SEGMENT"`
	NTE                []NTE                      `hl7:"NTE"`
}

type ORR_O02_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL ORR_O02_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

type ORR_O02_PATIENT struct {
	PID   PID             `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []ORR_O02_ORDER `hl7:"ORDER,required"`
}

// ORR_O02 - Response Message
// The function of this message is to respond to an ORM message.  An ORR message is the application acknowledgement to an ORM message.  See Chapter 2 for a description of the acknowledgement paradigm.
type ORR_O02 struct {
	MSH     MSH             `hl7:"MSH,required"`
	MSA     MSA             `hl7:"MSA,required"`
	ERR     ERR             `hl7:"ERR"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT ORR_O02_PATIENT `hl7:"PATIENT"`
}

type ORU_R01_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
	PV1 PV1   `hl7:"PV1"`
}

type ORU_R01_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
}

type ORU_R01_ORDEROBSERVATION struct {
	ORC         ORC                   `hl7:"ORC"`
	OBR         OBR                   `hl7:"OBR,required"`
	NTE         []NTE                 `hl7:"NTE"`
	OBSERVATION []ORU_R01_OBSERVATION `hl7:"OBSERVATION,required"`
}

type ORU_R01_PATIENTRESULT struct {
	PATIENT          ORU_R01_PATIENT            `hl7:"PATIENT"`
	ORDEROBSERVATION []ORU_R01_ORDEROBSERVATION `hl7:"ORDER_OBSERVATION,required"`
}

// ORU_R01 - Unsolicited Transmission Of Requested Information
// With the type (OBX) defined in this chapter, and the OBR defined in Chapter 4, one can construct almost any clinical report as a three-level hierarchy, with the PID segment defined in Chapter 3 at the upper level, an order record (OBR) at the next level and one or more observation records (OBX) at the "bottom."
type ORU_R01 struct {
	MSH           MSH                     `hl7:"MSH,required"`
	PATIENTRESULT []ORU_R01_PATIENTRESULT `hl7:"PATIENT_RESULT,required"`
	DSC           DSC                     `hl7:"DSC"`
}

// QRY_A19 - Patient Query
// The following triggering event is served by QRY (a query from another system) and ADR (a response from an ADT system.)
//
// Another application determines a need for ADT data about a patient and sends a query to the ADT system.  The Who Filter in the QRD can identify the patient or account number upon which the query is defined and can contain a Format Code of R (record oriented).  If the query is based on Patient ID and there are data associated with multiple accounts, it is an implementation issue as to which account data should be returned.  The ADT Event Type Segment, if included in the response, describes the last event for which the ADT system initiated an unsolicited update
type QRY_A19 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
}

// QRY_P04 - Generate bills and A/R statements
// For patient accounting systems that support demand billing, the QRY/DSP transaction defined in Chapter 2 will provide the mechanism to request a copy of the bill for printing or viewing by the requesting system.
type QRY_P04 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q01 - A Query is made for immediate Display Response
// When display data is involved, these trigger events are served by the Query (QRY) and Display Response (DSR) and General Acknowledgement (ACK) messages.  When the query is for record-oriented data, the QRY message is used, but the response message is specific to a functional area.  Record-oriented queries are described in other chapters.  Display-oriented queries are described here.
type QRY_Q01 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q02 - A Query is Sent for Deferred Response
// For clarity, A is the system initiating the query and B is the system sending the responses.  Multiple queries and responses are permitted within single messages.  The responses to a given query may be broken into several separate DSR messages.  A single DSR message may contain responses to more than one QRY
type QRY_Q02 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q26 - Pharmacy Prescription Order Query
// Query (QRY_Q26) / Response (ROR_ROR)
type QRY_Q26 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q27 - Pharmacy Administration Information Query
// Query (QRY_Q27) / Response (RAR_RAR)
type QRY_Q27 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q28 - Pharmacy Dispense Information Query
// Query (QRY_Q28) / Response (RDR_RDR)
type QRY_Q28 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q29 - Pharmacy Encoded Order Information Query
// Query (QRY_Q29) / Response (RER_RER)
type QRY_Q29 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_Q30 - Pharmacy Dose Information Query
// Query (QRY_Q30) / Response (RGR_RGR)
type QRY_Q30 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF"`
	DSC DSC `hl7:"DSC"`
}

// QRY_R02 - Query for results of observation
type QRY_R02 struct {
	MSH MSH `hl7:"MSH,required"`
	QRD QRD `hl7:"QRD,required"`
	QRF QRF `hl7:"QRF,required"`
	DSC DSC `hl7:"DSC"`
}

type RAR_RAR_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
}

type RAR_RAR_ENCODING struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RAR_RAR_ORDER struct {
	ORC      ORC              `hl7:"ORC,required"`
	ENCODING RAR_RAR_ENCODING `hl7:"ENCODING"`
	RXA      []RXA            `hl7:"RXA,required"`
}

type RAR_RAR_DEFINITION struct {
	QRD     QRD             `hl7:"QRD,required"`
	QRF     QRF             `hl7:"QRF"`
	PATIENT RAR_RAR_PATIENT `hl7:"PATIENT"`
	ORDER   []RAR_RAR_ORDER `hl7:"ORDER,required"`
}

// RAR_RAR - Pharmacy Administration Information Response
// Query (QRY_Q27) / Response (RAR_RAR)
type RAR_RAR struct {
	MSH        MSH                  `hl7:"MSH,required"`
	MSA        MSA                  `hl7:"MSA,required"`
	ERR        ERR                  `hl7:"ERR"`
	DEFINITION []RAR_RAR_DEFINITION `hl7:"DEFINITION,required"`
	DSC        DSC                  `hl7:"DSC"`
}

type RAS_O02_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
	AL1 []AL1 `hl7:"AL1"`
	PV1 PV1   `hl7:"PV1"`
}

type RAS_O02_COMPONENTS struct {
	RXC []RXC `hl7:"RXC,required"`
	NTE []NTE `hl7:"NTE"`
}

type RAS_O02_ORDERDETAILSUPPLEMENT struct {
	NTE        []NTE              `hl7:"NTE,required"`
	RXR        []RXR              `hl7:"RXR,required"`
	COMPONENTS RAS_O02_COMPONENTS `hl7:"COMPONENTS"`
}

type RAS_O02_ORDERDETAIL struct {
	RXO                   RXO                           `hl7:"RXO,required"`
	ORDERDETAILSUPPLEMENT RAS_O02_ORDERDETAILSUPPLEMENT `hl7:"ORDER DETAIL SUPPLEMENT"`
}

type RAS_O02_ENCODING struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RAS_O02_OBSERVATION struct {
	OBX OBX   `hl7:"OBX,required"`
	NTE []NTE `hl7:"NTE"`
}

type RAS_O02_ORDER struct {
	ORC         ORC                   `hl7:"ORC,required"`
	ORDERDETAIL RAS_O02_ORDERDETAIL   `hl7:"ORDER DETAIL"`
	ENCODING    RAS_O02_ENCODING      `hl7:"ENCODING"`
	RXA         []RXA                 `hl7:"RXA,required"`
	RXR         RXR                   `hl7:"RXR,required"`
	OBSERVATION []RAS_O02_OBSERVATION `hl7:"OBSERVATION"`
}

// RAS_O02 - Pharmacy/treatment administration message
// The RAS message may be created by the administering application (e.g., nursing application) for each instance of administration for an existing order.  If the administering application wants to report several administrations of medication for a given order with a single RAS message, each instance is reported by a separate (repeating) RXA segment.  In addition, the administration records for a group of orders may be sent in a single message by creating repeating groups of segments at the ORC level.
type RAS_O02 struct {
	MSH     MSH             `hl7:"MSH,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RAS_O02_PATIENT `hl7:"PATIENT"`
	ORDER   []RAS_O02_ORDER `hl7:"ORDER,required"`
}

type RDE_O01_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
	AL1 []AL1 `hl7:"AL1"`
	PV1 PV1   `hl7:"PV1"`
}

type RDE_O01_COMPONENT struct {
	RXC []RXC `hl7:"RXC,required"`
	NTE []NTE `hl7:"NTE"`
}

type RDE_O01_ORDERDETAIL struct {
	RXO       RXO               `hl7:"RXO,required"`
	NTE       []NTE             `hl7:"NTE"`
	RXR       []RXR             `hl7:"RXR,required"`
	COMPONENT RDE_O01_COMPONENT `hl7:"COMPONENT"`
}

type RDE_O01_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
}

type RDE_O01_ORDER struct {
	ORC         ORC                   `hl7:"ORC,required"`
	ORDERDETAIL RDE_O01_ORDERDETAIL   `hl7:"ORDER_DETAIL"`
	RXE         RXE                   `hl7:"RXE,required"`
	RXR         []RXR                 `hl7:"RXR,required"`
	RXC         []RXC                 `hl7:"RXC"`
	OBSERVATION []RDE_O01_OBSERVATION `hl7:"OBSERVATION,required"`
}

// RDE_O01 - Pharmacy/treatment encoded order message
// This message communicates the Pharmacy application's encoding of the pharmacy order (ORM message with RXO segment, see above).  It may be sent as an unsolicited message to report on either a single order or multiple pharmacy orders for a patient.
type RDE_O01 struct {
	MSH     MSH             `hl7:"MSH,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RDE_O01_PATIENT `hl7:"PATIENT"`
	ORDER   []RDE_O01_ORDER `hl7:"ORDER,required"`
}

type RDR_RDR_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
}

type RDR_RDR_ENCODING struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR RXR   `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RDR_RDR_DISPENSE struct {
	RXD RXD   `hl7:"RXD,required"`
	RXR []RXR `hl7:"RXR,required"`
}

type RDR_RDR_ORDER struct {
	ORC      ORC                `hl7:"ORC,required"`
	ENCODING RDR_RDR_ENCODING   `hl7:"ENCODING"`
	DISPENSE []RDR_RDR_DISPENSE `hl7:"DISPENSE,required"`
}

type RDR_RDR_DEFINITION struct {
	QRD     QRD             `hl7:"QRD,required"`
	QRF     QRF             `hl7:"QRF"`
	PATIENT RDR_RDR_PATIENT `hl7:"PATIENT"`
	ORDER   []RDR_RDR_ORDER `hl7:"ORDER,required"`
}

// RDR_RDR - Pharmacy Dispense Information Response
// Query (QRY_Q28) / Response (RDR_RDR)
type RDR_RDR struct {
	MSH        MSH                  `hl7:"MSH,required"`
	MSA        MSA                  `hl7:"MSA,required"`
	ERR        ERR                  `hl7:"ERR"`
	DEFINITION []RDR_RDR_DEFINITION `hl7:"DEFINITION,required"`
	DSC        DSC                  `hl7:"DSC"`
}

type RDS_O01_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
	AL1 []AL1 `hl7:"AL1"`
	PV1 PV1   `hl7:"PV1"`
}

type RDS_O01_COMPONENT struct {
	RXC []RXC `hl7:"RXC,required"`
	NTE []NTE `hl7:"NTE"`
}

type RDS_O01_ORDERDETAILSUPPLEMENT struct {
	NTE       []NTE             `hl7:"NTE,required"`
	RXR       []RXR             `hl7:"RXR,required"`
	COMPONENT RDS_O01_COMPONENT `hl7:"COMPONENT"`
}

type RDS_O01_ORDERDETAIL struct {
	RXO                   RXO                           `hl7:"RXO,required"`
	ORDERDETAILSUPPLEMENT RDS_O01_ORDERDETAILSUPPLEMENT `hl7:"ORDER DETAIL SUPPLEMENT"`
}

type RDS_O01_ENCODING struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RDS_O01_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
}

type RDS_O01_ORDER struct {
	ORC         ORC                   `hl7:"ORC,required"`
	ORDERDETAIL RDS_O01_ORDERDETAIL   `hl7:"ORDER_DETAIL"`
	ENCODING    RDS_O01_ENCODING      `hl7:"ENCODING"`
	RXD         RXD                   `hl7:"RXD,required"`
	RXR         []RXR                 `hl7:"RXR,required"`
	RXE         []RXE                 `hl7:"RXE"`
	OBSERVATION []RDS_O01_OBSERVATION `hl7:"OBSERVATION,required"`
}

// RDS_O01 - Pharmacy/treatment dispense information
// The RDS message may be created by the Pharmacy application for each instance of dispensing drugs to fill an existing order or orders.  In the most common case, the RDS messages would be routed to a Nursing application or to some clinical application, which needs the data about drugs dispensed.  As a site-specific variant, the original order segments (RXO, RXE and their associated RXR/RXCs) may be sent optionally (for comparison).
type RDS_O01 struct {
	MSH     MSH             `hl7:"MSH,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RDS_O01_PATIENT `hl7:"PATIENT"`
	ORDER   []RDS_O01_ORDER `hl7:"ORDER,required"`
}

type RER_RER_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
}

type RER_RER_ORDER struct {
	ORC ORC   `hl7:"ORC,required"`
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RER_RER_DEFINITION struct {
	QRD     QRD             `hl7:"QRD,required"`
	QRF     QRF             `hl7:"QRF"`
	PATIENT RER_RER_PATIENT `hl7:"PATIENT"`
	ORDER   []RER_RER_ORDER `hl7:"ORDER,required"`
}

// RER_RER - Pharmacy Encoded Order Information Response
// Query (QRY_Q29) / Response (RER_RER)
type RER_RER struct {
	MSH        MSH                  `hl7:"MSH,required"`
	MSA        MSA                  `hl7:"MSA,required"`
	ERR        ERR                  `hl7:"ERR"`
	DEFINITION []RER_RER_DEFINITION `hl7:"DEFINITION,required"`
	DSC        DSC                  `hl7:"DSC"`
}

type RGR_RGR_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
}

type RGR_RGR_ENCODING struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RGR_RGR_ORDER struct {
	ORC      ORC              `hl7:"ORC,required"`
	ENCODING RGR_RGR_ENCODING `hl7:"ENCODING"`
	RXG      []RXG            `hl7:"RXG,required"`
	RXR      []RXR            `hl7:"RXR,required"`
}

type RGR_RGR_DEFINITION struct {
	QRD     QRD             `hl7:"QRD,required"`
	QRF     QRF             `hl7:"QRF"`
	PATIENT RGR_RGR_PATIENT `hl7:"PATIENT"`
	ORDER   []RGR_RGR_ORDER `hl7:"ORDER,required"`
}

// RGR_RGR - Pharmacy dose information response
// Query (QRY_Q30) / Response (RGR_RGR)
type RGR_RGR struct {
	MSH        MSH                  `hl7:"MSH,required"`
	MSA        MSA                  `hl7:"MSA,required"`
	ERR        ERR                  `hl7:"ERR"`
	DEFINITION []RGR_RGR_DEFINITION `hl7:"DEFINITION,required"`
	DSC        DSC                  `hl7:"DSC"`
}

type RGV_O01_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
	AL1 []AL1 `hl7:"AL1"`
	PV1 PV1   `hl7:"PV1"`
}

type RGV_O01_COMPONENT struct {
	RXC []RXC `hl7:"RXC,required"`
	NTE []NTE `hl7:"NTE"`
}

type RGV_O01_ORDERDETAILSUPPLEMENT struct {
	NTE       []NTE             `hl7:"NTE,required"`
	RXR       []RXR             `hl7:"RXR,required"`
	COMPONENT RGV_O01_COMPONENT `hl7:"COMPONENT"`
}

type RGV_O01_ORDERDETAIL struct {
	RXO                   RXO                           `hl7:"RXO,required"`
	ORDERDETAILSUPPLEMENT RGV_O01_ORDERDETAILSUPPLEMENT `hl7:"ORDER DETAIL SUPPLEMENT"`
}

type RGV_O01_ENCODING struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RGV_O01_OBSERVATION struct {
	OBX OBX   `hl7:"OBX"`
	NTE []NTE `hl7:"NTE"`
}

type RGV_O01_GIVE struct {
	RXG         RXG                 `hl7:"RXG,required"`
	RXR         []RXR               `hl7:"RXR,required"`
	RXC         []RXC               `hl7:"RXC"`
	OBSERVATION RGV_O01_OBSERVATION `hl7:"OBSERVATION,required"`
}

type RGV_O01_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL RGV_O01_ORDERDETAIL `hl7:"ORDER_DETAIL"`
	ENCODING    RGV_O01_ENCODING    `hl7:"ENCODING"`
	GIVE        RGV_O01_GIVE        `hl7:"GIVE,required"`
}

// RGV_O01 - Pharmacy/treatment give message
// The RGV message uses the RXG segment to record drug administration instructions.  It may carry information about a single scheduled administration on a drug, or it may carry information about multiple administrations of a drug
type RGV_O01 struct {
	MSH     MSH             `hl7:"MSH,required"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RGV_O01_PATIENT `hl7:"PATIENT"`
	ORDER   []RGV_O01_ORDER `hl7:"ORDER,required"`
}

type ROR_ROR_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
}

type ROR_ROR_ORDER struct {
	ORC ORC   `hl7:"ORC,required"`
	RXO RXO   `hl7:"RXO,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type ROR_ROR_DEFINITION struct {
	QRD     QRD             `hl7:"QRD,required"`
	QRF     QRF             `hl7:"QRF"`
	PATIENT ROR_ROR_PATIENT `hl7:"PATIENT"`
	ORDER   []ROR_ROR_ORDER `hl7:"ORDER,required"`
}

// ROR_ROR - Pharmacy Prescription Order Response
// Query (QRY_Q26) / Response (ROR_ROR)
type ROR_ROR struct {
	MSH        MSH                  `hl7:"MSH,required"`
	MSA        MSA                  `hl7:"MSA,required"`
	ERR        ERR                  `hl7:"ERR"`
	DEFINITION []ROR_ROR_DEFINITION `hl7:"DEFINITION,required"`
	DSC        DSC                  `hl7:"DSC"`
}

type RRA_O02_PATIENT struct {
	PID PID   `hl7:"PID,required"`
	NTE []NTE `hl7:"NTE"`
}

type RRA_O02_ADMINISTRATION struct {
	RXA []RXA `hl7:"RXA,required"`
	RXR RXR   `hl7:"RXR,required"`
}

type RRA_O02_ORDER struct {
	ORC            ORC                      `hl7:"ORC,required"`
	ADMINISTRATION []RRA_O02_ADMINISTRATION `hl7:"ADMINISTRATION"`
}

type RRA_O02_RESPONSE struct {
	PATIENT RRA_O02_PATIENT `hl7:"PATIENT"`
	ORDER   []RRA_O02_ORDER `hl7:"ORDER,required"`
}

// RRA_O02 - Pharmacy/treatment administration acknowledgment message
// Response to a RAS_O02
type RRA_O02 struct {
	MSH      MSH              `hl7:"MSH,required"`
	MSA      MSA              `hl7:"MSA,required"`
	ERR      ERR              `hl7:"ERR"`
	NTE      []NTE            `hl7:"NTE"`
	RESPONSE RRA_O02_RESPONSE `hl7:"RESPONSE"`
}

type RRD_O02_ORDERDETAIL struct {
	RXD RXD   `hl7:"RXD,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RRD_O02_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL RRD_O02_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

type RRD_O02_PATIENT struct {
	PID   PID             `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []RRD_O02_ORDER `hl7:"ORDER,required"`
}

// RRD_O02 - Pharmacy/treatment dispense acknowledgment message
// The RDS message may be created by the Pharmacy application for each instance of dispensing drugs to fill an existing order or orders.  In the most common case, the RDS messages would be routed to a Nursing application or to some clinical application, which needs the data about drugs dispensed.  As a site-specific variant, the original order segments (RXO, RXE and their associated RXR/RXCs) may be sent optionally (for comparison).
type RRD_O02 struct {
	MSH     MSH             `hl7:"MSH,required"`
	MSA     MSA             `hl7:"MSA,required"`
	ERR     ERR             `hl7:"ERR"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RRD_O02_PATIENT `hl7:"PATIENT"`
}

type RRE_O02_ORDERDETAIL struct {
	RXE RXE   `hl7:"RXE,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RRE_O02_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL RRE_O02_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

type RRE_O02_PATIENT struct {
	PID   PID             `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []RRE_O02_ORDER `hl7:"ORDER,required"`
}

// RRE_O02 - Pharmacy/treatment encoded order acknowledgment message
// This message communicates the Pharmacy application's encoding of the pharmacy order (ORM message with RXO segment, see above).  It may be sent as an unsolicited message to report on either a single order or multiple pharmacy orders for a patient.
type RRE_O02 struct {
	MSH     MSH             `hl7:"MSH,required"`
	MSA     MSA             `hl7:"MSA,required"`
	ERR     ERR             `hl7:"ERR"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RRE_O02_PATIENT `hl7:"PATIENT"`
}

type RRG_O02_ORDERDETAIL struct {
	RXG RXG   `hl7:"RXG,required"`
	RXR []RXR `hl7:"RXR,required"`
	RXC []RXC `hl7:"RXC"`
}

type RRG_O02_ORDER struct {
	ORC         ORC                 `hl7:"ORC,required"`
	ORDERDETAIL RRG_O02_ORDERDETAIL `hl7:"ORDER_DETAIL"`
}

type RRG_O02_PATIENT struct {
	PID   PID             `hl7:"PID"`
	NTE   []NTE           `hl7:"NTE"`
	ORDER []RRG_O02_ORDER `hl7:"ORDER,required"`
}

// RRG_O02 - Pharmacy/treatment give acknowledgment message
// The RGV message uses the RXG segment to record drug administration instructions.  It may carry information about a single scheduled administration on a drug, or it may carry information about multiple administrations of a drug.
type RRG_O02 struct {
	MSH     MSH             `hl7:"MSH,required"`
	MSA     MSA             `hl7:"MSA,required"`
	ERR     ERR             `hl7:"ERR"`
	NTE     []NTE           `hl7:"NTE"`
	PATIENT RRG_O02_PATIENT `hl7:"PATIENT"`
}

// UDM_Q05 - Unsolicited Display Update Message
// There is a simple HL7 message that allows for unsolicited display update messages to be sent in HL7 format from one system to another.
//
// Trigger events for the unsolicited update are generally the completion of a particular action (concerning a given patient).
type UDM_Q05 struct {
	MSH MSH   `hl7:"MSH,required"`
	URD URD   `hl7:"URD,required"`
	URS URS   `hl7:"URS"`
	DSP []DSP `hl7:"DSP,required"`
	DSC DSC   `hl7:"DSC,required"`
}
