// Code generated by gen_hl7v2. DO NOT EDIT.

package v23

// AD - Address
// Example:
// |10 ASH LN^#3^LIMA^OH^48132|
type AD struct {
	StreetAddress              ST `hl7:"1"`
	OtherDesignation           ST `hl7:"2"`
	City                       ST `hl7:"3"`
	StateOrProvince            ST `hl7:"4"`
	ZipOrPostalCode            ST `hl7:"5"`
	Country                    ID `hl7:"6"`
	AddressType                ID `hl7:"7"`
	OtherGeographicDesignation ST `hl7:"8"`
}

// CD - Channel Definition
// This data type is used for labeling of digital waveform data.  It defines a recording channel which is associated with one of the values in each time sample of waveform data.  Each channel has a number (which generally defines its position in a multichannel display) and an optional name or label (also used in displays).  One or two named waveform sources may also be associated with a channel (providing for the use of differential amplifiers with two inputs). The other components of the channel definition data type are optional.
type CD struct {
	ChannelIdentifier        CM_WVI          `hl7:"1"`
	WaveformSource           CM_CD_ELECTRODE `hl7:"2"`
	ChannelSensitivityUnits  CM_CSU          `hl7:"3"`
	CalibrationParameters    CM_CCP          `hl7:"4"`
	SamplingFrequency        NM              `hl7:"5"`
	MinimumMaximumDataValues CM_MDV          `hl7:"6"`
}

// CE - Coded Element
// This data type transmits codes and the text associated with the code.  To allow all six components of a CE data type to be valued, the maximum length of this data type must be at  least 60 (see Section 2.6.2, “Maximum length”)
//
// Example:
// |F-11380^CREATININE^I9^2148-5^CREATININE^LN|
type CE struct {
	Identifier                  ST `hl7:"1"`
	Text                        ST `hl7:"2"`
	NameOfCodingSystem          ST `hl7:"3"`
	AlternateIdentifier         ST `hl7:"4"`
	AlternateText               ST `hl7:"5"`
	NameOfAlternateCodingSystem ST `hl7:"6"`
}

// CF - Coded Element With Formatted Values
// This data type transmits codes and the formatted text associated with the code.  This data type can be used to transmit for the first time the formatted text for the canned text portion of a report, for example, a standard radiologic description for a normal chest X-ray.  The receiving system can store this information and in subsequent messages only the identifier need be sent.  Another potential use of this data type is transmitting master file records that contain formatted text.
//
// The components, primary and alternate, are defined exactly as in the CE data type with the exception of the second and fifth components which are of the formatted text data type.
//
// Example:
// OBX||CF|71020^CXR^CPMC||79989^\H\Description:\N\\.sp\\ti+4\Heart is not enlarged.  There is no evidence of pneumonia, effusion, pneumothorax or any masses.\.sp+3\\H\Impression: \N\\.sp\\.ti+4\Negative chest.^CPMC
type CF struct {
	Identifier                  ID `hl7:"1"`
	FormattedText               FT `hl7:"2"`
	NameOfCodingSystem          ST `hl7:"3"`
	AlternateIdentifier         ID `hl7:"4"`
	AlternateFormattedText      FT `hl7:"5"`
	NameOfAlternateCodingSystem ST `hl7:"6"`
}

// CK - Composite ID With Check Digit
// This data type is used for certain fields that commonly contain check digits, e.g., PID-3-patient ID (internal).  If a site is not using check digits for a particular CK field, the second and third components are not valued.
//
// Example:
// |128952^6^M11^ADT01|
type CK struct {
	IDNumber                                   NM `hl7:"1"`
	CheckDigit                                 ST `hl7:"2"`
	CodeIdentifyingTheCheckDigitSchemeEmployed ID `hl7:"3"`
	AssigningAuthority                         HD `hl7:"4"`
}

// CM_ABS_RANGE - Absolute Range
type CM_ABS_RANGE struct {
	Range_           CM_RANGE `hl7:"1"`
	NumericChange    NM       `hl7:"2"`
	PercentPerChange NM       `hl7:"3"`
	Days             NM       `hl7:"4"`
}

// CM_AUI - Authorization Information
type CM_AUI struct {
	AuthorizationNumber ST `hl7:"1"`
	Date                DT `hl7:"2"`
	Source              ST `hl7:"3"`
}

// CM_CCD - Charge Time
type CM_CCD struct {
	WhenToChargeCode ID `hl7:"1"`
	DateTime         TS `hl7:"2"`
}

// CM_CCP - Channel Calibration Parameters
// This component consists of three optional subcomponents (each a maximum of 20 characters, data type NM), separated from each other by subcomponent delimiters (&), which define corrections to channel sensitivity, baseline, and channel time skew which may be derived from a calibration procedure
type CM_CCP struct {
	SensitivityCorrectionFactor NM `hl7:"1"`
	Baseline                    NM `hl7:"2"`
	TimeSkew                    NM `hl7:"3"`
}

// CM_CD_ELECTRODE - Electrode Parameter
type CM_CD_ELECTRODE struct {
	SourceName1 ST `hl7:"1"`
	SourceName2 ST `hl7:"2"`
}

// CM_CSU - Channel Sensitivity/units
// This CM data type defines the channel sensitivity (gain) and the units in which it is measured.  This component consists of up to seven subcomponents, separated from each other by subcomponent delimiters (&).  The first subcomponent specifies the sensitivity, while the remaining six subcomponents are used to specify the units of the sensitivity, using a format similar to the components of the coded entry (CE) data type.
type CM_CSU struct {
	Sensitivity                      NM `hl7:"1"`
	UnitIdentifier                   ID `hl7:"2"`
	UnitText                         ST `hl7:"3"`
	UnitsNameOfCodingSystem          ST `hl7:"4"`
	UnitsAlternateIdentifier         ID `hl7:"5"`
	UnitsAlternateText               ST `hl7:"6"`
	UnitsNameOfAlternateCodingSystem ST `hl7:"7"`
}

// CM_DDI - Daily Deductible
type CM_DDI struct {
	DelayDays    NM `hl7:"1"`
	Amount       NM `hl7:"2"`
	NumberOfDays NM `hl7:"3"`
}

// CM_DIN - Activation Date
type CM_DIN struct {
	Date            TS `hl7:"1"`
	InstitutionName CE `hl7:"2"`
}

// CM_DLD - Discharge Location
type CM_DLD struct {
	DischargeLocation ID `hl7:"1"`
	EffectiveDate     TS `hl7:"2"`
}

// CM_DLT - Delta Check
type CM_DLT struct {
	Range_           CM_RANGE `hl7:"1"`
	NumericThreshold NM       `hl7:"2"`
	Change           ST       `hl7:"3"`
	LengthOfTimeDays NM       `hl7:"4"`
}

// CM_DTN - Day Type And Number
type CM_DTN struct {
	DayType      IS `hl7:"1"`
	NumberOfDays NM `hl7:"2"`
}

// CM_EIP - Parent Order
type CM_EIP struct {
	ParentSPlacerOrderNumber EI `hl7:"1"`
	ParentSFillerOrderNumber EI `hl7:"2"`
}

// CM_ELD - Error
type CM_ELD struct {
	SegmentID            ST `hl7:"1"`
	Sequence             NM `hl7:"2"`
	FieldPosition        NM `hl7:"3"`
	CodeIdentifyingError CE `hl7:"4"`
}

// CM_MDV - Minimum/maximum Data Values
type CM_MDV struct {
	MinimumValue NM `hl7:"1"`
	MaximumValue NM `hl7:"2"`
}

// CM_MOC - Charge To Practise
type CM_MOC struct {
	DollarAmount MO `hl7:"1"`
	ChargeCode   CE `hl7:"2"`
}

// CM_MSG - Message Type
// This field contains the message type and trigger event for the message.
type CM_MSG struct {
	MessageType  ID `hl7:"1"`
	TriggerEvent ID `hl7:"2"`
}

// CM_NDL - Observing Practitioner
type CM_NDL struct {
	OPName             CN `hl7:"1"`
	StartDateTime      TS `hl7:"2"`
	EndDateTime        TS `hl7:"3"`
	PointOfCare        IS `hl7:"4"`
	Room               IS `hl7:"5"`
	Bed                IS `hl7:"6"`
	Facility           HD `hl7:"7"`
	LocationStatus     IS `hl7:"8"`
	PersonLocationType IS `hl7:"9"`
	Building           IS `hl7:"10"`
	Floor              ST `hl7:"11"`
}

// CM_OCD - Occurence
type CM_OCD struct {
	OccurrenceCode CE `hl7:"1"`
	OccurrenceDate DT `hl7:"2"`
}

// CM_OSD - Order Sequence
// There are many situations, such as the creation of an order for a group of intravenous (IV) solutions, where the sequence of the individual intravenous solutions (each a service in itself) needs to be specified, e.g., hyperalimentation with multi-vitamins in every third bottle.
//
// There are other situations where part of the order’s instructions contains a results condition of some type, such as “PRN pain.”  There is currently a free text “condition” component of ORC-7-quantity/timing which allows any condition to be specified.  However, to support a fully encoded version of order sequencing, or results condition, we have defined in the following paragraphs a 10th component of ORC-7quantity/timing.
//
// The sequencing conditions supported by this 10th component are based on the completion of a  predecessor service.
type CM_OSD struct {
	SequenceResultsFlag               ID `hl7:"1"`
	PlacerOrderNumberEntityIdentifier ST `hl7:"2"`
	PlacerOrderNumberNamespaceID      IS `hl7:"3"`
	FillerOrderNumberEntityIdentifier ST `hl7:"4"`
	FillerOrderNumberNamespaceID      IS `hl7:"5"`
	SequenceConditionValue            ST `hl7:"6"`
	MaximumNumberOfRepeats            NM `hl7:"7"`
	PlacerOrderNumberUniversalID      ST `hl7:"8"`
	PlacerOrderNumberUniversalIDType  ID `hl7:"9"`
	FillerOrderNumberUniversalID      ST `hl7:"10"`
	FillerOrderNumberUniversalIDType  ID `hl7:"11"`
}

// CM_OSP - Occurence Span
type CM_OSP struct {
	OccurrenceSpanCode      CE `hl7:"1"`
	OccurrenceSpanStartDate DT `hl7:"2"`
	OccurrenceSpanStopDate  DT `hl7:"3"`
}

// CM_PCF - Pre-certification Required
// This field indicates whether pre-certification is required for particular patient types, and the time window for obtaining the certification.
type CM_PCF struct {
	PreCertificationPatientType IS `hl7:"1"`
	PreCertificationRequired    ID `hl7:"2"`
	PreCertificationWindwow     TS `hl7:"3"`
}

// CM_PEN - Penalty
type CM_PEN struct {
	PenaltyType   IS `hl7:"1"`
	PenaltyAmount NM `hl7:"2"`
}

// CM_PI - Person Identifier
type CM_PI struct {
	IDNumber            ST `hl7:"1"`
	TypeOfIDNumber      IS `hl7:"2"`
	OtherQualifyingInfo ST `hl7:"3"`
}

// CM_PIP - Privileges
type CM_PIP struct {
	Privilege      CE `hl7:"1"`
	PrivilegeClass CE `hl7:"2"`
	ExpirationDate DT `hl7:"3"`
	ActivationDate DT `hl7:"4"`
}

// CM_PLN - Practitioner ID Numbers
type CM_PLN struct {
	IDNumber                 ST `hl7:"1"`
	TypeOfIDNumber           IS `hl7:"2"`
	StateOtherQualifyingInfo ST `hl7:"3"`
	ExpirationDate           DT `hl7:"4"`
}

// CM_PRL - Parent Result Link
type CM_PRL struct {
	OBX3ObservationIdentifierOfParentResult CE `hl7:"1"`
	OBX4SubIDOfParentResult                 ST `hl7:"2"`
	PartOfOBX5ObservationResultFromParent   TX `hl7:"3"`
}

// CM_PTA - Policy Type
type CM_PTA struct {
	PolicyType  IS `hl7:"1"`
	AmountClass IS `hl7:"2"`
	Amount      NM `hl7:"3"`
}

// CM_RANGE - Wertebereich
type CM_RANGE struct {
	LowValue  ST `hl7:"1"`
	HighValue ST `hl7:"2"`
}

// CM_RFR - Reference Range
type CM_RFR struct {
	ReferenceRange CM_RANGE `hl7:"1"`
	Sex            IS       `hl7:"2"`
	AgeRange       CM_RANGE `hl7:"3"`
	AgeGestation   CM_RANGE `hl7:"4"`
	Species        TX       `hl7:"5"`
	RaceSubspecies ST       `hl7:"6"`
	Conditions     TX       `hl7:"7"`
}

// CM_RMC - Room Coverage
type CM_RMC struct {
	RoomType       IS `hl7:"1"`
	AmountType     IS `hl7:"2"`
	CoverageAmount NM `hl7:"3"`
}

// CM_SPD - Specialty
type CM_SPD struct {
	SpecialtyName       ST `hl7:"1"`
	GoverningBoard      ST `hl7:"2"`
	EligibleOrCertified ID `hl7:"3"`
	DateOfCertification DT `hl7:"4"`
}

// CM_SPS - Specimen Source
type CM_SPS struct {
	SpecimenSourceNameOrCode     CE `hl7:"1"`
	Additives                    TX `hl7:"2"`
	Freetext                     TX `hl7:"3"`
	BodySite                     CE `hl7:"4"`
	SiteModifier                 CE `hl7:"5"`
	CollectionModifierMethodCode CE `hl7:"6"`
}

// CM_UVC - Value Code And Amount
type CM_UVC struct {
	ValueCode   IS `hl7:"1"`
	ValueAmount NM `hl7:"2"`
}

// CM_VR - Value Qualifier
type CM_VR struct {
	FirstDataCodeValue ST `hl7:"1"`
	LastDataCodeCalue  ST `hl7:"2"`
}

// CM_WVI - Channel Identifier
type CM_WVI struct {
	ChannelNumber NM `hl7:"1"`
	ChannelName   ST `hl7:"2"`
}

// CN - Composite ID Number And Name
// A field identifying a person both as a coded value and with a text name.  For specific fields, individual sites may elect to omit the ID or the name
//
// Example:
// |12372^RIGGINS^JOHN^""^""^""^MD^ADT1|
// |12372^^^^^^^ADT1|
// |^RIGGINS^JOHN^""^""^""^MD|
type CN struct {
	IDNumber            ST `hl7:"1"`
	FamilyName          ST `hl7:"2"`
	GivenName           ST `hl7:"3"`
	MiddleInitialOrName ST `hl7:"4"`
	Suffix              ST `hl7:"5"`
	Prefix              ST `hl7:"6"`
	Degree              ST `hl7:"7"`
	SourceTable         ID `hl7:"8"`
	AssigningAuthority  ST `hl7:"9"`
}

// CNE - Coded with No Exceptions
type CNE struct {
	Identifier                     ST `hl7:"1"`
	Text                           ST `hl7:"2"`
	NameOfCodingSystem             ID `hl7:"3"`
	AlternateIdentifier            ST `hl7:"4"`
	AlternateText                  ST `hl7:"5"`
	NameOfAlternateCodingSystem    ID `hl7:"6"`
	CodingSystemVersionID          ST `hl7:"7"`
	AlternateCodingSystemVersionID ST `hl7:"8"`
	OriginalText                   ST `hl7:"9"`
}

// CP - Composite Price
// Example:
// |100.00&USD^UP^0^9^min^P~50.00&USD^UP^10^59^min^P~10.00&USD^UP^60^999^P ~50.00&USD^AP~200.00&USD^PF~80.00&USD^DC|
type CP struct {
	Price      MO `hl7:"1"`
	PriceType  ID `hl7:"2"`
	FromValue  NM `hl7:"3"`
	ToValue    NM `hl7:"4"`
	RangeUnits CE `hl7:"5"`
	RangeType  ID `hl7:"6"`
}

// CQ - Composite Quantity With Units
// In future versions, CQ fields should be avoided because the same data can usually be sent as two separate fields, one with the value and one with the units as a CE data type
//
// Examples:
//
// |123.7^kg|  kilograms is an ISO unit
// |150^lb&&ANSI+| weight in pounds is a customary US unit defined within ANSI+
type CQ struct {
	Quantity NM `hl7:"1"`
	Units    ST `hl7:"2"`
}

// CX - Extended Composite ID With Check Digit
// Example:
// |1234567^4^M11^ADT01^MR^University Hospital|
type CX struct {
	ID                                         ST `hl7:"1"`
	CheckDigit                                 ST `hl7:"2"`
	CodeIdentifyingTheCheckDigitSchemeEmployed ID `hl7:"3"`
	AssigningAuthority                         HD `hl7:"4"`
	IdentifierTypeCode                         IS `hl7:"5"`
	AssigningFacility                          HD `hl7:"6"`
}

// DLN - Driver's License Number
// This field contains the driver’s license information.  For state or province refer to official postal codes for that country; for country refer to ISO 3166 for codes
type DLN struct {
	DriverSLicenseNumber        ST `hl7:"1"`
	IssuingStateProvinceCountry IS `hl7:"2"`
	ExpirationDate              DT `hl7:"3"`
}

// DR - Date Time Range
type DR struct {
	RangeStartDateTime TS `hl7:"1"`
	RangeEndDateTime   TS `hl7:"2"`
}

// DT - Date
// In prior versions of HL7, this data type was  always specified to be in the format YYYYMMDD.  In the current and future versions, the precision of a date may be expressed by limiting the number of digits used with the format specification YYYY[MM[DD]].  Thus, YYYY is used to specify a precision of “year,” YYYYMM specifies a precision of “month,” and YYYYMMDD specifies a precision of “day.”
//
// By site-specific agreement,  YYYYMMDD may be used where backward compatibility must be maintained.
//
// Examples:
//
// |19880704|
// |199503|
type DT string

// DTM - Date/Time
type DTM string

// ED - Encapsulated Data
// This data type transmits encapsulated data from a source system to a destination system.  It contains the identity of the source system, the type of data, the encoding method of the data, and the data itself.  This data type is similar to the RP (reference pointer) data type of Section 2.8.34, “RP - reference pointer,” except that instead of pointing to the data on another system, it contains the data which is to be sent to that system.
type ED struct {
	SourceApplication HD `hl7:"1"`
	TypeOfData        ID `hl7:"2"`
	DataSubtype       ID `hl7:"3"`
	Encoding          ID `hl7:"4"`
	Data              ST `hl7:"5"`
}

// EI - Entity Identifier
// The entity identifier defines a given entity within a specified series of identifiers.
//
// The specified series, the assigning authority, is defined by components 2 through 4.  The assigning authority is of the hierarchic designator data type, but it is defined as three separate components in the EI data type, rather than as a single component as would normally be the case.  This is in order to maintain backward compatibility with the EI’s use as a component in several existing data fields. Otherwise, the components 2 through 4 are as defined in Section 2.8.18, “HD - hierarchic designator.”  Hierarchic designators are unique across a given HL7 implementation
type EI struct {
	EntityIdentifier ST `hl7:"1"`
	NamespaceID      IS `hl7:"2"`
	UniversalID      ST `hl7:"3"`
	UniversalIDType  ID `hl7:"4"`
}

// ELD - Error
type ELD struct {
	SegmentID            ST `hl7:"1"`
	Sequence             NM `hl7:"2"`
	FieldPosition        NM `hl7:"3"`
	CodeIdentifyingError CE `hl7:"4"`
}

// FC - Financial Class
type FC struct {
	FinancialClass IS `hl7:"1"`
	EffectiveDate  TS `hl7:"2"`
}

// FN - Family + Last Name Prefix
type FN struct {
	FamilyName     ST `hl7:"1"`
	LastNamePrefix ST `hl7:"2"`
}

// FT - Formatted Text Data
// This data type is derived from the string data type by allowing the addition of embedded formatting instructions.  These instructions are limited to those that are intrinsic and independent of the circumstances under which the field is being used.  The actual instructions and their representation are described later in this chapter.  The FT field is of arbitrary length (up to 64k) and may contain formatting commands enclosed in escape characters.  Example:
// |\.sp\(skip one vertical line)|
//
// For additional examples of formatting commands see Section 2.9, “Use of escape sequences in text fields.”
type FT string

// HD - Hierarchic Designator
// The HD is designed to be a more powerful application identifier.  It is also designed to be used either as a local version of a site-defined application identifier or a publicly-assigned UID.  Syntactically, the HD is a group of two application identifiers: one defined by the first component, and one defined by the second and third components.
//
// The HD allows any site to act as an assigning authority (on a local or user-defined basis), even if it technically does not have the right to issue new IDs within an identification scheme.  HDs which have defined third components (defined UID types) must be unique within the series of ID’s defined by that component.
type HD struct {
	NamespaceID     IS `hl7:"1"`
	UniversalID     ST `hl7:"2"`
	UniversalIDType ID `hl7:"3"`
}

// ID - Coded values for HL7 tables
// The value of such a field follows the formatting rules for an ST field except that it is drawn from a table of legal values. There shall be an HL7 table number associated with ID data types. Examples of ID fields include MSH-12-version ID and OBR-25-result status. This data type should be used only for HL7 tables (see Section 2.6.7, ID number). The reverse is not true, since in some circumstances it is more appropriate to use the CE data type for HL7 tables.
type ID string

// IS - Coded value for user-defined tables
// The value of such a field follows the formatting rules for a ST field except that it is drawn from a site-defined (or user-defined) table of legal values. There shall be an HL7 table number associated with IS data types. An example of an IS field is the Event reason code defined in Section 3.3.1.4, Event reason code. This data type should be used only for user-defined tables (see Section 2.6.7, ID number). The reverse is not true, since in some circumstances, it is more appropriate to use the CE data type for user-defined tables.
type IS string

// JCC - Job Code Class
type JCC struct {
	JobCode  IS `hl7:"1"`
	JobClass IS `hl7:"2"`
}

// LA1 - Location With Address Information (variant 1)
type LA1 struct {
	PointOfCare        IS `hl7:"1"`
	Room               IS `hl7:"2"`
	Bed                IS `hl7:"3"`
	Facility           HD `hl7:"4"`
	LocationStatus     IS `hl7:"5"`
	PersonLocationType IS `hl7:"6"`
	Building           IS `hl7:"7"`
	Floor              IS `hl7:"8"`
	Address            AD `hl7:"9"`
}

// LA2 - Location With Address Information (variant 2)
type LA2 struct {
	PointOfCare                IS `hl7:"1"`
	Room                       IS `hl7:"2"`
	Bed                        IS `hl7:"3"`
	Facility                   HD `hl7:"4"`
	LocationStatus             IS `hl7:"5"`
	PersonLocationType         IS `hl7:"6"`
	Building                   IS `hl7:"7"`
	Floor                      IS `hl7:"8"`
	StreetAddress              ST `hl7:"9"`
	OtherDesignation           ST `hl7:"10"`
	City                       ST `hl7:"11"`
	StateOrProvince            ST `hl7:"12"`
	ZipOrPostalCode            ST `hl7:"13"`
	Country                    ID `hl7:"14"`
	AddressType                ID `hl7:"15"`
	OtherGeographicDesignation ST `hl7:"16"`
}

// MA - Multiplexed Array
// This data type is used to represent channel-multiplexed waveform data, (e.g., the digitized values from an analog-to-digital converter or other digital data source).  Each value is of type NM, and represents a time sample from a channel.  This segment may contain data from one or more channels.  The waveform data is in channel-multiplexed format (that is, the values for all channels for the first time sample are transmitted, then the values for the next time sample, and so on until the requisite number of time samples have been transmitted).  Time samples are separated by repeat delimiters (~), and channels within a sample are separated by component delimiters (^).  The time between samples (the sampling interval) is the reciprocal of the digitization frequency as specified using the CD data type.
//
// 3 channels (identical), 5 time-samples
// |0^0^0~1^1^1~2^2^2~3^3^3~4^4^4~5^5^5|
//
// 1 channel, 11 time-samples
// |0~1~2~3~4~5~6~7~8~9~10|
type MA struct {
	Sample1FromChannel1 NM `hl7:"1"`
	Sample1FromChannel2 NM `hl7:"2"`
	Sample1FromChannel3 NM `hl7:"3"`
	Sample2FromChannel1 NM `hl7:"4"`
	Sample2FromChannel2 NM `hl7:"5"`
	Sample2FromChannel3 NM `hl7:"6"`
}

// MO - Money
type MO struct {
	Quantity     NM `hl7:"1"`
	Denomination ID `hl7:"2"`
}

// NA - Numeric Array
// This data type is used to represent a series (array) of numeric values, each one having a data type of NM.  A field of this type may contain a one-dimensional array (vector or row) of numbers.  Also, by allowing the field to repeat, a two-dimensional array (table) of numbers may be transmitted using this format, with each row of the table represented as one repetition of the field.  Arrays which have one or more values not present may be transmitted using this data type.  “Not present” values are represented as two adjacent component delimiters.  If the absent values occur at the end of a row, the trailing component delimiters may be omitted.  If an entire row of a table has no values, no component delimiters are necessary (in this case, there will be two adjacent repetition delimiters).  The maximum number of values in one repetition of an NA format field is determined by the maximum field length.
//
// Vector of 8 numbers
// |125^34^-22^-234^569^442^-212^6|
//
// 3 x 3 array of numbers
// |1.2^-3.5^5.2~2.0^3.1^-6.2~3.5^7.8^-1.3|
//
// 5 x 4 array of numbers **
// |^2^3^4~5^^^8~9^10~~17^18^19^20|
//
// ** the values in positions (1,1), (2,2), (2,3), (3,3), (3,4), (4,1), (4,2), (4,3), and (4,4) not present
type NA struct {
	Value1 NM `hl7:"1"`
	Value2 NM `hl7:"2"`
	Value3 NM `hl7:"3"`
	Value4 NM `hl7:"4"`
}

// NM - Numeric
// A number represented as a series of ASCII numeric characters consisting of an optional leading sign ( + or -), the digits and an optional decimal point. In the absence of a sign, the number is assumed to be positive. If there is no decimal point the number is assumed to be an integer. Examples:
type NM string

// PL - Person Location
// This data type is used to specify a patient location within a healthcare institution. Which components are valued depends on the needs of the site.  It is most commonly used for specifying patient locations, but may refer to other types of persons within a healthcare setting.
type PL struct {
	PointOfCare        IS `hl7:"1"`
	Room               IS `hl7:"2"`
	Bed                IS `hl7:"3"`
	Facility           HD `hl7:"4"`
	LocationStatus     IS `hl7:"5"`
	PersonLocationType IS `hl7:"6"`
	Building           IS `hl7:"7"`
	Floor              IS `hl7:"8"`
	LocationType       ST `hl7:"9"`
}

// PN - Person Name
// Example:
// |SMITH^JOHN^J^III^DR^PHD|
//
// This data type includes multiple free text components.  Each component is specified to be an HL7 ST data type.  The maximum length of a PN field is 48 characters including component separators.  The sending system may send upper- and lowercase or all uppercase. The receiving system may convert to all uppercase if required.
type PN struct {
	FamilyName          ST `hl7:"1"`
	GivenName           ST `hl7:"2"`
	MiddleInitialOrName ST `hl7:"3"`
	Suffix              ST `hl7:"4"`
	Prefix              ST `hl7:"5"`
	Degree              ST `hl7:"6"`
}

// PPN - Performing Person Time Stamp
// This data type is the equivalent of an XCN data type joined with a TS data type.  However,  since HL7 does not support subcomponents in Version 2.3, the XCD data type has been flattened.
type PPN struct {
	IDNumber                                   ST `hl7:"1"`
	FamilyName                                 ST `hl7:"2"`
	GivenName                                  ST `hl7:"3"`
	MiddleInitialOrName                        ST `hl7:"4"`
	Suffix                                     ST `hl7:"5"`
	Prefix                                     ST `hl7:"6"`
	Degree                                     ST `hl7:"7"`
	SourceTable                                ID `hl7:"8"`
	AssigningAuthority                         HD `hl7:"9"`
	NameTypeCode                               ID `hl7:"10"`
	IdentifierCheckDigit                       ST `hl7:"11"`
	CodeIdentifyingTheCheckDigitSchemeEmployed ID `hl7:"12"`
	IdentifierTypeCode                         IS `hl7:"13"`
	AssigningFacility                          HD `hl7:"14"`
	DateTimeActionPerformed                    TS `hl7:"15"`
}

// PT - Processing Type
// This data type indicates whether to process a message as defined in HL7 Application (level 7) Processing rules
type PT struct {
	ProcessingID   ST `hl7:"1"`
	ProcessingMode ST `hl7:"2"`
}

// PTS - Authentication person, time stamp
// This field contains a set of components describing by whom and when authentication was performed.  Whenever any one of the ID number - Name type code component s is valued, the when authenticated component, which is time stamp, must be valued as non-null.  If the time component of a set is valued as non-null, the person component becomes required. These subcomponents are normally delimited by an ampersand (&).  See Chapter 2.
type PTS struct {
	AuthenticationPerson    XCN `hl7:"1"`
	AuthenticationTimeStamp TS  `hl7:"2"`
}

// QIP - Query Input Parameter List
// Definition:  This field contains the list of parameter names and values to be passed to the stored procedure
type QIP struct {
	FieldName          ST `hl7:"1"`
	Value1Value2Value3 ST `hl7:"2"`
}

// QSC - Query Selection Criteria
// This field indicates the conditions that qualify the rows to be returned in the query response.  (This field conveys the same information as the “WHERE” clause in the corresponding SQL expression of the query, but is formatted differently.)
type QSC struct {
	NameOfField           ST `hl7:"1"`
	RelationalOperator    ID `hl7:"2"`
	Value                 ST `hl7:"3"`
	RelationalConjunction ID `hl7:"4"`
}

// RCD - Row Column Definition
// Each repetition of this field consists of three components
type RCD struct {
	HL7ItemNumber      ST `hl7:"1"`
	HL7DateType        ST `hl7:"2"`
	MaximumColumnWidth NM `hl7:"3"`
}

// RI - Repeat Interval
// This field contains the interval between repeating appointments.  The default setting indicates that the appointment should occur once, when the component is not valued.  The definition of this field is equivalent to the definition of the Interval component of the Quantity/Timing field given in Chapter 4, Section 4.4.2 “Interval component (CM).”
type RI struct {
	RepeatPattern        IS `hl7:"1"`
	ExplicitTimeInterval ST `hl7:"2"`
}

// RP - Reference Pointer
// This data type transmits information about data stored on another system.  It contains a reference pointer that uniquely identifies the data on the other system, the identity of the other system, and the type of data.
type RP struct {
	Pointer       ST `hl7:"1"`
	ApplicationID HD `hl7:"2"`
	TypeOfData    ID `hl7:"3"`
	Subtype       ID `hl7:"4"`
}

// SCV - Scheduling Class Value Pair
// For use only with the scheduling chapter.
//
// This field is used to communicate parameters and preferences to the filler application regarding the selection of an appropriate time slot, resource, location, or filler override criterion  for an appointment
type SCV struct {
	ParameterClass IS `hl7:"1"`
	ParameterValue ST `hl7:"2"`
}

// SI - Sequence ID
// A non-negative integer in the form of an NM field.  The uses of this data type are defined in the chapters defining the segments and messages in which it appears
type SI string

// SN - Structured Numeric
// The structured numeric data type is used to unambiguously express numeric clinical results along with qualifications.  This enables receiving systems to store the components separately, and facilitates the use of numeric database queries.  The corresponding sets of values indicated with the <comparator> and <separator/suffix> components are intended to be the authoritative and complete set of values.  If additional values are needed for the  <comparator> and <separator/suffix> components, they should be submitted to HL7 for inclusion in the Standard.
//
// If <num1> and <num2> are both non-null, then the separator/suffix must be non-null.  If the separator is “-”, the data range is inclusive; e.g., <num1> - <num2> defines a range of numbers x, such that:  <num1> <=x<= <num2>
//
// Examples:
// greater than 100
// |>^100|
//
// equal to range of 100 through 200
// |^100^-^200|
//
// ratio of 1 to 128, e.g., the results of a serological test
// |^1^:^228|
//
// categorical response, e.g., occult blood positivity
// |^2^+|
type SN struct {
	Comparator        ST `hl7:"1"`
	Num1              NM `hl7:"2"`
	SeparatorOrSuffix ST `hl7:"3"`
	Num2              NM `hl7:"4"`
}

// ST - String Data
// To include any HL7 delimiter character (except the segment terminator) within a string data field, use the appropriate HL7 escape sequence (see Section 2.9.1, Formatting codes).
type ST string

// TM - Time
// Format: HH[MM[SS[.S[S[S[S]]]]]][+/-ZZZZ]
//
// In prior versions of HL7, this data type was always specified to be in the format HHMM[SS[.SSSS]][+/ZZZZ] using a 24 hour clock notation.  In the current and future versions, the precision of a time may be expressed by limiting the number of digits used with the format specification as shown above.  By sitespecific agreement, HHMM[SS[.SSSS]][+/-ZZZZ] may be used where backward compatibility must be maintained.
//
// Thus, HH is used to specify a precision of “hour,” HHMM is used to specify a precision of “minute,” HHMMSS is used to specify a precision of seconds, and HHMMSS.SSSS is used to specify a precision of  ten-thousandths of a second.
//
// In each of these cases, the time zone is an optional component. The fractional seconds could be sent by a transmitter who requires greater precision than whole seconds.  Fractional representations of minutes, hours or other higher orders units of time are not permitted.
// The time zone of the sender may be sent optionally as an offset from the coordinated universal time (previously known as Greenwich Mean Time).  Where the time zone is not present in a particular TM field but is included as part of the date/time field in the MSH segment, the MSH value will be used as the default time zone.  Otherwise, the time is understood to refer to the local time of the sender.  Midnight is represented as 0000.
//
// Examples:
//
// 1 second before midnight in a time zone eleven hours ahead of Universal Coordinated Time (i.e., east of Greenwich).
// |235959+1100|
//
// Eight AM, local time of the sender.
// |0800|
//
// 44.2312 seconds after Nine thirty-five AM, local time of sender.
// |093544.2312|
//
// 1pm (with a precision of hours), local time of sender.
// |13|
type TM string

// TN - Telephone Number
// For use in the United States and conforming countries, the telephone number is always in the form:
//
// Format:  [NN] [(999)]999-9999[X99999][B99999][C any text]
//
// The optional first two digits are the country code.  The optional X portion gives an extension.  The optional B portion gives a beeper code.  The optional C portion may be used for comments like, After 6:00.  While no explicit limit is placed on the text field, receiving systems may be expected to truncate values that are more than 10 characters long.  To accommodate the variability of institutional phone systems, the length of the extension and beeper numbers may be extended by local agreement.
//
// Examples:
// |(415)925-0121X305|
// |234-4532CWEEKENDS|
type TN string

// TQ - Timing Quantity
// Quantity/timing (ORC-7, OBR-27) provides a means of specifying when the service described by the order segment is to be performed and how frequently.  It is a complex multicomponent field that can have repeats; i.e., more than one quantity/timing specification, separated by repeat delimiters, may appear.  It is a distinct data type (see Section 2.8.41, “TQ - timing quantity”).  The components of a single quantity/timing specification are described in the Sections: 4.4.1, “Quantity component  (CQ),” through 4.4.10, “Order sequencing component (CM).”
type TQ struct {
	Quantity        CQ     `hl7:"1"`
	Interval        RI     `hl7:"2"`
	Duration        ST     `hl7:"3"`
	StartDateTime   TS     `hl7:"4"`
	EndDateTime     TS     `hl7:"5"`
	Priority        ST     `hl7:"6"`
	Condition       ST     `hl7:"7"`
	Text            TX     `hl7:"8"`
	Conjunction     ST     `hl7:"9"`
	OrderSequencing CM_OSD `hl7:"10"`
}

// TS - Time Stamp
// Contains the exact time of an event, including the date and time. The date portion of a time stamp follows the rules of a date field and the time portion follows the rules of a time field. The time zone (+/-ZZZZ) is represented as +/-HHMM offset from UCT (formerly Greenwich Mean Time (GMT)), where +0000 or -0000 both represent UCT (without offset). The specific data representations used in the HL7 encoding rules are compatible with ISO 8824-1987(E).
type TS struct {
	TimeOfAnEvent ST `hl7:"1"`
}

// TX - Text Data
// String data meant for user display (on a terminal or printer).  Such data would not necessarily be left justified since leading spaces may contribute greatly to the clarity of the presentation to the user.  Because this type of data is intended for display, it may contain certain escape character sequences designed to control the display.  Escape sequence formatting is defined later in this chapter in Section 2.9, “Use of escape sequences in text fields.”  Leading spaces should be included.  Trailing spaces should be removed.
//
// Example:
// |  leading spaces are allowed.|
//
// Since TX data is intended for display purposes, the repeat delimiter, when used with a TX data field, implies a series of repeating lines to be displayed on a printer or terminal.  Therefore, the repeat delimiters are regarded as paragraph terminators or hard carriage returns (e.g., they would display as though a CR/LF were inserted in the text (DOS type system) or as though a LF were inserted into the text (UNIX style system)).
//
// A receiving system would word-wrap the text between repeat delimiters in order to fit it into an arbitrarily sized display window but start any line beginning with a repeat delimiter on a new line.
//
// Usage note: the maximum length of a TX data field is 64K
type TX string

// VARIES - Variable Datatype
type VARIES string

// VH - Visiting Hours
// This data type contains the hours when a patient location is open for visiting.  Refer to HL7 table 0267 - Days of the week for valid values for the first two components
type VH struct {
	StartDayRange  ID `hl7:"1"`
	EndDayRange    ID `hl7:"2"`
	StartHourRange TM `hl7:"3"`
	EndHourRange   TM `hl7:"4"`
}

// VID - Version Identifier
type VID struct {
	VersionId                ID `hl7:"1"`
	InternationalizationCode CE `hl7:"2"`
	InternationalVersionId   CE `hl7:"3"`
}

// XAD - Extended Address
// Example:
// |1234 Easy St.^Ste. 123^San Francisco^CA^95123^USA^B^^SF^|
type XAD struct {
	StreetAddress              ST `hl7:"1"`
	OtherDesignation           ST `hl7:"2"`
	City                       ST `hl7:"3"`
	StateOrProvince            ST `hl7:"4"`
	ZipOrPostalCode            ST `hl7:"5"`
	Country                    ID `hl7:"6"`
	AddressType                ID `hl7:"7"`
	OtherGeographicDesignation ST `hl7:"8"`
	CountyParishCode           IS `hl7:"9"`
	CensusTract                IS `hl7:"10"`
}

// XCN - Extended Composite ID Number And Name
// Example:
// |1234567^Smith^John^J^III^DR^PHD^ADT01^^L^4^M11^MR|
type XCN struct {
	IDNumber                                   ST `hl7:"1"`
	FamilyName                                 ST `hl7:"2"`
	GivenName                                  ST `hl7:"3"`
	MiddleInitialOrName                        ST `hl7:"4"`
	Suffix                                     ST `hl7:"5"`
	Prefix                                     ST `hl7:"6"`
	Degree                                     ST `hl7:"7"`
	SourceTable                                IS `hl7:"8"`
	AssigningAuthority                         HD `hl7:"9"`
	NameType                                   ID `hl7:"10"`
	IdentifierCheckDigit                       ST `hl7:"11"`
	CodeIdentifyingTheCheckDigitSchemeEmployed ID `hl7:"12"`
	IdentifierTypeCode                         IS `hl7:"13"`
	AssigningFacilityID                        HD `hl7:"14"`
}

// XON - Extended Composite Name And ID For Organizations
// Example:
// |HL7 Health Center^L^6^M11^HCFA|
type XON struct {
	OrganizationName                           ST `hl7:"1"`
	OrganizationNameTypeCode                   IS `hl7:"2"`
	IDNumber                                   NM `hl7:"3"`
	CheckDigit                                 ST `hl7:"4"`
	CodeIdentifyingTheCheckDigitSchemeEmployed ID `hl7:"5"`
	AssigningAuthority                         HD `hl7:"6"`
	IdentifierTypeCode                         IS `hl7:"7"`
	AssigningFacilityID                        HD `hl7:"8"`
}

// XPN - Extended Person Name
// Example:
// |Smith^John^J^III^DR^PHD^L|
type XPN struct {
	FamilyName             ST `hl7:"1"`
	GivenName              ST `hl7:"2"`
	MiddleInitialOrName    ST `hl7:"3"`
	Suffix                 ST `hl7:"4"`
	Prefix                 ST `hl7:"5"`
	Degree                 ST `hl7:"6"`
	NameTypeCode           ID `hl7:"7"`
	NameRepresentationCode ID `hl7:"8"`
}

// XTN - Extended Telecommunication Number
// Example:
// (415)555-3210^ORN^FX^
type XTN struct {
	TelephoneNumber                TN `hl7:"1"`
	TelecommunicationUseCode       ID `hl7:"2"`
	TelecommunicationEquipmentType ID `hl7:"3"`
	EmailAddress                   ST `hl7:"4"`
	CountryCode                    NM `hl7:"5"`
	AreaCityCode                   NM `hl7:"6"`
	PhoneNumber                    NM `hl7:"7"`
	Extension                      NM `hl7:"8"`
	AnyText                        ST `hl7:"9"`
}
